konflux-ci/e2e-tests

.github/workflows/PR.yaml
.github/workflows/build.yaml

feat: Setup PR check and post-merge build&push

---

pkg/framework/common/appstudio.go
pkg/framework/common/controller/pipelines.go
scripts/Readme.md

After PR: https://github.com/redhat-appstudio/infra-deployments/pull/38 the pipelines are removed and created clusterTasks instead.

Check Cluster Tasks e2e

---

go.mod
go.sum
pkg/tests/common/appstudio.go
pkg/tests/has/application.go
pkg/utils/common/controller.go

Add a timeout to wait for AppStudio Application to be up and ready.
Also the PR is updating the HAS version to the last one.

Improve argo cd components status checks

---

cmd/e2e_test.go
go.mod

This PR is adding a check for the secret `has-github-token` in the `application-service` namespace, so it stops the execution if the secret is not found.

Add secret check inside SynchronizedBeforeSuite

---

.ci/openshift-ci/oci-launch-e2e.sh

Add JUnit output to OpenShift CI

---

cmd/e2e_test.go
go.mod
go.sum
pkg/framework/webhook.go
webhookConfig.yml

RHDP-434 Add support for sending webhooks after the tests finished

---

README.md
pkg/tests/has/Readme.md
scripts/Readme.md
scripts/install-appstudio-e2e-mode.sh

Improve e2e documentation

---

pkg/tests/build/chains.go
pkg/utils/common/controller.go
pkg/utils/tekton/controller.go
pkg/utils/tekton/tasks.go

Create kaniko demo tasks
Create tasks to run cosign verify and cosign verify attestation
Other misc orchestration tasks to watch and monitor pods/tasks
This depends on two other PRs
https://github.com/redhat-appstudio/infra-deployments/pull/204

Create chains task integration tests

---

.ci/openshift-ci/Dockerfile

Install latest yq version compatible with appstudio

Fix openshift-ci test container

---

cmd/e2e_test.go
pkg/framework/framework.go
pkg/tests/cluster-registration/README.md
pkg/tests/cluster-registration/clusters.go

Part of issue https://issues.redhat.com/browse/CMCS-50

Cluster reg

---

pkg/framework/framework.go
pkg/tests/has/devfile_source.go

Introduce AfterAll function to remove CRs after tests running.

Add `AfterAll` function to remove resources

---

.github/workflows/conventional-commits.yaml
pkg/constants/constants.go
tests/cluster-registration/clusters.go

-  Added Conventional commits check inorder to maintain good commit messages 
- Added Cluster registration Namespace as Constant 
Signed off by msawood@redhat.com

core: Added conventional commits check and also added CR NS as constant

---

pkg/utils/tekton/tasks.go

Remove reliance on an external Tekton bundle and simply inline the
definition in the tests making the test more self-contained.
Signed-off-by: Luiz Carvalho <lucarval@redhat.com>

fix: Cleanup buildah-demo task

---

go.mod
pkg/utils/tekton/controller.go
pkg/utils/tekton/tasks.go
tests/build/chains.go

https://issues.redhat.com/browse/HACBS-46

feat: Add coverage for verify-ec task

---

.github/workflows/PR.yaml
pkg/utils/tekton/controller_test.go

* add CI job for running unit tests
* fix tekton controller unit tests

test: run unit tests per PR

---

.ci/oci-launch-e2e.sh
scripts/spi-e2e-setup.sh

This scripts will help: https://github.com/redhat-appstudio/e2e-tests/pull/63

ci: Add script to setup SPI for e2e tests

---

scripts/e2e-openshift-ci.sh

Disable openshift ci user provision in has
x

fix: Disable openshift ci user provision in external repos

---

.github/CODEOWNERS

Add Alessandro Barbarossa to owner files
N/A

Add Alessandro Barbarossa to owner files

---

scripts/install-appstudio-e2e-mode.sh

Initialize SPI vault in all jobs

fix: Add command to initialize SPI vault

---

pkg/utils/has/controller.go
tests/has/devfile_private_source.go
tests/has/devfile_source.go

Signed-off-by: John Collier <jcollier@redhat.com>
This PR updates the existing HAS e2e tests to create a `ComponentDetectionQuery` (CDQ) resource in the tests, and to create the test repo's `Component` resource from the results of that CDQ.
https://issues.redhat.com/browse/DEVHAS-74

test: [DEVHAS-74] Add ComponentDetectionQuery to HAS e2e tests

---

pkg/utils/common/controller.go
pkg/utils/has/controller.go
pkg/utils/release/controller.go
tests/build/build.go
tests/e2e-demos/quarkus_curated.go
tests/has/devfile_private_source.go
tests/has/devfile_source.go
tests/release/release.go

fix: Hacbs 701/move namespace funcs

---

.ci/oci-launch-e2e.sh
pkg/framework/webhook.go
webhookConfig.yml

feat: RHDP-442 Update webhook parameters

---

tests/release/release-failures.go
tests/release/release.go

Jira: https://issues.redhat.com/browse/HACBS-650

test: [Hacbs 650]/failure missing release strategy

---

tests/e2e-demos/config/default.yaml
tests/integration-service/integration.go

Change nodejs application tests to point to redhat-appstudio-qe organization. Also this PR change the quarkus repo in integration tests to golang one. Quarkus repo have to much dependencies and that make sbom to take to much time in ci and the PR fails

feat: Add nodejs very simple application for tests

---

README.md
tests/release/const.go
tests/release/release-failures.go
tests/release/release.go

https://issues.redhat.com/browse/HACBS-834

test: Hacbs 834/create constants module in release tests folder

---

tests/build/chains.go

We're having issues running the chains tests, this disables running them
to unblock the work until we troubleshot and fix the issues in the
tests.
https://issues.redhat.com/browse/HACBS-894

fix: skip chains tests

---

tests/build/jvm-build.go

* skip printing out logs from pipelinerun in case the pipelinerun succeeded
* skip specs for checking dependencybuilds due to https://issues.redhat.com/browse/PLNSRVCE-519 (might not be needed if it's get fixed soon)
* skip deleting taskruns (deleting related pipelinerun is sufficient)
* updated "wait intervals" to speed up the test execution
N/A
```bash
ginkgo --progress --focus="jvm-build-service" ./cmd -- --config-suites=/Users/psturc/work/redhat-appstudio/e2e-tests/tests/e2e-demos/config/default.yaml
```

fix: jvm-build-test

---

scripts/install-appstudio-e2e-mode.sh
scripts/spi-e2e-setup.sh
tests/build/build.go
tests/build/jvm-build.go

See https://github.com/redhat-appstudio/e2e-tests/pull/152#issue-1315156916 plus https://github.com/redhat-appstudio/e2e-tests/pull/152#issuecomment-1192803843
@psturc @flacatus 
n/a
- [/] Bug fix (non-breaking change which fixes an issue)
- [/] I have performed a self-review of my code

fix: vault plus build e2e

---

pkg/utils/has/controller.go
tests/e2e-demos/Readme.md
tests/e2e-demos/config/default.yaml
tests/e2e-demos/config/types.go
tests/e2e-demos/const.go
tests/e2e-demos/e2e-demo.go

Adding scale replicas test to e2e-demo suite: if the replicas field in the component yaml definition is greater than 1 the test will be performed, skipped otherwise. 

test: add component replica scale test

---

.github/pull_request_template.md
README.md
docs/LabelsNaming.md
pkg/framework/describe.go
scripts/install-appstudio-e2e-mode.sh
tests/build/build.go
tests/build/chains.go
tests/build/jvm-build.go
tests/cluster-registration/clusters.go
tests/e2e-demos/e2e-demo.go
tests/has/devfile_private_source.go
tests/has/devfile_source.go
tests/integration-service/integration.go
tests/release/release-failures.go
tests/release/release.go

feat: RHDP-453 Add Test labels

---

.ci/oci-launch-e2e.sh

To unblock PRs merging let's skip the `ec` tests for now.

fix: skip `ec` tests for now

---

pkg/utils/tekton/controller.go

fix error `unable to remove finalizers from PipelineRun` seen recently in [CI run](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/logs/periodic-ci-redhat-appstudio-infra-deployments-main-appstudio-e2e-deployment-periodic/1557155135581327360/artifacts/appstudio-e2e-deployment-periodic/appstudio-e2e-deployment-periodic/build-log.txt)
N/A
```bash
for i in {1..10}; do echo $i && ginkgo --focus="Creating a component with a specific container image URL" --progress -v ./cmd -- --config-suites=/Users/psturc/work/redhat-appstudio/e2e-tests/tests/e2e-demos/config/default.yaml > /dev/null || echo ERROR; done
```

fix: improve method for removing PR finalizers

---

cmd/loadTests.go
pkg/utils/has/controller.go
tests/build/build.go
tests/build/jvm-build.go
tests/e2e-demos/e2e-demo.go
tests/integration-service/integration.go

Re-add jvm-build-service tests
https://issues.redhat.com/browse/PLNSRVCE-533
```
ginkgo --focus="jvm-build-service" --progress -v ./cmd -- --config-suites=/path/to/e2e-tests/tests/e2e-demos/config/default.yaml
```

feat: Add in jvm-build-service tests again

---

tests/has/devfile_source.go

Delete a component and check if gitops stuffs are not getting deleted.
https://issues.redhat.com/browse/RHDP-479

feat: Component deletion tests

---

pkg/utils/common/controller.go

improvement of the error message for missing 'pipeline' service account
N/A
in CI

fix: improve error message for missing pipeline sa

---

magefiles/magefile.go
pkg/utils/util.go
tests/build/build.go
tests/build/jvm-build.go
tests/e2e-demos/e2e-demo.go
tests/has/devfile_private_source.go
tests/has/devfile_source.go
tests/integration-service/integration.go

Run e2e tests in parallel in CI

chore: Run e2e tests in parallel

---

cmd/loadTests.go
magefiles/magefile.go
magefiles/utils.go
pkg/apis/github/git.go
pkg/apis/github/pull_request.go
pkg/apis/github/repositories.go
pkg/utils/common/controller.go
pkg/utils/has/controller.go
pkg/utils/tekton/controller.go
pkg/utils/util.go
tests/build/build.go
tests/build/jvm-build.go
tests/has/devfile_source.go
tests/integration-service/integration.go

update build-service test to test PaC builds
https://issues.redhat.com/browse/PLNSRVCE-580
```bash
ginkgo --label-filter="github-webhook" --progress -v ./cmd -- --config-suites=/Users/psturc/work/redhat-appstudio/e2e-tests/tests/e2e-demos/config/default.yaml
```

feat: PaC build test coverage

---

tests/build/chains.go

Reduce the amount of policy violations reported during test to ensure we stay under the 4k limit imposed by Tekton on results.
https://issues.redhat.com/browse/HACBS-1111
I was able to reproduce the reported issue on my dev cluster, then I verified the fix is working on the same cluster.

fix: Reduce EC report size to avoid 4k limit

---

scripts/spi-e2e-setup.sh

infra-deployment's PR https://github.com/redhat-appstudio/infra-deployments/pull/638 brings in some name changes to SPI
configuration. This PR makes it possible for the CI to pass for both the main branch as well as that PR.
Once PR https://github.com/redhat-appstudio/infra-deployments/pull/638 is merged, I will create a new PR that will remove
the legacy naming from the script.
https://issues.redhat.com/browse/SVPI-175
It hasn't been.. I don't know how to test this, but the change seems quite simple. I admit to just be crossing fingers here :)

fix: Temporarily create 2 secrets with the SPI config file

---

tests/build/build.go

Fixes an issue with leftover webhooks in https://github.com/redhat-appstudio-qe/devfile-sample-hello-world repo
N/A

fix: build: remove repo webhook from github

---

magefiles/magefile.go
tests/build/build.go
tests/build/chains.go
tests/build/jvm-build.go
tests/integration-service/integration.go

Add "HACBS" label to hacbs-specific e2e.
TODO
https://issues.redhat.com/browse/HACBS-988
in CI

feat: preparations for HACBS periodic job

---

tests/e2e-demos/multi-component.go

This PR adds multi-component creation tests to the e2e-demos suite. The system will bring in multi components from a git repo and we can see that they are all created and deployed
[RHDP-499](https://issues.redhat.com/browse/RHDP-499
)

test: add mutlicomponent creation tests to e2e-demos suite

---

tests/build/build.go

Noticed the [runtime error in the nightly periodic job](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-redhat-appstudio-infra-deployments-pre-kcp-appstudio-e2e-deployment-periodic/1570201047329148928)
This PR should fix it 
N/A
in CI

fix: build: runtime error

---

pkg/utils/build/hacbs.go
tests/build/build.go

Signed-off-by: srivickynesh <sselvan@redhat.com>

test: add test for hacbs pipeline

---

.github/pull_request_template.md
README.md
tests/has/devfile_source.go

Contribution guide update
No JIRA.
Just documentation update.

docs: Updated contribution guide

---

pkg/utils/util.go

i noticed an illegal use of gomega functions which impacts load tests thus changing it. 

fix: Refactoring using  go omega functions in utils

---

scripts/install-appstudio-kcp.sh

Detect when we are in infra-deployments repository.

chore: Fix e2e installation gap

---

tests/build/chains.go

There's an issue related to Rekor integration that needs to be fixed. The fix will be done in:
https://issues.redhat.com/browse/HACBS-1349
Signed-off-by: Luiz Carvalho <lucarval@redhat.com>

test: Disable ec tests

---

tests/build/build.go

Related to [PLNSRVCE-800](https://issues.redhat.com//browse/PLNSRVCE-800) and redhat-appstudio/build-definitions#226
Signed-off-by: Chenxiong Qi <cqi@redhat.com>

fix: do not change pipeline bundle name

---

pkg/utils/build/hacbs.go
pkg/utils/has/controller.go
tests/build/build.go

Signed-off-by: Hongwei Liu  hongliu@redhat.com
Add tekton task sbom-json-check to e2e test
[HACBS-1213](https://issues.redhat.com/browse/HACBS-1213)
CI will test it

feat: add task sbom-json-check to e2e test

---

tests/build/build.go

Signed-off-by: Sri Vignesh <sselvan@redhat.com>

feat: HACBS-973 add ClamAV results to HACBS pipeline

---

pkg/utils/integration/controller.go
tests/integration-service/integration.go

feat: Add happy path test cases for integration service

---

tests/integration-service/integration.go

fix integration test - ignore errors about missing PipelineRuns before they are actually triggered

fix: integration svc: wait for PipelineRun init

---

magefiles/magefile.go

we've hit an issue when running a job from a PR in infra-deployments
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/redhat-appstudio_infra-deployments/954/pull-ci-redhat-appstudio-infra-deployments-main-appstudio-e2e-tests/1595424474709102592#1:build-log.txt%3A79-80
N/A

fix: infra-deployments PR job

---

magefiles/magefile.go

ignore ci bots accounts as authors

fix: ignore ci bots accounts as authors

---

go.mod
go.sum
pkg/utils/build/hacbs.go
pkg/utils/has/controller.go
pkg/utils/tekton/controller.go
pkg/utils/tekton/matchers.go
pkg/utils/tekton/matchers_test.go

update tektoncd/pipeline module (v0.37.0) and test it with https://github.com/redhat-appstudio/infra-deployments/pull/954

chore: update tektoncd/pipeline module (v0.37.0)

---

tests/build/build.go

Signed-off-by: Chenxiong Qi <cqi@redhat.com>

test: PLNSRVCE-693: work with repo url which ends with .git

---

tests/e2e-demos/multi-component.go

Since we cannot reproduce the error locally, adding conditional removal of application in multicomponent tests to make the log available after the job finishes and understand why the periodic job sometimes fails. 

fix: don't remove applications if pipeline fails

---

pkg/utils/tekton/pipelines.go
tests/build/chains.go

This PR makes the minimal amount of changes to restore the Chains/EC tests:
* use non-deprecated ec task
* use proper policy source
* remove pending status
https://issues.redhat.com/browse/HACBS-1349
Tested against an OpenShift 4.11 cluster on quicklab.

fix: restore enterprise contract tests

---

tests/build/chains.go

Determine which bundle to use for the verify-enterprise-contract task from the cluster configuration.
https://issues.redhat.com/browse/HACBS-1412
Tested against my dev cluster in quicklab.

feat: use ConfigMap for ec bundle

---

tests/build/build.go

Repository protection was removed, there is a bug for tracking what to do next - PLNSRVCE-952.

fix: disable repository protection tests

---

pkg/utils/build/sbom.go

Remove extracted image content at the end of function.

fix: sbom - delete extracted image

---

magefiles/magefile.go
magefiles/utils.go
pkg/utils/util.go
scripts/install-appstudio.sh

feat: Generate user's kubeconfig

---

tests/release/release.go

This reverts commit d2d5ce25d5e77e94fe401ffe21cb564487d89bdd.

fix: revert - disable release tests

---

pkg/utils/integration/controller.go

* Update component/snapshot labels for integration tests
[HACBS-1576](https://issues.redhat.com//browse/HACBS-1576)
- [*] Bug fix (non-breaking change which fixes an issue)

fix(HACBS-1576): update component and snapshot labels

---

tests/e2e-demos/multi-component.go

Multi-component is not fully supported yet due an error in HAS service. 
Please see jira for more context: https://issues.redhat.com/browse/DEVHAS-225

fix: Skip temporary multi component tests due an error on application-service cdq

---

tests/e2e-demos/config/config.go
tests/e2e-demos/config/default.yaml
tests/e2e-demos/config/types.go
tests/e2e-demos/e2e-demo.go

Disable container tests until issue https://issues.redhat.com/browse/STONE-336 it is resolved

fix: skip temporary container tests until STONE-336 issue is resolved

---

tests/build/build.go
tests/build/chains.go

Increasing timeout from 10 mintues to 15. There was execution which had 10 minutes and 31 seconds.

fix: increase timeout for pipelinerun

---

pkg/utils/common/controller.go
tests/build/build.go

[PLNSRVCE-967](https://issues.redhat.com//browse/PLNSRVCE-967)

feat: build - remove registry-auth

---

tests/integration-service/OWNERS

chore: Add owners for integration service test suite

---

magefiles/installation/install.go

fix: STONE-421 fix misspelled "toolchain"

---

tests/build/build.go

See [this comment](https://github.com/redhat-appstudio/infra-deployments/pull/1207#issuecomment-1401565689)
N/A
in CI

fix: build: skip CR deletion in case of failure

---

README.md

remove outdated info
- non existing shell script
- env var that is not used anymore
N/A
\-

docs: remove outdated info

---

tests/release/OWNERS

[Issue ticket number and link](https://issues.redhat.com/browse/HACBS-1748)

fix: Adding OWNERS file to tests/release with users of release team

---

pkg/utils/has/controller.go
pkg/utils/util.go
tests/build/jvm-build.go

fix: jvm-build: skip CR deletion on a failure, nicer error output

---

magefiles/magefile.go

Add more complex tests to application-service repo
https://issues.redhat.com/browse/DEVHAS-248

feat: Run e2e demos in application-service PRs

---

tests/e2e-demos/config/default.yaml

feat: Add python with devfile test scenario

---

tests/e2e-demos/e2e-demo.go

feat: Retry pipeline in case if fail for some external reasons like quay connection is flaky

---

tests/build/build.go

JIRA [HACBS-1654](https://issues.redhat.com/browse/HACBS-1654), [HACBS-1695](https://issues.redhat.com/browse/HACBS-1695)

fix: update hacbs pipeline validation

---

go.sum
pkg/framework/framework.go
tests/build/chains.go
tests/cluster-registration/clusters.go
tests/e2e-demos/multi-component.go
tests/has/devfile_private_source.go
tests/has/devfile_source.go
tests/integration-service/integration.go
tests/release/e2e-test-default-bundle.go
tests/release/release.go

First reason for this PR is that initializing of the framework should be done in setup nodes (BeforeAll/BeforeEach) and we should avoid [doing assertions in container nodes](https://onsi.github.io/ginkgo/#no-assertions-in-container-nodes)
Second reason is that testing of changes to a single test during test development was slow. That was caused by the initialization of the framework during [tree construction phase](https://onsi.github.io/ginkgo/#mental-model-how-ginkgo-traverses-the-spec-hierarchy), which means that whenever a ginkgo command was run (to validate the changes to the test done during development), it triggered the framework initialization in all tests that didn't have the framework init defined in `BeforeAll` setup node (the slowest part IMO is …

fix: move framework init into BeforeAll

---

cmd/e2e_test.go
cmd/loadTests.go
pkg/framework/describe.go
pkg/sandbox/sandbox.go
pkg/utils/common/controller.go
pkg/utils/has/controller.go
pkg/utils/integration/controller.go
pkg/utils/release/controller.go
tests/build/build.go
tests/build/jvm-build.go
tests/e2e-demos/e2e-demo.go
tests/e2e-demos/multi-component.go
tests/mvp-demo/mvp-demo.go

add an automated test of the MVP demo user journey
https://issues.redhat.com/browse/STONEBLD-77

feat: mvp-demo automation

---

.tekton/pull-request.yaml
.tekton/push.yaml

Switching to new bundle since development of old one was stopped before attempt to migrate to kcp. New bundle is removing dependency on shared secret.

ci: STONEBLD-777 - tekton-ci: update bundle

---

README.md

docs: removed Polarion chapter and Jira link, added oc version comment, fixed typo

---

README.md
tests/mvp-demo/README.md

* update readme based on the feedback from people that were recently onboarding
* add a doc for mvp-demo test
N/A
👉  👀

docs: improve readme

---

tests/e2e-demos/multi-component.go

fix: update information about multi components skip issue

---

tests/build/build.go

Added test specs to PaC build test for:
* validating usage of custom default branch in component repo
* checking that after component is deleted, related pipelinerun and github webhook is deleted as well
https://issues.redhat.com/browse/STONEBLD-727
```bash
ginkgo --label-filter="github-webhook" --v ./cmd -- --config-suites=$PWD/tests/e2e-demos/config/default.yaml
```

test: build: validate using custom default branch

---

pkg/framework/custom_junit_reporter.go

The path rp_preproc clean up is not correct. 

fix: STONE-770 rp_preproc folder cleanup fix

---

go.sum
pkg/utils/pipeline/results.go
tests/build/build.go

- [x ] I have performed a self-review of my code

feat: PLNSRVCE-1087 Test Tekton Result stored in the persistent storage

---

README.md
docs/InvestigatingCIFailures.md

Add InvestigatingCIFailures.md

docs: STONE-553 Add InvestigatingCIFailures.md

---

cmd/e2e_test.go
pkg/framework/describe.go
pkg/framework/framework.go
pkg/utils/common/controller.go
pkg/utils/o11y/controller.go
tests/o11y/o11y.go

Setting up the framework for the o11y team e2e tests. Added Pending Labels to test to not to run this test as part of CI, till the deployment-related [STONEO11Y-86](https://issues.redhat.com/browse/STONEO11Y-86) is completed.

test(STONEO11Y-44): Add initial o11y tests to e2e

---

tests/build/jvm-build.go

Fix runtime errors
1. Caused by a [failed ginkgo assertion inside `wait.PollImmediate`](https://github.com/redhat-appstudio/e2e-tests/compare/main...psturc:jvm-build-fix-panic?expand=1#diff-127f18b492d6676e9c424390e4da1361cb81a80d27d58802e2b264611d9e9835L379) - fixed by replacing it with gomega's `Eventually`
2. Caused by [trying to access fields of `componentPipelinerun` struct](https://github.com/redhat-appstudio/e2e-tests/compare/main...psturc:jvm-build-fix-panic?expand=1#diff-127f18b492d6676e9c424390e4da1361cb81a80d27d58802e2b264611d9e9835R96) that hasn't been initialized yet - this can happen in case when test fails before the initial componentPipelinerun was created. the issue was mentioned [here](https://redhat-internal.slack.com/archives/C02FANRBZQD/p1675278103105159) …

fix: runtime errors in jvm-build-service test

---

pkg/apis/github/git.go
tests/build/build.go

This PR is updating e2e tests related to the recent fix in build-service when a component is deleted related PaC unmerged PR should be closed.
https://issues.redhat.com/browse/STONEBLD-956
Tested with a local cluster with the changes. Test change is working fine.

fix: Changes related to component delete check

---

LICENSE

Add copyright owner in license file.
No ticket
Not needed

docs: Add Copyright owner in license file

---

pkg/constants/constants.go
tests/mvp-demo/mvp-demo.go
tests/release/const.go
tests/release/e2e-test-default-bundle.go

fix the tag for release-pipeline to prevent unexpected failures caused by changes in [release-bundles repo](https://github.com/hacbs-release/release-bundles)
N/A
in CI 🤷

fix: fixed tag for release pipeline

---

cmd/loadTests.go
docs/LoadTests.md
tests/load-tests/.gitignore
tests/load-tests/clear.sh
tests/load-tests/loadtest.go
tests/load-tests/run.sh

The current load test was not updated for some time and become out-of-date - it assumes some previous state of app studio that is no longer valied.
This PR:
* Updates the load test to match current state of app studio
* Adds logging to a log file
* Refactors a bit the use of channels to better synchronize phases of the load test for each simulated user
* Changes the way the `DOCKER_CONFIG_JSON` env variable is set for the script, from writting it directly into the script to exporting it instead
* Make use of env variables instead of hard-coded values

fix: out-of-date load test

---

go.sum
pkg/utils/has/controller.go
tests/has/devfile_private_source.go

fix: DEVHAS-254: Disable e2e for private repositories

---

go.mod
go.sum
magefiles/magefile.go
pkg/apis/github/client.go
pkg/utils/common/controller.go

In the future we will have a lot of tests in ci; is better to avoid from now seconday limits

feat: Avoid secondary rate limits in e2e-tests

---

tests/release/e2e-test-push-image-to-pyxis.go

See explanation in https://github.com/redhat-appstudio/e2e-tests/pull/361#issue-1592224911
N/A
CI 🤷

fix: release: move fw init to BeforeAll

---

magefiles/magefile.go

fix: Remove webhooks from redhat-appstudio/hacbs-test-project

---

tests/build/build_templates.go

As the original build tests were separated into 2 files, this PR just added `pipeline` label in build_templates tests
- [] Bug fix (non-breaking change which fixes an issue)

test: added pipeline label in build_templates tests

---

pkg/utils/o11y/controller.go
pkg/utils/tekton/controller.go
tests/o11y/const.go
tests/o11y/o11y.go

JIRA - [STONEO11Y-32](https://issues.redhat.com/browse/STONEO11Y-32)
Added Pending Labels to test to not to run this test as part of CI, till the deployment-related
STONEO11Y-86 is completed.

test(STONEO11Y-32): pipeline network egress e2e test

---

magefiles/magefile.go

This PR contains changes required for on boarding openshift-ci to the image-controller repo.
https://issues.redhat.com/browse/STONEBLD-1101

feat: Change related to openshift-ci on boarding to image-controller repo

---

magefiles/magefile.go

This PR will fix the logic in setRequiredEnvVars for image-controller jobs.

fix: Fix logic in setRequiredEnvVars for image-controller jobs

---

pkg/utils/tekton/controller.go
tests/build/build_templates.go

Add a test case that checks output of `show-sbom` task in build pipeline and ensures, that the SBOM is a valid JSON.
Issue: [STONEBLD-1042](https://issues.redhat.com/browse/STONEBLD-1042)
Implementation PR: https://github.com/redhat-appstudio/build-definitions/pull/380
https://github.com/redhat-appstudio/build-definitions/pull/383

test: Add test case for show-sbom task

---

pkg/utils/integration/controller.go
pkg/utils/release/controller.go
tests/e2e-demos/e2e-demo.go
tests/e2e-demos/multi-component.go
tests/integration-service/integration.go
tests/mvp-demo/README.md
tests/mvp-demo/mvp-demo.go
tests/release/release.go

* update mvp-demo test with more test specs for easier debugging
* extend the timeout for release pipeline to 15 minutes
* improvements of some controllers' methods
* renamed ApplicationSnapshot -> Snapshot
https://issues.redhat.com/browse/RHTAPBUGS-27
```
ginkgo --label-filter="mvp-demo" --v ./cmd -- --config-suites=$PWD/tests/e2e-demos/config/default.yaml
```

fix: improve mvp-demo test

---

pkg/utils/has/controller.go

useful component status is not getting displayed in e2e error logging, thus requiring searching in artifacts 
see https://redhat-internal.slack.com/archives/C02FANRBZQD/p1681834465373529
/assign @flacatus 
/assign @Dannyb48 
- [/] Bug fix (non-breaking change which fixes an issue)

fix: refresh component prior to error log to obtain useful status info

---

pkg/constants/constants.go
pkg/utils/release/controller.go
tests/mvp-demo/README.md
tests/mvp-demo/mvp-demo.go
tests/release/const.go

https://issues.redhat.com/browse/RHTAPBUGS-165

fix: mvp-demo: unique component name

---

pkg/utils/has/controller.go

More useful debug a la https://github.com/redhat-appstudio/e2e-tests/pull/459
With this change, I do not have to hunt through the artifacts in https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/redhat-appstudio_infra-deployments/1666/pull-ci-redhat-appstudio-infra-deployments-main-appstudio-e2e-tests/1648678676826427392 to find out that my application create failed because of git throtting:
```
"status": {
"conditions": [
{
"lastTransitionTime": "2023-04-19T14:02:54Z",
"message": "Application create failed: POST https://api.github.com/orgs/redhat-appstudio-qe/repos: 403 You have exceeded a secondary rate limit and have been temporarily blocked from content creation. Please retry your request again later. []",
"reason": "Error",
"status": "False",
"type": "Created"
}
]
}
} …
```

fix: refresh application prior to error log to obtain useful status info

---

pkg/utils/integration/controller.go

* Remove the environment configuration from ITS spec
* Full environment testing will be added in future ([STONEINTG-398](https://issues.redhat.com/browse/STONEINTG-398))
[STONEINTG-248](https://issues.redhat.com//browse/STONEINTG-248)

fix(STONEINTG-248): don't specify environment for ITS

---

cmd/loadTests.go

This PR introduces creating of user resources by using the user token by logging into the registration service
[RHTAP-667](https://issues.redhat.com//browse/RHTAP-667)  https://issues.redhat.com/browse/RHTAP-667 

feat: use user token to create resources

---

go.mod
go.sum
tests/release/e2e-test-push-image-to-pyxis.go

https://issues.redhat.com/browse/RHTAPBUGS-197

fix: RHTAPBUGS-197:skip pyxis tests due failures

---

pkg/sandbox/keycloak.go

When creating a new `Framework` the framework tries to get KeyCloak token via HTTP client. When the response is `nil` the following panic occurs when error message is generated and `response.StatusCode` is referenced:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x18ab0ef]
goroutine 1192 [running]:
github.com/redhat-appstudio/e2e-tests/pkg/sandbox.(*SandboxController).RegisterKeyclokUser(0xc002959540, {0xc0052e2d40?, 0xf?}, {0xc00a511200, 0x40e}, {0x1e7b826, 0xf})
/home/pmacik/work/devtools/github.com/redhat-appstudio/e2e-tests.git/pkg/sandbox/keycloak.go:97 +0x42f
github.com/redhat-appstudio/e2e-tests/pkg/sandbox.(*SandboxController).ReconcileUserCreation(0xc002959540, {0xc0052e2d40, 0x8}) …
```

fix(keycloak.go): panic when response is nil

---

cmd/e2e_test.go
pkg/framework/describe.go
pkg/utils/tekton/pipelines.go
tests/build/build_templates.go
tests/build/chains.go
tests/enterprise-contract/README.md
tests/enterprise-contract/contract.go

create a new enterprise-contract test suite
add case Release policy: Task bundle is not acceptable
add case Release policy: Task bundle is out of date
update mvp-demo and build suite for enterprise contract part
because verify-enterprise-contract task expose para --effective-time 
https://issues.redhat.com/browse/HACBS-1844
https://issues.redhat.com/browse/HACBS-1845
https://issues.redhat.com/browse/HACBS-2166
```
$ ./bin/e2e-appstudio --ginkgo.focus-file tests/enterprise-contract/contract.go
"level"=0 "msg"="Starting Red Hat App Studio e2e tests...\n"Running Suite: Red Hat App Studio E2E tests - /home/chuo/gitsrc/hacbs/e2e-tests
===============================================================================
Random Seed: 1682012767
Will run 2 of 313 specs …
```

feat: add test case 1885

---

go.mod
go.sum
tests/mvp-demo/mvp-demo.go
tests/release/e2e-test-default-bundle.go
tests/release/e2e-test-default-with-deployment.go
tests/release/e2e-test-push-image-to-pyxis.go
tests/release/release.go

The Release service code has been refactor and includes some breaking changes that had to be addressed within the E2E tests. This commit introduce those changes.

feat(HACBS-1777): adapt test to run for latest Release refactor

---

tests/integration-service/integration.go

Use the newest version of integration-service to resolve issues with IntegrationTestScenarios with no environments defined.

fix: set integration tests as pending temporarily

---

go.mod
go.sum
pkg/utils/integration/controller.go
pkg/utils/release/controller.go

https://issues.redhat.com/browse/HACBS-1032

chore(HACBS-1032): changes AutoReleaseLabel import package to metadata 

---

pkg/constants/constants.go
pkg/framework/framework.go
pkg/utils/common/namespace.go
pkg/utils/o11y/controller.go
tests/build/build.go
tests/o11y/const.go
tests/release/const.go
tests/release/e2e-test-default-bundle.go
tests/release/e2e-test-default-with-deployment.go
tests/release/e2e-test-push-image-to-pyxis.go
tests/release/release.go

Switching default service account to appstudio-pipeline.
Related feature: [RHTAP-872](https://issues.redhat.com//browse/RHTAP-872)

feat: STONEBLD-1241: Switch service account to appstudio-pipeline

---

tests/integration-service/integration.go

* Add digest to sample image in integration tests
[STONEINTG-414](https://issues.redhat.com//browse/STONEINTG-414)

fix(STONEINTG-414): add digest to sample image

---

tests/e2e-demos/e2e-demo.go

**Why**
to debug the issue [seen in CI lately](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/redhat-appstudio_infra-deployments/1811/pull-ci-redhat-appstudio-infra-deployments-main-appstudio-e2e-tests/1658081867284353024#1:build-log.txt%3A1275)

fix: log gitops endpoint err

---

pkg/utils/tekton/controller.go
pkg/utils/tekton/pipelines.go
tests/build/chains.go

https://issues.redhat.com/browse/RHTAPBUGS-276

fix(RHTAPBUGS-276): use default image repo instead of internal registry

---

tests/build/build.go

[Slack thread](https://redhat-internal.slack.com/archives/C02FANRBZQD/p1684399708509619)
CI :eyes:

fix: remove reference to the old SA

---

go.mod
go.sum
pkg/utils/tekton/controller.go
pkg/utils/tekton/controller_test.go
tests/build/chains.go

a follow-up on https://github.com/redhat-appstudio/e2e-tests/pull/526
https://issues.redhat.com/browse/RHTAPBUGS-276
[HACBS-2223](https://issues.redhat.com/browse/HACBS-2223)
```
ginkgo --label-filter="ec" --v ./cmd -- --config-suites=$PWD/tests/e2e-demos/config/default.yaml
```

fix: chains: check attestation and signature

---

pkg/utils/util.go
tests/byoc/byoc.go

K8s endpoint checks only DEVHAS367 is ready implemented.

fix: RHTAPBUGS-343: Check host until DEVHAS-367 is ready and implemented

---

cmd/loadTests.go
tests/load-tests/ci-scripts/collect-results.sh
tests/load-tests/clear.sh
tests/load-tests/load-tests-example.json

fix(load-test): Fix collecting results

---

tests/mvp-demo/mvp-demo.go

fix: RHTAPBUGS-356: Skip mvp release tests until RHTAPBUGS-356 is solved

---

tests/release/README.md

Will write down all use cases been covered in release suite 

feat:  Adding README.txt for release e2e-tests

---

cmd/loadTests.go
pkg/utils/has/controller.go
tests/load-tests/ci-scripts/collect-results.sh
tests/load-tests/load-tests-example.json
tests/load-tests/run.sh

[RHTAP-969](https://issues.redhat.com/browse/RHTAP-969)

feat(RHTAP-969): Make it possible to run basic or advanced pipeline builds in load test

---

tests/load-tests/ci-scripts/collect-results.sh
tests/load-tests/cluster_read_config.yaml

Collect some cluster-wide monitoring data once test is done
https://issues.redhat.com/browse/RHTAP-963
Made just limited test of bits here and there. I hope CI could show us more.

feat(RHTAP-963): Also collect some monitoring data

---

tests/load-tests/ci-scripts/max-concurrency/collect-results.sh
tests/load-tests/run-max-concurrency.sh

feat(load-test): Split output for max-concurrency load test per step and include cluster metrics

---

tests/e2e-demos/multi-component.go

fix: Skip frontend advanced checks in e2e-demos due huge memory needs

---

pkg/constants/constants.go
tests/release/e2e-test-push-image-to-pyxis.go

feat(HACBS-2055): update release pipeline tags

---

tests/build/build_templates.go
tests/release/e2e-test-default-with-deployment.go

fix: RHTAPBUGS-202: skip tekton results validation due product issue. Is blocking part of our tests to merge PRs

---

tests/mvp-demo/mvp-demo.go

This PR contains e2e-test changes to cover the advance to simple build transition flow.
https://issues.redhat.com/browse/STONEBLD-820

feat: e2e test for moving from advance to simple build 

---

tests/load-tests/ci-scripts/max-concurrency/collect-results.sh
tests/load-tests/ci-scripts/setup-cluster.sh
tests/load-tests/ci-scripts/tekton-performance/update-tekton-config-performance.yaml
tests/load-tests/cluster_read_config.yaml
tests/load-tests/run-max-concurrency.sh

[RHTAP-979](https://issues.redhat.com/browse/RHTAP-979)
In OpenShift CI:
* https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/40128/rehearse-40128-pull-ci-redhat-appstudio-e2e-tests-main-load-test-ci-tekton-tuning-base/1667154077949104128
* https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/40128/rehearse-40128-pull-ci-redhat-appstudio-e2e-tests-main-load-test-ci-tekton-tuning-tuned/1667154077995241472
* https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/40128/rehearse-40128-periodic-ci-redhat-appstudio-e2e-tests-main-load …

feat(RHTAP-979): Add possibility in load test to tweak tekton performance

---

pkg/apis/kubernetes/client.go
pkg/framework/framework.go
pkg/utils/common/proxy_plugin.go
tests/build/build_templates.go

Test the result data  which is added by console to ui. This test can be verified using registration proxy. 
https://issues.redhat.com/browse/PLNSRVCE-1311

test: PLNSRVCE-1311: Access ui tekton results data using proxyplugin

---

README.md
cmd/e2e_test.go
go.mod
go.sum
magefiles/magefile.go
pkg/framework/describe.go
pkg/utils/has/controller.go
pkg/utils/integration/controller.go
pkg/utils/jvmbuildservice/controller.go
pkg/utils/util.go
tests/build/jvm-build.go
tests/integration-service/integration.go
tests/mvp-demo/README.md
tests/mvp-demo/mvp-demo.go
tests/rhtap-demo/README.md
tests/rhtap-demo/rhtap-demo.go

* remove chapter 1 from mvp-demo since it duplicates what's being tested in e2e-demo suite
* refactor/reorganize former chapter 2
* few improvements
* mvp-demo readme doc updated
* rename mvp-demo to rhtap-demo
[RHTAP-1004](https://issues.redhat.com//browse/RHTAP-1004)
```
ginkgo --label-filter='mvp-demo' --v ./cmd/ -- --config-suites=$PWD/tests/e2e-demos/config/default.yaml
```

chore: remove chapter 1 from mvp-demo, mvp-demo -> rhtap-demo

---

tests/load-tests/ci-scripts/max-concurrency/collect-results.sh

fix(load-test): Archive output after metrics has been added not before

---

tests/load-tests/.gitignore
tests/load-tests/ci-scripts/collect-results.sh
tests/load-tests/ci-scripts/load-test.sh
tests/load-tests/ci-scripts/max-concurrency/collect-results.sh
tests/load-tests/ci-scripts/max-concurrency/load-test.sh
tests/load-tests/ci-scripts/setup-cluster.sh
tests/load-tests/run-max-concurrency.sh
tests/load-tests/run.sh

[RHTAP-1012](https://issues.redhat.com/browse/RHTAP-1012)

feat(RHTAP-1012): Enable pprof for tekton controller in load test and collect profiling data in CI

---

tests/load-tests/ci-scripts/collect-results.sh
tests/load-tests/ci-scripts/load-test.sh
tests/load-tests/run.sh

[RHTAP-1077](https:// issues.redhat.com/browse/RHTAP-1077)

feat(RHTAP-1077): Enable debugging and collecting logs for kube scheduler

---

tests/release/release.go

The ec-defaults ConfigMap in the enterprise-contract-service namespace contain values for which policy and data refs to use when creating a new EnterpriseContractPolicy resource. However, we have moved away from using this ConfigMap for this purpose. Although the values still exist, they are no longer updated by automation.
The automation now keeps a few EnterpriseContractPolicy resources up to date. This commit changes the release tests to no longer fetch the policy and data refs from the ConfigMap. Instead, it uses the `default` EnterpriseContractPolicy as the basis for creating a new resource. This `default` has the added benefit of only including certain policy rules that shouls always pass under normal operation.
NOTE: The ConfigMap is still useful for determining the most up to date …

feat: HACBS-2315: Remove outdated EC dependency

---

pkg/constants/constants.go
pkg/utils/common/route.go
pkg/utils/has/components.go
pkg/utils/integration/controller.go
tests/build/build.go
tests/build/build_templates.go
tests/build/jvm-build.go
tests/byoc/README.md
tests/byoc/byoc.go
tests/e2e-demos/config/types.go
tests/e2e-demos/e2e-demo.go
tests/e2e-demos/multi-component.go
tests/enterprise-contract/contract.go
tests/integration-service/integration.go
tests/release/const.go
tests/release/e2e-test-default-bundle.go
tests/release/e2e-test-default-with-deployment.go
tests/release/e2e-test-push-image-to-pyxis.go
tests/release/release.go
tests/rhtap-demo/rhtap-demo.go
tests/spi/access-control.go
tests/spi/get-file-content.go
tests/spi/link-secret-sa.go
tests/spi/quay-imagepullsecret-usage.go
tests/spi/token-upload-k8s.go
tests/spi/token-upload-rest-endpoint.go

Goal of this PR is to improve error logging in our tests with special focus on [`Eventually`](https://onsi.github.io/gomega/#eventually) polling wrappers that used to "swallow" the error => making the debugging harder.
Basically it's about applying of what was done in the scope of [RHTAP-915](https://issues.redhat.com//browse/RHTAP-915) for mvp-demo test (now rhtap-demo) to all tests
plus some small improvements
[RHTAP-968](https://issues.redhat.com//browse/RHTAP-968)
in CI

fix: improve (error) logging

---

cmd/e2e_test.go
magefiles/magefile.go

feat: RHTAPBUGS-257: remove verbose from resolved flakiness test

---

pkg/utils/jvmbuildservice/controller.go
tests/build/jvm-build.go
tests/rhtap-demo/rhtap-demo.go

Minor fix to delete the JBSConfig after the test run.

fix: delete JBSConfig after test

---

tests/build/build.go
tests/build/build_templates.go
tests/build/jvm-build.go
tests/byoc/byoc.go
tests/cluster-registration/clusters.go
tests/e2e-demos/e2e-demo.go
tests/e2e-demos/multi-component.go
tests/integration-service/integration.go
tests/o11y/o11y-deployments.go
tests/o11y/o11y-pipelinerun.go
tests/release/e2e-test-default-bundle.go
tests/release/e2e-test-default-with-deployment.go
tests/release/e2e-test-push-image-to-pyxis.go
tests/release/release.go
tests/rhtap-demo/rhtap-demo.go
tests/spi/access-control.go
tests/spi/quay-imagepullsecret-usage.go
tests/spi/remote-secret.go
tests/spi/token-upload-rest-endpoint.go

Improve assertions to avoid double negative assertions, wrong length and error assertions, etc... This way, the tests can be easier to read

test: improve assertions

---

pipelines/interrupt_catcher/ic-task.yaml

fix: IC rotation task failed when looping back to beginning.

---

pkg/utils/spi/controller.go

Unfortunately, [RHTAPBUGS-61](https://issues.redhat.com/browse/RHTAPBUGS-61) started to happen again. Kudos to @psturc who gave the hint regarding the fix.
[RHTAPBUGS-61](https://issues.redhat.com/browse/RHTAPBUGS-61)

fix: RHTAPBUGS-61 runtime error in GetSPIAccessTokenBinding

---

tests/spi/oauth.go

Temporary disable recent added test for further investigation. 

fix: temporary disable oauth test

---

.github/workflows/loadtest.yaml
tests/load-tests/ci-scripts/stage/collect-results.sh

feat(RHTAP-1335): Archive results for stage load test CI

---

tests/load-tests/ci-scripts/collect-results.sh
tests/load-tests/ci-scripts/max-concurrency/collect-results.sh

feat(load-test): sort output pipelineruns CSV by SucceededDuration column

---

tests/build/build_templates.go
tests/build/const.go

This PR adds a test to verify if the git repo contains symlink pointing outside of the repo
https://issues.redhat.com/browse/STONEBLD-1489

feat: Added test to check if repo contains symlink

---

go.mod
go.sum
tests/release/README.md
tests/release/const.go
tests/release/neg-missing-releaseplanadmission.go
tests/release/neg-missing-releasestrategy.go
tests/release/neg-missingreleaseplan.go
tests/release/release.go

We create 3 release manual e2e-tests that ensures behavior of release operator according to what is designed in case of missing required CRs ReleasePlan, ReleasePlanAdmission and ReleaseStrategy.
e2e-tests are added to README file with instructions  way to run.
##[HACBS-2360](https://issues.redhat.com/browse/HACBS-2360) 

feat: adding release negative 3 e2e-tests and updating them to README

---

tests/rhtap-demo/rhtap-demo.go

fix: set rhtap-demo release cr to 15 minutes timeout.

---

tests/release/e2e-test-push-image-to-pyxis.go

Due to https://issues.redhat.com/browse/RHTAPBUGS-560

chore: temporarily disable release-pyxis test

---

tests/build/build.go

fix: disable annotations tests

---

tests/release/e2e-test-push-image-to-pyxis.go

chore: bump release pipeline version in pyxis test

---

.gitignore
tests/load-tests/ci-scripts/collect-results.sh

[RHTAP-1421](https://issues.redhat.com/browse/RHTAP-1421)

feat(RHTAP-1421): Include tapa tool in collect-resources step of load test CI

---

tests/load-tests/ci-scripts/collect-results.sh

feat(load-test): Switch tapa tool to CSV output.

---

cmd/loadTests.go
docs/LoadTests.md
pkg/utils/has/components.go
tests/load-tests/load-tests-example.json
tests/load-tests/run-stage.sh
tests/load-tests/run.sh

https://issues.redhat.com/browse/RHTAP-1018
Integration service tests occur before the deployment is done
So I will add a fifth step into the load tests user journey between Build PipelineRun and Deployment
UserCreation->ResourcesCreation->Build PipelineRun->App (Integration service) tests->Deployment
It's tested just like the load-tests was implemented.
Integration service monitors the successful completion of the Build service pipelineRun and creates an application snapshot and an environment where GitOps will trigger and deploy.
However, before deployment, once the snapshot is created, the integration service …

feat(RHTAP-1018): load test measure how long the app test took

---

tests/byoc/byoc.go
tests/rhtap-demo/rhtap-demo.go

workaround for [RHTAPBUGS-595](https://issues.redhat.com//browse/RHTAPBUGS-595)
[RHTAPBUGS-595](https://issues.redhat.com//browse/RHTAPBUGS-595)
in CI 🤷

fix: deletecollection "as developer" workaround

---

.golangci.yml
tests/build/build.go

add [ginkgolinter](https://github.com/nunnatsa/ginkgolinter) to golangci lint and apply suggested fixes
[RHTAP-1435](https://issues.redhat.com//browse/RHTAP-1435)
```bash
ginkgolinter ./...
```

feat: add ginkgolinter

---

tests/release/README.md
tests/release/const.go
tests/release/e2e-test-releaseplan-owner-ref.go

test(HACBS-2469): create test for releaseplan adapter

---

tests/build/build_templates.go

If the Tekton Chains controller is busy, it may take longer than usual for it to sign and attest the image built in BeforeAll. This commit adds an explicit check to wait for them to show up before proceeding.

fix: Wait for atts/sigs in build template tests

---

tests/integration-service/integration.go

chore: add 2 additional failure tests for SEB

---

tests/build/build_templates.go

fixes an issue seen in build-definitions e2e:
```
[BeforeAll] /github.com/redhat-appstudio/e2e-tests/tests/build/build_templates.go:34
[It] /github.com/redhat-appstudio/e2e-tests/tests/build/build_templates.go:122
[FAILED] Unexpected error:
<*errors.errorString | 0xc000517ea0>:
unable to create proxy plugin due to no matches for kind "ProxyPlugin" in version "[toolchain.dev.openshift.com/v1alpha1](http://toolchain.dev.openshift.com/v1alpha1)"
{
s: "unable to create proxy plugin due to no matches for kind \"ProxyPlugin\" in version \"[toolchain.dev.openshift.com/v1alpha1](http://toolchain.dev.openshift.com/v1alpha1)\"",
}
occurred
In [BeforeAll] at: /github.com/redhat-appstudio/e2e-tests/tests/build/build_templates.go:58 @ 08/22/23 11:11:39.92
```
N/A
Please describe the tests that you ran …

fix: move proxyplugin creation and deletion

---

.github/workflows/loadtest.yaml
tests/load-tests/ci-scripts/stage/collect-results.sh

Ticket to give us Stage service account: [RHTAPWATCH-388](https://issues.redhat.com/browse/RHTAPWATCH-388)
For testing before ^^^ is resolved (if it helps), you can use personal OCP token to test it.
Goal here is to backport this to the GH action: https://github.com/redhat-appstudio/e2e-tests/blob/ec4b41064ddba845a6d1e22f0c863b406c4a8ab6/tests/load-tests/ci-scripts/collect-results.sh#L105-L129
Added support for OCP_TOKEN and STAGE_MEMBER_CLUSTER repository secrets To allow login with the OCP_TOKEN to allow elevated credentials for the stage collect-results.sh script actions
Comments:
1. OCP_TOKEN was base64 encoded before stored as a secret
2. These secrets need to be created on https://github.com/redhat-appstudio/e2e-tests/settings/secrets/actions also
I am not an owner on that repo, so …

feat(RHTAP-1336): Collect-monitoring-data-from-the-OCP-Prometheus

---

tests/spi/oauth.go

To avoid hitting pull rate limits with docker.io, we have mirrored the cypress image in quay, so we need to update it. 

fix: update cypress image

---

cmd/loadTests.go
tests/load-tests/run.sh

Enable or Disable the progress bar in the load test
The progress bar can be enabled by adding `--enable-progress-bar` in `[OPTIONS]`
[RHTAP-1340](https://issues.redhat.com/browse/RHTAP-1340)

chore: Disable / Enable progress bar in load test

---

pkg/utils/loadtests/controller.go
tests/integration-service/integration.go

[Stoneintg-468 ](https://issues.redhat.com/browse/STONEINTG-468)
- [x ] e2e test suite

chore: change new tests to push type tests

---

tests/build/const.go

Changes devfile-sample-hello-world component revision from [one causing the issue](https://github.com/redhat-appstudio-qe/devfile-sample-hello-world/commit/e17b15c4ea1fd4a2553e17ab24561bbe40d0e2f4) to the [current HEAD](https://github.com/redhat-appstudio-qe/devfile-sample-hello-world/commit/b915157dc9efac492ebc285d4a44ce67e6ab2075) of default branch
[RHTAPBUGS-496](https://issues.redhat.com/browse/RHTAPBUGS-496)
[RHTAPBUGS-732](https://issues.redhat.com/browse/RHTAPBUGS-732)

fix: wrong component revision

---

tests/load-tests/ci-scripts/collect-results.sh
tests/load-tests/ci-scripts/max-concurrency/collect-results.sh

fix(load-test): Try to collect as much results as possible without failing if files not found.

---

cmd/loadTests.go
tests/load-tests/run.sh

Updated support 6 chars random prefix to be added to user prefix
The motivation: to avoid situations where a resource with same name exists and can't be created again
"Error #6: Unable to create ComponentDetectionQuery test-rhtap-1-cdq: 
componentdetectionqueries.appstudio.redhat.com "test-rhtap-1-cdq" already exists"
Activities done:
1. Have implemented new design -
The random string will be added to user prefix only for non-OpenShift-CI jobs 
It will not be implemented also for Stage tests since it's users are already existing there
Both OpenShift-CI Presubmit  jobs and regular non-OpenShift-CI use the run.sh script
Both type of load tests are using the cmd/loadTests.go program
For both OpenShift CI jobs and non OpenShift-CI the maximum suffix length used is 11 which is leaves maximum 9 …

feat(RHTAP-1338): Add-random-prefix-to-all-resource-names

---

tests/spi/quay-imagepullsecret-usage.go

Skip spi skopeo test until fixed

fix: skip spi skopeo test until fixed

---

tests/integration-service/OWNERS

update owners list for integration-service
N/A
Owners list updates
N/A

fix: updated owners list for integration-service

---

tests/load-tests/ci-scripts/max-concurrency/collect-results.sh
tests/load-tests/cluster_read_config.yaml

Just adding few more interesting queries to track in load test
Tested the queries manually in OCP console and as part of similar config file

feat: Few more interesting queries to track

---

go.mod
go.sum
magefiles/utils_test.go

proceed with the the ticket https://issues.redhat.com/browse/RHTAPBUGS-558
to bump the version of image-controller it's also required to 
* bump jvm-build-service pkg
* add missing mock methods in unit tests
https://issues.redhat.com/browse/RHTAPBUGS-558
in CI 🤪

chore: bump jvm-build-service and image-ctrl

---

tests/integration-service/README.md

docs: add README file to integration service

---

magefiles/magefile.go

Fix wrong test suite label for spi e2e job

fix: fix spi test suite label

---

tests/load-tests/ci-scripts/max-concurrency/collect-results.sh
tests/load-tests/cluster_read_config.yaml

feat(load-test): add additional basic metrics

---

tests/build/build_templates.go

delete EC pipelinerun in build-templates test immediately if it succeeds
tested with [this PR](https://github.com/redhat-appstudio/build-definitions/pull/538)
N/A
https://github.com/redhat-appstudio/build-definitions/pull/538
or
```
ginkgo --label-filter='build-templates-e2e' --v ./cmd/
```

fix: delete EC PR if it completes successfully

---

pkg/constants/constants.go
tests/release/e2e-test-default-with-deployment.go
tests/release/e2e-test-push-image-to-pyxis.go

Update release pipeline versions to latest which include passing the enterprise contract task via git resolver instead of bundle resolver.

feat(HACBS-2550): update release pipeline versions

---

tests/build/build.go
tests/build/const.go

This PR adds a test to cover scenario of creating multi components from the same repository
https://issues.redhat.com/browse/STONEBLD-1613
Locally in a RHTAP cluster

feat: add multi-component test using same repo

---

tests/integration-service/namespace-backed-environments.go

fix: Skip namespace-backed-environments

---

tests/load-tests/run-max-concurrency.sh

feat(load-test): Add start and end timestamps to max-concurrency JSON

---

tests/rhtap-demo/rhtap-demo.go

skip multi-component language until: https://issues.redhat.com/browse/RHTAPBUGS-804 is fixed

---

tests/rhtap-demo/rhtap-demo.go

fix: Remove unused vars

---

pkg/constants/constants.go
tests/release/e2e-test-default-with-deployment.go
tests/release/e2e-test-push-image-to-pyxis.go

Bump release pipelines to tekton v1 versions

feat(HACBS-2526): update release pipelines to use tekton api v1

---

tests/build/build.go

This PR adds a scenario when two components use same git url in two different namespaces, it should result in failure
https://issues.redhat.com/browse/STONEBLD-1613

feat: multi component in different namespace with same git url

---

tests/load-tests/run-max-concurrency.sh
tests/load-tests/run-stage.sh
tests/load-tests/run.sh

feat(load-test): Propagate ENABLE_PROGRESS_BARS env variable to --enable-progress-bars flag

---

pkg/utils/has/components.go

Adding this change for getting the current state of the component when the CheckForImageAnnotation fails and also if the GetComponent call fails inside the CheckForImageAnnotations.. just log it and don't return error so that WaitUntil retries
https://issues.redhat.com/browse/RHTAPBUGS-789

fix: log the error and retry the GetComponent when it fails during CheckForImageAnnotations

---

go.mod
go.sum
pkg/utils/release/strategies.go

The API for ReleaseStrategy has changed.

feat: update strategies to use new API

---

OWNERS

chore: add siddardh-ra to root OWNERS file

---

pkg/utils/gitops/environments.go
pkg/utils/has/applications.go
pkg/utils/spi/access_checks.go
pkg/utils/spi/access_token_bindings.go

fix: RHTAPBUGS-257 Change context.TODO() to context.Background()

---

magefiles/magefile.go
tests/build/build.go
tests/rhtap-demo/config/scenarios.go

disable spray proxy registering and PaC test cases until the spray proxy host is fixed
[RHTAPBUGS-851](https://issues.redhat.com//browse/RHTAPBUGS-851)
CI 🤷

chore: temporarily disable PaC test cases

---

tests/enterprise-contract/contract.go

The newer version of EC configuration doesn't contain the `exclude` field.
Was not

fix: remove the exclude assert

---

pkg/constants/constants.go

https://github.com/redhat-appstudio/infra-deployments/commit/3dcd1853513d3da566e27fdfc2599c229d0e0363 changed the location of this file.

fix: JVM test failures

---

go.mod
go.sum
pkg/utils/gitops/deploymenttargets.go
pkg/utils/gitops/gitopsdeployments.go
pkg/utils/gitops/space.go
tests/integration-service/namespace-backed-environments.go

feat(STONEINTG-530): Making NBE more robust

---

tests/remotesecret/environments.go

Fix remote secret suite name in environment test

fix: fix remote secret suite in environment test

---

sonar-project.properties

adding sonar properties to enable better controlling over the exclusion and quality gate
https://issues.redhat.com/browse/RHTAP-1856

feat: added sonar properties 

---

pkg/utils/build/image.go
pkg/utils/build/source_image.go
pkg/utils/util.go
tests/build/build_templates.go

basic source image related tests to check if the source files are added to the source image 
https://issues.redhat.com/browse/STONEBLD-1607
creating an image quay.io/susdas/e2e:test locally with this change and pushing to quay and then updating it [here](https://github.com/redhat-appstudio/build-definitions/commit/d59c9929c8789ffd929929d2b30324f3447ec15c)

feat: add build source image tests

---

pkg/utils/common/snapshot_environment_bindings.go
pkg/utils/remotesecret/remote_secrets.go
pkg/utils/spi/file_content_requests.go
tests/remote-secret/README.md
tests/spi/README.md

The present PR updates spi and remote-secret related docs in order to reflect the current state of the tests. 
[SVPI-658](https://issues.redhat.com/browse/SVPI-658)

docs: SVPI-658 enhance and updated spi and remote-secret docs

---

tests/spi/oauth.go

fix: RHTAPBUGS-939: Skip oauth tests until RHTAPBUGS-939 is resolved

---

sonar-project.properties

just excluding the test folder in sonar

fix: Exclude test directory in sonar

---

.github/workflows/PR.yaml

fix: Increase golangci lint timeout to 10min

---

tests/build/build.go
tests/rhtap-demo/config/scenarios.go
tests/rhtap-demo/rhtap-demo.go

feat: RHTAPBUGS-804: Remove QD checks from e2e tests. We are already grooming QD in RHTAP

---

magefiles/magefile.go
tests/build/build.go
tests/rhtap-demo/config/scenarios.go

enable PaC tests after addressing issues with sprayproxy
N/A
```
ginkgo --focus "Maven project - Simple and Advanced" -v ./cmd/
```

chore: re-enable PaC tests

---

docs/OpenShiftCI.md

docs: RHTAP-1148: add link to RHTAP cluster pools documentation

---

pkg/framework/custom_junit_reporter.go

fix: RHTAP-1840 OmitTimelinesForSpecStates Passed,Skipped and

---

cmd/e2e_test.go
tests/release/service/const.go
tests/release/service/happy_path_with_deployment.go

- Created service directory and moved e2e-test-default-with-deployment to the
- folder and renamed to happy_path_with_deployment.go. 
- Copied const.go to new folder and added absent constants. 
- Renamed the namespaces to relate to the filename. 
- Removed the StrategyConfigsRepo related action.
- Used the e2e pipeline to replace deploy-release pipeline. 

fix(RHTAPREL-658): move and fix e2e-test-default-with-deployment.go

---

tests/build/build.go

https://issues.redhat.com/browse/RHTAPBUGS-961
`ginkgo --label-filter="annotations" --v ./cmd`

fix: Check pipelinerun count instead of deleting pipelineruns

---

cmd/loadTests.go

This is currently a draft PR
We are also adding tracking for integration test scenario resource creation time as done for other resources like application, cdq, component, etc
Currently the new metrics gathering per ITS are disabled until they will be added as a PR into https://github.com/redhat-appstudio-qe/perf-monitoring
https://issues.redhat.com/browse/RHTAP-1532
The test is being done currently on my Hive cluster
I intend to test it also in openshift-CI to gain more insights
New variables added to load-tests.json - 
createItsTimeAvg, createItsTimeMax, createItsSuccesses, createItsFailures, createItsFailureRate
The load test is run the same way
The integration test workflow resource is being measured as per the pattern per the other resources
The only difference is that:
- …

feat(RHTAP-1532): Track-integration-test-scenario-resource-creation-time

---

go.mod
go.sum
pkg/utils/contract/policy.go
tests/build/build_templates.go
tests/build/chains.go
tests/enterprise-contract/contract.go

This brings in the latest version of the enterprise-contract-controller. It includes various updates to the EnterpriseContractPolicy custom resource.

chore: update enterprise-contract-controller

---

tests/spi/oauth.go

This PR replaces passing k8s_token query parameter in SPI oauth login flow by the POST /login method provided by spi itself:
- [a new /login page ](https://github.com/albarbaro/spi-oauth-redirect-proxy/blob/8f46e7d4c6423c70f761eb62b61d85296a619d81/main.go#L117)is served by the [spi-oauth-redirect-proxy](https://github.com/redhat-appstudio-qe/spi-oauth-redirect-proxy ) which contains a simple html form to submit the token via POST; such page accepts the `url` query parameter, that allow us to dynamically define the action property of the html form and deal with our ephemeral e2e environments 
- upon submit, spi returns the sessions cookie needed to perform the normal oauth authentication flow
All the above steps are executed in a Cypress pod ( tests have already been updated …

feat: add spi login page support

---

OWNERS
OWNERS_ALIASES
tests/build/OWNERS
tests/enterprise-contract/OWNERS
tests/integration-service/OWNERS
tests/release/OWNERS

- update owners files
- add owners aliases
N/A
N/A

chore: update owners files, add owners_aliases

---

tests/release/pipelines/fbc_release.go

- Update ReleasePlanPermission part after ReleaseStrategy is removed
- Move e2e-fbc.go to fbc_release.go

feat(RHTAPREL-659): produce a test for the fbc-release pipeline

---

pkg/framework/describe.go
tests/byoc/byoc.go
tests/rhtap-demo/config/scenarios.go

chore: Change byoc suite name to byoc-suite and remove duplicated suite

---

docs/Installation.md

The existence of a branch with the right name in your fork is not enough, there needs to be a PR open in redhat-appstudio/e2e-tests from that branch.
n/a

docs: clarify the branch pairing mechanism

---

tests/build/build.go
tests/byoc/byoc.go
tests/integration-service/integration.go
tests/rhtap-demo/rhtap-demo.go

Skipping component deletion where it is failing. Examples:
- [rhtap-demo.go:121](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/redhat-appstudio_e2e-tests/879/pull-ci-redhat-appstudio-e2e-tests-main-redhat-appstudio-e2e/1724041603149991936#1:build-log.txt%3A1186)
- [build.go:240](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/redhat-appstudio_e2e-tests/883/pull-ci-redhat-appstudio-e2e-tests-main-redhat-appstudio-e2e/1724074524539883520#1:build-log.txt%3A1111)
- [build.go:1081](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/redhat-appstudio_e2e-tests/883/pull-ci-redhat-appstudio-e2e-tests-main-redhat-appstudio-e2e/1724074524539883520#1:build-log.txt%3A1099)
- [integration.go:303](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr …

test: RHTAPBUGS-978 skipping component deletion

---

tests/integration-service/integration.go

The integration service adds finalizers to build pipelineruns to ensure that they can be processed by the integration service before being cleaned up. This commit adds checks that verify that the finalizers were added and removed properly
Deploy RHTAP on a Quickcluster instance using `make local/cluster/prepare` then run `./bin/e2e-appstudio --ginkgo.focus="with happy path for general flow of Integration service" –ginkgo.vvv`

feat(STONEINTG-600): Add tests for build plr finalizers

---

magefiles/magefile.go

Our goal is to test release-service-catalog changes with the release-pipelines suite. We do not need to deploy a special version of the release-service for this task, for now.

feat(RHTAPREL-732): update magefile for release-service-catalog repo

---

pkg/utils/tekton/bundle.go
pkg/utils/tekton/pipeline_extraction_test.go

During refactoring the wrong 'yaml' was imported.
https://issues.redhat.com/browse/STONEBUGS-123

fix(STONEBUGS-123): fix JVM Build Service tests

---

magefiles/magefile.go

follow-up on https://github.com/redhat-appstudio/e2e-tests/pull/897#discussion_r1401683543
N/A
CI

fix: env vars setup for release-service-catalog

---

magefiles/magefile.go
tests/build/build_templates.go

Related flakiness:
https://issues.redhat.com/browse/RHTAPBUGS-992, https://issues.redhat.com/browse/RHTAPBUGS-991, https://issues.redhat.com/browse/RHTAPBUGS-989, https://issues.redhat.com/browse/RHTAPBUGS-978,https://issues.redhat.com/browse/RHTAPBUGS-956

fix: Disable build tests in infra-deployments until flakiness are fixed

---

pkg/clients/has/components.go

feat: RHTAPBUGS-985: retry pipelineruns when hit TaskRunImagePullFailed reason in Pipelinerun statuses

---

pkg/framework/custom_junit_reporter.go

modify disabled and status fields while generating xunit 
The latest JUnit file generated from this test can be used to verify its matching the below sample structure.

feat: modify disabled and status fields

---

tests/integration-service/status-reporting-to-pullrequest.go

See [this comment](https://issues.redhat.com/browse/RHTAPBUGS-993?focusedId=23530437&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-23530437) for more info
[RHTAPBUGS-993](https://issues.redhat.com//browse/RHTAPBUGS-993)
```
ginkgo -v --label-filter='status-reporting' ./cmd/
```

fix: checkRun variable not being updated

---

magefiles/magefile.go

The JVM build service tests are failing again due to the API change.
https://issues.redhat.com/browse/RHTAPBUGS-1012

fix(RHTAPBUGS-1012): update to v1 API

---

.github/workflows/PR.yaml
Dockerfile
Makefile
docs/Installation.md
tests/load-tests/ci-scripts/setup-cluster.sh

* move away from using `vendor` folder
1. clone this PR
2. delete `vendor` folder
3. run `make build`
https://issues.redhat.com/browse/RHTAP-1804
in CI 🤷

chore: do not rely on 'vendor' folder

---

Makefile
magefiles/magefile.go
pkg/clients/sprayproxy/sprayproxy.go
pkg/clients/sprayproxy/types.go

This PR is to cleanup  the registered (and no longer valid)  pac servers on qe sprayproxy. We will add it in CI to do a periodic cleanup.
[PLNSRVCE-1512](https://issues.redhat.com/browse/PLNSRVCE-1512)

feat: periodic cleanup of registered (and no longer valid) servers on qe sprayproxy

---

pkg/clients/has/components.go

fix: RHTAPBUGS-985: retry pipelineruns always when error occurs

---

tests/release/pipelines/push_to_external_registry.go

Release pipeline failed at step verify_enterprise_contract step in
push_to_external_registry pipeline, this PR is to fix the values in
data struct to make it pass.

fix: update the values in data struct to pass the ec verification

---

tests/build/build.go

Adding 1 sec wait before sending second build request, which will avoid the issue occurred [here](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/redhat-appstudio_e2e-tests/916/pull-ci-redhat-appstudio-e2e-tests-main-redhat-appstudio-e2e/1729784061569798144) and also handles the invalid annotations build status message check properly since it can fail intermittently similar to [here](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/redhat-appstudio_e2e-tests/919/pull-ci-redhat-appstudio-e2e-tests-main-redhat-appstudio-e2e/1729927342807060480)

fix: Add 1 sec wait before sending second build request and handle inivalid status message check

---

tests/release/service/happy_path_with_deployment.go

fix: update the EC policy in happy_path_with_deployment

---

tests/build/build.go
tests/build/jvm-build.go
tests/byoc/byoc.go
tests/integration-service/integration.go
tests/integration-service/status-reporting-to-pullrequest.go
tests/rhtap-demo/rhtap-demo.go

This PR increases randomly generated string in temp branch names as well as in components. This should minimize risk of  https://issues.redhat.com/browse/RHTAPBUGS-1013
https://issues.redhat.com/browse/RHTAPBUGS-1013

fix: RHTAPBUGS-1013: increase random string in branch names.

---

tests/build/build.go
tests/integration-service/status-reporting-to-pullrequest.go
tests/rhtap-demo/config/scenarios.go

Skipping pac-related tests until [RHTAPBUGS-1049](https://issues.redhat.com//browse/RHTAPBUGS-1049) is fixed.
[RHTAPBUGS-1049](https://issues.redhat.com//browse/RHTAPBUGS-1049)
CI :crossed_fingers:

fix: Skipping pac-related tests until RHTAPBUGS-1049 is fixed

---

tests/build/build.go
tests/integration-service/status-reporting-to-pullrequest.go
tests/rhtap-demo/config/scenarios.go

reverts https://github.com/redhat-appstudio/e2e-tests/pull/941

fix: Revert skipping the pac-tests

---

tests/build/build.go
tests/build/build_templates.go
tests/build/const.go

log step-summary output to see, what is the content for which the validation fails and also added logs before other Json.Unmarshals in our build tests
https://issues.redhat.com/browse/RHTAPBUGS-956

chore: Added debug log for RHTAPBUGS-956 and also before other json.Unmarshals in build-tests

---

magefiles/magefile.go

For debug purpose, it print out more logs related to sprayproxy 
- [x ] I have performed a self-review of my code

chore: print out more logs for sprayproxy

---

magefiles/magefile.go

Run same tests like in infra-deployments in periodic jobs 

fix: RHTAPBUGS-991: Do not run flaky tests in periodic jobs

---

magefiles/magefile.go

fix of configuration of multiplatform tests
[RHTAPBUGS-1063](https://issues.redhat.com//browse/RHTAPBUGS-1063)
CI

fix: configuration of MP tests in CI

---

pkg/clients/has/components.go

Print the error log when we pipelinerun deletion fails

chore: Added debug log for rhtapbugs-1039

---

magefiles/magefile.go
pkg/clients/sprayproxy/sprayproxy.go

This is to fix a few of minor issues related to  sprayproxy   

fix: issues of registering pac server in sprayproxy

---

pkg/sandbox/sandbox.go

fix: Remove sandbox logging

---

tests/release/const.go
tests/release/pipelines/fbc_release.go
tests/release/releaseLib.go

1. Added FBC hot fix test case
2. Created common function lib for release suite 

feat(RHTAPREL-740): add fbc hotfix test case

---

magefiles/magefile.go

* fix of the condition for rehearsal job for release-service-catalog
in CI

fix: release-service-catalog CI config

---

magefiles/magefile.go

This is to fix the issue of cleanup invalid pac servers.  
- [x ] I have performed a self-review of my code

fix: fix the issue of cleanup invalid pac servers

---

tests/release/pipelines/OWNERS

Add OWNERs for release-pipelines-suite. This suite will only be ran in the CI of 
release-service-catalog repo.

chore: add OWNERS for release-pipelines-suite

---

tests/integration-service/status-reporting-to-pullrequest.go

In cases when build PLR failed and was retriggered by the test, the check for validating the PR checkrun status was not working correctly, because it was using the old PR head SHA for validation. This PR should fix it
https://issues.redhat.com/browse/RHTAPBUGS-993
1. Trigger the test
```
ginkgo -v --label-filter='status-reporting' ./cmd/
```
2. Once the PLR is created, cancel it (easy to do via openhshift console) to simulate pipelinerun failure, so it gets retriggered
3. The test should succeed

fix: refer to correct PLR sha in case of PLR retry

---

tests/release/pipelines/push_to_external_registry.go

Temprarily remove "@slsa3" from EC policy for release-service-catalog CI

fix: update the EC policy for push_to_external_registry

---

tests/release/pipelines/fbc_release.go
tests/release/pipelines/push_to_external_registry.go

Turn release-pipelines suite tests to pending for now. They will be reenabled as they are fixed.

chore(RHTAPREL-732): turn off release-pipelines tests

---

go.mod
go.sum
pkg/sandbox/sandbox.go

TSIA
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/redhat-appstudio_infra-deployments/2957/pull-ci-redhat-appstudio-infra-deployments-main-appstudio-e2e-tests/1737101734284627968/artifacts/appstudio-e2e-tests/redhat-appstudio-gather/artifacts/usersignups.json

fix: Add email to the sandobx usersignups

---

tests/release/pipelines/fbc_release.go

fix: add credentials settings for FBC tests

---

tests/build/build.go

Updating component sometimes fails with error `Operation cannot be fulfilled on components.appstudio.redhat.com "test-component-pac-qusm": the object has been modified`
https://issues.redhat.com/browse/RHTAPBUGS-992

fix: Use eventually when updating component 

---

tests/integration-service/namespace-backed-environments.go

Don't retry for the unrecoverable error, see [discussion](https://github.com/redhat-appstudio/e2e-tests/pull/980#discussion_r1436318610)

fix(RHTAPBUGS-980): don't retry for the unrecoverable error

---

cmd/loadTests.go

refactor userJourneyThread method
Refactor userJourneyThread method in cmd/loadTests.go to align to Refactor this method to reduce its Cognitive Complexity from 310 to the 15 allowed (SonarCloud)
https://issues.redhat.com/browse/RHTAP-1897
Testing on my Hive cluster
Intend to test openshift-ci load test

fix(RHTAP-1897): Refactor-userJourneyThread-method

---

tests/release/const.go
tests/release/pipelines/rh_push_to_external_registry.go

Change the default revision to staging and fix the revision in
rh_push_to_external_registry

chore: change default revision to staging

---

magefiles/magefile.go

this PR should enable targeting correct infra-deployments branch when running HAC E2E from infra-deployments PRs
N/A
in CI 🤷

fix: set required env vars for HAC E2E

---

go.mod
go.sum
tests/build/build.go
tests/build/const.go

Initial tests for the component nudge update.
https://issues.redhat.com/browse/STONEBLD-1844

test(STONEBLD-1844): add test for component nudge

---

magefiles/installation/install.go
magefiles/magefile.go
magefiles/utils.go

fix: RHTAPBUGS-1090 Fix already-up-to-date issue in upgrade tests

---

docs/Installation.md

to address feedback from cspi-qe team
N/A
N/A

docs: address feedback

---

pkg/clients/tekton/pipelineruns.go
tests/build/build_templates.go

This is part of the story: https://issues.redhat.com/browse/STONEBLD-2111

fix: Use finalizers in build PLR to avoid getting pruned

---

magefiles/magefile.go

Recent change in build test suites started created private repositories with prefixes "multi-platform" and "jvm-build", we need to cleanup them regularly.

chore: Add new prefixes for private repo cleanup

---

tests/build/build.go

This PR will catch the failure earlier when we reach the quay org private repo limit (=50), the error will be printed correctly.
https://issues.redhat.com/browse/RHTAPBUGS-1126

fix: image repo status check

---

pkg/utils/build/quay.go
tests/build/build_templates.go

The new tag is based on cosign convention in the form `registry/ns/repo:sha256-hash.src`.
Requires https://github.com/redhat-appstudio/build-tasks-dockerfiles/pull/27
[STONEBLD-1945](https://issues.redhat.com//browse/STONEBLD-1945)

feat(STONEBLD-1945): check new source container image tag

---

tests/release/service/release_plan_and_admission_matched.go

It's to add checking for the fix of [RHTAPBUGS-1113](https://issues.redhat.com//browse/RHTAPBUGS-1113)

fix: the matchedCondition of RP need to be set when no RPA exist

---

tests/release/pipelines/fbc_release.go

feat(RHTAPREL-749): add e2e-tests for publishing FBC pre-GA

---

tests/build/build.go

Github org and quay org name could differ when running locally

chore: Fix the quay org name

---

tests/build/build_templates.go

When a pipeline is failed, `e2e-test` finalizer was not removed with the current logic since the pipeline was retried and when querying prs in GetComponentPipelineRun it was returning the latest retried pipelinerun without the `e2e-test` finalizer
https://issues.redhat.com/browse/KFLUXBUGS-558
locally with `ginkgo --label-filter="build-templates-e2e" --v ./cmd`

fix: the logic of e2e-test finalizer removing

---

tests/spi/oauth.go

skip the oauth test until it's fixed
https://issues.redhat.com/browse/KFLUXBUGS-1108
N/A

chore: spi: skip github oauth test

---

tests/release/pipelines/fbc_release.go

feat: delete crs always in fbc release tests

---

go.mod
go.sum

chore(deps): Update github.com/containerd/containerd from v1.7.11 to v1.7.13

---

tests/rhtap-demo/rhtap-demo.go

With changes introduced with [PR](https://github.com/redhat-appstudio/build-service/pull/248) , build-service will do the cleanup of pacBranch, e2e-tests should handle that scenario 

fix: handle pac branch does not exists scenario

---

tests/enterprise-contract/contract.go

The violation message changed and this updates the test. Second commit formats the code using `go fmt`.
Was not

fix: ec violation message

---

magefiles/magefile.go

chore: update relSvcCatalog revision

---

tests/release/pipelines/fbc_release.go

This supports [EC-272](https://issues.redhat.com//browse/EC-272) and https://github.com/redhat-appstudio/release-service-catalog/pull/372
* https://issues.redhat.com/browse/EC-272
Looking for CI feedback.

feat: add allowedPackages for the fbc test

---

tests/release/pipelines/fbc_release.go

chore: print fbc application name

---

pkg/clients/common/pod.go
tests/build/multi-platform.go

PR adds a e2e-test for aws dynamic instance allocation.
https://issues.redhat.com/browse/STONEBLD-1857
locally with `ginkgo --label-filter="multi-platform" --v ./cmd`

feat: Add aws dynamic instance allocation tests

---

.github/workflows/estimate-review.yaml

Add the [Estimate time to review a PR](https://github.com/redhat-appstudio/qe-tools/blob/main/docs/estimate-review.md) workflow. 
[KONFLUX-2261](https://issues.redhat.com/browse/KONFLUX-2261)
Tested in my fork. https://github.com/tnevrlka/e2e-tests/actions/runs/8328781539/job/22789585555
Due to `on: pull_request_target`, the action will not run on this PR.

ci: add estimate PR review time workflow

---

magefiles/upgrade/upgrade.go

the ocp upgrade script previously supported only conditional updates and was ignoring standard (available updates)
https://issues.redhat.com/browse/KFLUXBUGS-1155
```
❯ make ci/test/openshift-upgrade
./mage -v ci:performOpenShiftUpgrade
Running target: CI:PerformOpenShiftUpgrade
I0320 07:06:48.959972   16597 upgrade.go:77] current channel is "candidate-4.13", current ocp version is "4.13.37"
I0320 07:06:49.084526   16597 upgrade.go:112] desired major.minor version is "4.14", desired channel is "candidate-4.14"
I0320 07:06:49.456283   16597 upgrade.go:186] admin ack {"data":{"ack-4.13-kube-1.27-api-removals-in-4.14":"true"}} successfully applied
I0320 07:06:49.577681   16597 upgrade.go:197] found the desired version "4.14.17" in available updates
Requesting update to 4.14.17
I0320 …
```

fix: ocp upgrade: available/conditional updates

---

OWNERS_ALIASES

Adding myself to the rhtap-qe alias.
N/A

chore: add myself to rhtap-qe alias.

---

tests/load-tests/cluster_read_config.yaml

Adding additional metadata to our JSON result file - adding info about e2e-tests and infra-deployments repo.
https://issues.redhat.com/browse/KONFLUX-926
New feature (non-breaking change which adds functionality)
Will run CI in this PR

feat(KONFLUX-926): Track git commit status

---

pkg/clients/github/repositories.go
tests/release/const.go
tests/release/pipelines/fbc_release.go
tests/release/pipelines/release_to_github.go
tests/release/releaseLib.go

feat(RHTAPREL-849): add e2e test for release_to_github

---

tests/build/multi-platform.go

https://issues.redhat.com/browse/KFLUXBUGS-1179
https://issues.redhat.com/browse/KFLUXBUGS-1179
N/A

chore: skip flakey IBM PPC test

---

tests/build/multi-platform.go

ibmz tests also failing with the same error reported in [KFLUXBUGS-1179](https://issues.redhat.com//browse/KFLUXBUGS-1179), so skipping it as well.

chore: KFLUXBUGS-1179 skip ibmz tests

---

tests/build/build_templates.go

temporarily disabling the test due to https://issues.redhat.com/browse/SRVKP-4348
https://issues.redhat.com/browse/SRVKP-4348
N/A

chore: disable tekton-results pipeline logs check

---

tests/load-tests/ci-scripts/stage/cluster_read_config.yaml

Add metric to track average task pod duration by Tekton measurements
https://issues.redhat.com/browse/RHTAP-1742
This is a config file change that should not affect stability. Will run CI job.

feat(RHTAP-1742): Add metric to track average task pod duration by Tekton measurements

---

tests/load-tests/cluster_read_config.yaml

Add OCP cluster version to the JSON file
N/A
New feature (non-breaking change which adds functionality)
Will run CI job

feat: Add OCP cluster version

---

pkg/utils/tekton/pipelineruns.go
tests/build/multi-platform.go

address recently discovered test issues
* missing app repo: https://github.com/redhat-appstudio/e2e-tests/commit/8dc4743cf47ff108ae56606951b7d694f17b7a57
* failing MP tests: https://github.com/redhat-appstudio/e2e-tests/commit/a50d32d6846dbf299ff87ca56656158346403711
[KFLUXBUGS-1179](https://issues.redhat.com//browse/KFLUXBUGS-1179)
```
ginkgo -v --label-filter='ec' ./cmd/
```

fix: address issues with tests

---

tests/release/pipelines/fbc_release.go

Since the FBC release pipelineRun need about 15 minutes to complete and the bear token expires around every 3 minutes, this PR is adding framework renew action during the period of waiting for the release pipelineRun to complete.

fix: renew framework every 3 minutes

---

tests/build/const.go

Follow-up on the update done in https://github.com/redhat-appstudio-qe/sample-multi-component/commit/0d1835404efb8ab7bb1ab5b5b82cda1ebfda4b25 
More details in [KFLUXBUGS-1219](https://issues.redhat.com//browse/KFLUXBUGS-1219) and related slack discussions
[KFLUXBUGS-1219](https://issues.redhat.com//browse/KFLUXBUGS-1219)
```
ginkgo -p -v --label-filter='build' ./cmd/
```

fix: follow-up on the devfile schema version incompatibility issue

---

cmd/loadTests.go

Make it possible to create a component with 'build.appstudio.openshift.io/request: configure-pac'
https://issues.redhat.com/browse/KONFLUX-2602
New feature (non-breaking change which adds functionality)
Local run against Stage

feat(KONFLUX-2602): Make it possible to create a component with 'build.appstudio.openshift.io/request: configure-pac'

---

cmd/loadTests.go
tests/integration-service/const.go
tests/load-tests/run-stage.sh
tests/load-tests/run.sh
tests/rhtap-demo/config/scenarios.go

* Update integration-examples link to org konflux-ci

feat(STONEINTG-837): update org of integration-examples

---

tests/release/pipelines/fbc_release.go

fix(RHTAPREL-842): preGA and hotfix can't be set both

---

tests/build/build.go
tests/build/const.go

adds tests for secret lookup feature in build-service
https://issues.redhat.com/browse/STONEBLD-2195

feat: add tests related to secret lookup

---

cmd/loadTests.go
pkg/clients/has/components.go
pkg/clients/integration/integration_test_scenarios.go

Make it possible to create more components in one app
https://issues.redhat.com/browse/KONFLUX-2084
- New feature (non-breaking change which adds functionality)
Locally against Stage, but plan to use CI as well.

feat(KONFLUX-2084): Make it possible to create more components in one app

---

OWNERS_ALIASES
cmd/OWNERS
tests/load-tests/OWNERS

- add owners for load/perf tests related code

chore: add perf-test OWNERS files

---

pkg/clients/release/sbom.go
tests/release/pipelines/rh_push_to_external_registry.go

The changes for [KFLUXBUGS-1115](https://issues.redhat.com//browse/KFLUXBUGS-1115) remove a task result that the rh_push_to_external_registry release pipeline test relied on. This commit updates that task to use task logs instead of task results to check that the pipeline executed properly.

refactor(KFLUXBUGS-1115): rh_push_to_external_registry refactor

---

pkg/clients/release/OWNERS

chore: add approvers for release dir in pkg

---

pkg/clients/common/pod.go
tests/build/tkn-bundle.go

* document running tests locally on kind
* fix bug where bundle name was invalid
* wait for setup pod so test data exists
* overwrite test data on each run
https://issues.redhat.com/browse/EC-624

fix(EC-624): tkn-bundle bug fixes

---

tests/build/tkn-bundle.go

Skipping the test to unblock build-definitions CI
https://issues.redhat.com/browse/EC-629

fix: skip tkn-bundle task test temporarily

---

Dockerfile
docs/Installation.md
go.mod
go.sum

* prereq for https://github.com/redhat-appstudio/e2e-tests/pull/1144

chore: prepare for go v1.21

---

tests/build/build_templates.go

[STONEBLD-2122](https://issues.redhat.com//browse/STONEBLD-2122)

feat: stop checking deprecated source image tag

---

tests/release/pipelines/fbc_release.go
tests/release/pipelines/release_to_github.go
tests/release/pipelines/rh_advisories.go
tests/release/pipelines/rh_push_to_redhat_io.go

fix: add renew framework for build pipelineRun

---

tests/enterprise-contract/contract.go

add test case to cover  redhat EC policy to make sure any change in redhat policy collection is tested.
https://issues.redhat.com/browse/EC-589

feat: add test coverage for redhat policy check

---

pkg/clients/release/releases.go
tests/release/pipelines/fbc_release.go
tests/release/pipelines/push_to_external_registry.go
tests/release/pipelines/release_to_github.go
tests/release/pipelines/rh_advisories.go
tests/release/pipelines/rh_push_to_external_registry.go
tests/release/pipelines/rh_push_to_redhat_io.go
tests/release/service/happy_path.go

Add WaitForReleasePipelineToBeFinished function and expose the failed PipelineRun errors in it. Update the test cases to use this function.
Update the delete/create secret to avoid potential flakiness.

feat(RELEASE-906): add WaitForReleasePipelineToBeFinished function

---

pkg/clients/common/namespace.go
pkg/clients/common/rbac.go

[link to a slack thread](https://redhat-internal.slack.com/archives/C02FANRBZQD/p1716378316878169?thread_ts=1716272083.258219&cid=C02FANRBZQD)
https://issues.redhat.com/browse/KONFLUX-3170
in CI 🤷

fix: remove waiting the Argo CD role/rb to be set

---

tests/integration-service/integration.go

* update integration GCL test for GCL logic change in https://github.com/konflux-ci/integration-service/pull/733 since we don't need to wait until the snapshot pass integration test
* should be merged after https://github.com/konflux-ci/integration-service/pull/733 is merged

feat(STONEINTG-881): update intg GCL test for GCL logic change

---

tests/integration-service/integration.go

feat(STONEINTG-881): enable GCL test

---

tests/release/pipelines/fbc_release.go
tests/release/pipelines/release_to_github.go
tests/release/pipelines/rh_advisories.go
tests/release/pipelines/rh_push_to_external_registry.go
tests/release/pipelines/rh_push_to_redhat_io.go

Implement loop in the test script itself to avoid the invalid memeoy or nil pointer issue

fix: invalid memory or nil pointer issue

---

tests/enterprise-contract/contract.go

Instead of looking at "SUCCESS" as the result we can look at the result not being a "FAILURE", this way we can tolerate warnings as well.
Resolves: https://issues.redhat.com/browse/KFLUXBUGS-1314

fix: expect EC check not to fail

---

tests/rhtap-demo/rhtap-demo.go

After [this PR](https://github.com/konflux-ci/build-service/pull/309/files) got merged, pacPurgeBranchName is prefixed with `konflux-` 
Kept check for both now so that we can unblock merging of [infra-deployment PR](https://github.com/redhat-appstudio/infra-deployments/pull/3841), once that is merged we can move to check only `konflux-` prefix

fix: check for either appstudio- or konflux- prefix for the pacPurgeBranchName

---

tests/release/pipelines/fbc_release.go
tests/release/pipelines/push_to_external_registry.go
tests/release/pipelines/release_to_github.go
tests/release/pipelines/rh_advisories.go
tests/release/pipelines/rh_push_to_external_registry.go
tests/release/pipelines/rh_push_to_redhat_io.go
tests/release/service/happy_path.go

fix: fix ec policy rules

---

tests/release/pipelines/rh_push_to_redhat_io.go

fix: some error in  rh_push_to_redhat_io 

---

tests/release/pipelines/rh_push_to_external_registry.go

fix: undefined compName in release test

---

tests/release/pipelines/push_to_external_registry.go

The variable "devFw" is used without being defined and breaks the test for "invalid memory/nil pointer" issue

fix:   var fw was replaced by devFw wrongly

---

tests/enterprise-contract/contract.go

this test is failing on every PR atm
N/A
N/A

chore: disable release-policy test

---

tests/enterprise-contract/contract.go

ec-golden-image:latest (As of 06/25/2024, the image just updated latest version) using ec validate command and it passed. So ec can be enabled.
https://issues.redhat.com/browse/KFLUXBUGS-1360

fix: enable ec

---

tests/release/pipelines/push_to_external_registry.go
tests/release/pipelines/rh_push_to_external_registry.go

feat(RELEASE-932): add tags to rh_push_to_external_registry test

---

.tekton/update-build-tasks-dockerfiles.yaml

[STONEBLD-2558](https://issues.redhat.com//browse/STONEBLD-2558)
Integration tests has been set up in build-tasks-dockerfiles. This PR updates the e2e-tests image for it.

feat: update e2e-tests image in build-tasks-dockerfies repo

---

go.mod
go.sum
pkg/clients/release/plans.go
tests/integration-service/integration.go
tests/release/pipelines/fbc_release.go
tests/release/pipelines/push_to_external_registry.go
tests/release/pipelines/release_to_github.go
tests/release/pipelines/rh_advisories.go
tests/release/pipelines/rh_push_to_external_registry.go
tests/release/pipelines/rh_push_to_redhat_io.go
tests/release/pipelines/tenant_pipelines.go
tests/release/service/happy_path.go
tests/release/service/release_plan_and_admission_matched.go
tests/release/service/release_plan_owner_ref.go
tests/rhtap-demo/rhtap-demo.go

feat(RELEASE-190): add e2e tests for tenant pipeline

---

.tekton/konflux-e2e-tests-push.yaml

fix: Fix deprecated task bundles

---

.tekton/konflux-e2e-tests-push.yaml

fix: Fix tasks-dockerfiles update script

---

tests/integration-service/README.md

Adding the Gitlab and Environment tests added to integration suite into README file 

feat(STONEINTG-979): add gitlab and environment tests in README

---

tests/release/pipelines/rhtap_service_push.go

feat(RELEASE-106): add e2e tests for rhtap-service-push pipeline

---

tests/enterprise-contract/README.md

ec [README](https://github.com/konflux-ci/e2e-tests/blob/main/tests/enterprise-contract/README.md) links attached is not valid anymore and leads to 404, update
[Release Policy](https://redhat-appstudio.github.io/docs.stonesoup.io/ec-policies/release_policy.html) and [Pipeline Policy](https://redhat-appstudio.github.io/docs.stonesoup.io/ec-policies/pipeline_policy.html) to the new url

chore: update ec readme

---

tests/load-tests/ci-scripts/stage/collect-results.sh

Do not fail whole collection step if this fails

fix: Do not fail collection if this fails

---

tests/load-tests/ci-scripts/utility_scripts/runs-to-csv.sh

In my local runs, I use this field to distinguish runs.

feat: For local runs, I use this field to distinguish runs

---

tests/load-tests/ci-scripts/utility_scripts/playwright-update-tokens.py

Adding Playwright script to regenerate offline tokens

feat: Playwright script to regenerate offline tokens

---

go.mod
go.sum
pkg/clients/integration/integration_test_scenarios.go
pkg/clients/integration/pipelineruns.go
pkg/clients/kubernetes/client.go
tests/integration-service/gitlab-integration-reporting.go
tests/integration-service/integration-with-env.go
tests/integration-service/integration.go
tests/integration-service/status-reporting-to-pullrequest.go
tests/load-tests/pkg/journey/handle_integration_test_scenarios.go
tests/rhtap-demo/rhtap-demo.go

chore(stoneintg-930): update ITS v1beta2 in e2e

---

magefiles/magefile.go
magefiles/rulesengine/repos/e2e_repo.go
magefiles/rulesengine/types.go

chore: add rules for release service catalog testing

---

magefiles/magefile.go
magefiles/rulesengine/engine/engine.go
magefiles/rulesengine/repos/e2e_repo.go
magefiles/rulesengine/repos/release_service_catalog.go

chore:  update rules for release service catalog testing

---

magefiles/magefile.go

fix: remove DeepEqual check

---

tests/load-tests/ci-scripts/collect-results.sh
tests/load-tests/ci-scripts/stage/collect-results.sh

Put all addition data collected in results collection phase to go to additional directory to make main artefact directory bit cleaner.

feat: Put additional collected data to dedicated directory

---

Dockerfile

In order to push artifacts to quay we need oras.

fix: Add oras to konflux container to push artifacts

---

tests/release/pipelines/fbc_release.go

fix: increase ticker time for fbc pipeline

---

tests/build/build_templates.go

print pipelinerun and taskrun details for the The "[runs ec pipeline](https://github.com/redhat-appstudio/e2e-tests/blob/c4f5822caebb5b5119eedc4e1ab836eb7e6237f1/tests/build/build_templates.go#L556)" tests verify the EC Pipelines
https://issues.redhat.com/browse/EC-537

fix: Print PipelineRun status

---

tests/release/pipelines/rhtap_service_push.go
tests/release/releaseLib.go

It's to skip initial check in build pipelineRun to reduce the runtime of it

chore: skip init check in build pipelineRun

---

.tekton/konflux-e2e-tests-push.yaml

fix: Add removed params during migration to a new konflux workspace

---

integration-tests/tasks/konflux-e2e-tests-task.yaml

Add correctly the oras credentials to login

fix: Fix oras username and oras password

---

.tekton/konflux-e2e-tests-push.yaml
default.env
integration-tests/pipelines/konflux-e2e-tests-pipeline.yaml
integration-tests/tasks/konflux-e2e-tests-task.yaml
magefiles/magefile.go

* Increase limits of the e2e tasks
* add ginkgo procs environment to customize processes

fix: Increase limits again

---

tests/build/jvm-build.go
tests/konflux-demo/konflux-demo.go

Skipping the `jvm-build-service` related tests, since `jvm-build-service` will be reworked
https://issues.redhat.com/browse/KFLUXBUGS-1510

chore: skip jvm-build-service related tests

---

.github/workflows/PR.yaml

chore: bump golangci-lint version

---

integration-tests/pipelines/konflux-e2e-tests-pipeline.yaml
integration-tests/tasks/konflux-e2e-tests-task.yaml

Usse devshift vault external secrets name

chore: Use external secret from vault in e2e tests

---

integration-tests/pipelines/konflux-e2e-tests-pipeline.yaml
integration-tests/tasks/konflux-e2e-tests-task.yaml
magefiles/magefile.go
magefiles/rulesengine/repos/e2e_repo.go

chore: workaround to pull otel images using docker io creds

---

magefiles/rulesengine/repos/e2e_repo.go

Check tekton files in e2e repo rules.

fix: Fix e2e repo rule engine

---

integration-tests/pipelines/konflux-e2e-tests-pipeline.yaml
integration-tests/tasks/konflux-e2e-tests-task.yaml

chore: Modify e2e pipeline and task to allow to execute e2e tasks in Konflux components

---

tests/release/service/happy_path.go

[KFLUXBUGS-1530](https://issues.redhat.com//browse/KFLUXBUGS-1530)

chore: pending release happy-path temporarily

---

.tekton/konflux-e2e-tests-pull-request.yaml
.tekton/konflux-e2e-tests-push.yaml
magefiles/rulesengine/repos/e2e_repo.go

chore: don't run  builds when readmes or other irrelevant changes to code are modified

---

magefiles/magefile.go
pkg/clients/common/secret.go
pkg/clients/has/components.go
pkg/clients/integration/pipelineruns.go
pkg/clients/release/releases.go
pkg/sandbox/keycloak.go
pkg/sandbox/sandbox.go
pkg/utils/build/quay.go
pkg/utils/build/source_image.go
pkg/utils/loadtests/controller.go
tests/release/pipelines/fbc_release.go
tests/release/pipelines/multiarch_rh_advisories.go
tests/release/pipelines/release_to_github.go
tests/release/pipelines/rh_advisories.go
tests/release/pipelines/rh_push_to_external_registry.go
tests/release/pipelines/rh_push_to_redhat_io.go
tests/release/pipelines/rhtap_service_push.go

fix linter errors reported by a new version of golangci-lint
more info about the reported issues this PR is fixing:
* https://github.com/golang/go/issues/60529#issue-1733343158
* https://staticcheck.dev/docs/checks#SA1006
https://issues.redhat.com/browse/KFLUXBUGS-1538
`golangci-lint run`

fix: golangci-lint issues

---

tests/release/pipelines/fbc_release.go
tests/release/pipelines/multiarch_advisories.go
tests/release/pipelines/push_to_external_registry.go
tests/release/pipelines/release_to_github.go
tests/release/pipelines/rh_advisories.go
tests/release/pipelines/rh_push_to_external_registry.go
tests/release/pipelines/rh_push_to_redhat_io.go
tests/release/pipelines/rhtap_service_push.go
tests/release/pipelines/tenant_pipelines.go
tests/release/releaseLib.go
tests/release/service/happy_path.go

feat(RELEASE-1104): triggering release pipelines by snapshots

---

pkg/clients/integration/integration_test_scenarios.go
pkg/clients/integration/pipelineruns.go
tests/integration-service/gitlab-integration-reporting.go
tests/integration-service/integration-with-env.go
tests/integration-service/integration.go
tests/integration-service/status-reporting-to-pullrequest.go
tests/konflux-demo/konflux-demo.go
tests/load-tests/pkg/journey/handle_integration_test_scenarios.go

* Add IntegrationTestScenarios with different contexts to e2e tests
* Check that the new IntegrationTestScenarios are skipped as part of testing
* Check that the existing integrationTestScenarios have PLR triggered according to their context
Signed-off-by: dirgim <kpavic@redhat.com>
[STONEINTG-975](https://issues.redhat.com/browse/STONEINTG-975)

feat(STONEINTG-975): e2e tests for IntegrationTestScenarios contexts

---

.tekton/konflux-e2e-tests-pull-request.yaml

chore: Do not run pipelinerun when pull_request is in draft mode

---

.tekton/konflux-e2e-tests-pull-request.yaml

we should not run konflux-ci e2e tests if changes are made (only) to load-tests
N/A
[here](https://playcel.undistro.io/?content=H4sIAAAAAAAAA11QTWsCMRD9KyUIuqXN3vciIjlsERW30EtoSZNhDc0XSVYsjv%2B9o946lxnevHnzZi5Mg2MdO3Ovqj5CWcw%2FF8vORF2Qj7Yep2%2Fkp6KjAaxQamldVOb1XmKyCZwNUKjlk1OENi1KCu7NDG9C%2FLltlpTvIOnZMcQMuPvYisOA%2B8PuTazfcdOvxXYQtDE6FUZt%2Ba93yEsMKmsXJ8NTjglytbTrMfu12vSrQQzIyesP5IdwM5s37IUZVVUf0lTpsotkZ8m6J8n%2B%2B28lu8pAdE%2FXEfP2iesfCS427BEBAAA%3D)

fix: konflux-ci: ignore load tests changes

---

magefiles/rulesengine/repos/e2e_repo.go
pkg/constants/constants.go
tests/build/build.go
tests/release/service/happy_path.go

chore: remove dependency from build to release const.go

---

tests/build/build_templates.go
tests/build/build_templates_scenarios.go
tests/build/jvm-build.go
tests/konflux-demo/konflux-demo.go

This PR add a test repo which is using from scratch in the dockerfile
Also mentions the jira id for jbs related test skipping
https://issues.redhat.com/browse/STONEBLD-2085
Tested with [this PR](https://github.com/konflux-ci/build-definitions/pull/1320) here

feat: Add a test repo with dockerfile using from scratch

---

integration-tests/scripts/konflux-e2e-runner.sh

chore: Save e2e outputs to oci artifacts

---

tests/release/const.go
tests/release/pipelines/release_to_github.go

chore: pending release-to-gitHub test 

---

integration-tests/scripts/konflux-e2e-runner.sh

fix: remove duplicate test run command

---

integration-tests/scripts/konflux-e2e-runner.sh

chore: Fix exit code in the scripts

---

tests/release/OWNERS
tests/release/const.go

chore: add owner file in release dir

---

tests/release/const.go
tests/release/pipelines/fbc_release.go
tests/release/pipelines/multiarch_advisories.go
tests/release/pipelines/push_to_external_registry.go
tests/release/pipelines/release_to_github.go
tests/release/pipelines/rh_advisories.go
tests/release/pipelines/rh_push_to_external_registry.go
tests/release/pipelines/rh_push_to_redhat_io.go
tests/release/pipelines/rhtap_service_push.go
tests/release/service/happy_path.go

feat(RELEASE-1121): migrate the images re-used to hacbs-release-tests

---

tests/load-tests/ci-scripts/max-concurrency/collect-results.sh

fix(KONFLUX-3986): fix CSV header generator

---

tests/release/const.go
tests/release/pipelines/fbc_release.go
tests/release/pipelines/multiarch_advisories.go
tests/release/pipelines/release_to_github.go
tests/release/pipelines/rh_advisories.go
tests/release/pipelines/rh_push_to_redhat_io.go
tests/release/pipelines/rhtap_service_push.go
tests/release/releaseLib.go

fix: fix pipelines timeout

---

integration-tests/pipelines/konflux-e2e-tests-pipeline.yaml
integration-tests/scripts/konflux-e2e-runner.sh
integration-tests/tasks/konflux-e2e-tests-task.yaml

* Add task to generate correctly the OCI artifacts container
* Improve shell script to load secrets from files. 

chore: Add new task to create OCI artifacts and improve e2e runner script

---

integration-tests/pipelines/konflux-e2e-tests-pipeline.yaml

chore: Update konflux CI pipeline to use new naming for storage artifacts

---

integration-tests/pipelines/konflux-e2e-tests-pipeline.yaml
integration-tests/tasks/konflux-e2e-tests-task.yaml

chore: Revert fork name from pipelines

---

tests/release/service/tenant_pipelines.go

Change to use a simpler tenant pipeline for testing
Move tenant pipeline test case to release service directory

chore: change  tenant pipeline test case to use a simpler pipeline

---

pkg/clients/tekton/pipelineruns.go

Credits to @lcarva for investigating the issue and fixing it.

fix: delete pipelinerun  finalizer issue

---

magefiles/magefile.go
pkg/utils/build/custom_bundle.go
tests/build/build.go
tests/integration-service/gitlab-integration-reporting.go
tests/integration-service/integration.go
tests/konflux-demo/konflux-demo.go

use custom bundle with buildah-min task in e2e-tests
https://issues.redhat.com/browse/STONEBLD-2741
Locally

fix: use custom bundle in e2e-tests

---

OWNERS_ALIASES

Add tnevrlka to the build-team OWNERS alias so tnevrlka can review PRs relevant to the build team
N/A
N/A
N/A

chore: add tnevrlka to build OWNERS

---

magefiles/rulesengine/repos/e2e_repo.go

* fix test selection mechanism for the scenario when `tests/release/pipelines/*.go` files are changed
https://issues.redhat.com/browse/KFLUXBUGS-1635
Tested 3 scenarios:
```
I0916 13:12:40.751397   93011 util.go:450] The following files, magefiles/rulesengine/repos/e2e_repo.go, were changed!
I0916 13:12:40.751480   93011 types.go:72] Loading the catalog for, e2e-repo, from category, tests
I0916 13:12:40.751513   93011 types.go:155] The following rules have matched E2E Default PR Test Exectuion.
I0916 13:12:40.751516   93011 types.go:168] DryRun has been enabled will apply them in dry run mode
exec: ginkgo "--seed=1726485160" "--dry-run" "--timeout=1h30m0s" "--grace-period=30s" "--output-interceptor-mode=none" "--label-filter=!upgrade-create && !upgrade-verify && !upgrade-cleanup && …
```

fix: run release-pipelines tests if modified in PR

---

OWNERS_ALIASES

Adding my profile (rh-rahulshetty) to the perf-team alias for reviewing team's code changes.
N/A
N/A
N/A

chore: add rh-rahulshetty user to perf-team alias

---

pkg/clients/tekton/bundles.go
pkg/constants/constants.go
tests/build/build_templates.go
tests/build/build_templates_scenarios.go
tests/build/const.go
tests/build/source_build.go

Modify the structure of the component test scenarios to allow them to be executed by different build Pipelines.
Also...
In newer build Pipelines, the show-summary Task is no longer included. As such, remove the test that ensures the show-summary Task was included in the build Pipeline.
Ref: https://issues.redhat.com/browse/EC-715

feat: Test different Pipeline variants

---

pkg/utils/build/task_results.go

This changes are created to allign with 
https://github.com/konflux-ci/build-definitions/pull/1390

feat(STONEINTG-660): renaming clair scan result

---

tests/build/build_templates_scenarios.go

This change adds the `docker-build-multi-platform-oci-ta` pipeline to the list of bundles to be tested.
https://issues.redhat.com/browse/EC-715

feat: test multi-platform pipeline

---

OWNERS_ALIASES

Adding my profile (zxiong) to the perf-team alias for reviewing team's code changes.
N/A
N/A

chore: add zxiong user to perf-team alias

---

tests/load-tests/.gitignore
tests/load-tests/ci-scripts/max-concurrency/collect-results.sh
tests/load-tests/ci-scripts/max-concurrency/load-test.sh
tests/load-tests/run-stage-max-concurrency.sh

Adds script to run max-concurrency on Staging cluster.
[KONFLUX-4178](https://issues.redhat.com/browse/KONFLUX-4178)
```
export SERVER_API=<Server URL>
export TOKEN=<Token from Stage Cluster>
oc login --token=$TOKEN --server=$SERVER_API
source user.env
export RUN_ON_STAGE=true
export THRESHOLD=3500 MAX_THREADS=300 MAX_CONCURRENCY_STEPS=1,2,3 COMPONENT_REPO=https://github.com/rh-perf-test-org/devfile-sample PIPELINE_REQUEST_CONFIGURE_PAC=true
./tests/load-tests/ci-scripts/max-concurrency/load-test.sh
./tests/load-tests/ci-scripts/max-concurrency/collect-results.sh
```

feat(KONFLUX-4178): Add script to run max-concurrency tests on staging cluster

---

integration-tests/pipelines/konflux-e2e-tests-pipeline.yaml
tests/release/const.go

Increase the time limitation since some test case may run a long time 

fix: increase konflux-e2e tests run time limitation

---

tests/integration-service/README.md

chore(stoneintg-942): update readme with new test info

---

magefiles/magefile.go
magefiles/rulesengine/engine/engine.go
magefiles/rulesengine/repos/build_service.go

feat(KONFKUX-4006): Add mage engine rules for build-service repo

---

integration-tests/scripts/konflux-e2e-runner.sh

TTSIA
https://issues.redhat.com/browse/KFLUXBUGS-1721
in CI 🤷

fix: link pull secret to console-sa for minio

---

.github/workflows/loadtest.yaml
tests/load-tests/ci-scripts/merge-json.sh

This PR fixes the load test workflow for running tests via GitHub Actions.
https://issues.redhat.com/browse/KONFLUX-4925
I have successfully [tested](https://github.com/rh-rahulshetty/e2e-tests/actions/workflows/loadtest.yaml) the changes for Github Action in my fork.
**Steps to Run:**
1. Clone my fork: `https://github.com/rh-rahulshetty/e2e-tests.git`
2. Configure the following Github Action Secrets in `https://github.com/<profile>/e2e-tests/settings/secrets/actions`:
- **GH_TOKEN**: Private token used in Konflux tests to fork repository.
-  **OCP_PROMETHEUS_TOKEN**: Cluster Service-Account token to fetch metrics from Prometheus.
- **STAGE_MEMBER_CLUSTER**: Cluster API-Server URL
-  STAGING_USERS_1
- STAGING_USERS_2
- STAGING_USERS_3
- STAGING_USERS_4
- STAGING_USERS_5
- STAGING_USERS_6 …

fix(KONFLUX-4925): Fix Github Action Setup for perf load-test

---

pkg/clients/release/releases.go
tests/release/pipelines/fbc_release.go
tests/release/pipelines/multiarch_advisories.go
tests/release/pipelines/release_to_github.go
tests/release/pipelines/rh_advisories.go
tests/release/pipelines/rh_push_to_redhat_io.go
tests/release/pipelines/rhtap_service_push.go
tests/release/releaseLib.go

Update the error handling in the loop of running pipelineRun. 
Store the release pipelineRun log and Release CR when test is finished.

feat(RELEASE-1201): get pipelineRun logs from staging cluster

---

pkg/constants/constants.go
tests/release/pipelines/fbc_release.go

fix(KFLUXBUGS-1614): fbc pipeline should stop passing binaryimage to iib

---

tests/build/build_templates.go

since the issue is resolved, changed the test accordingly.
https://issues.redhat.com/browse/KONFLUX-3649

chore: cleanup in build tests

---

tests/build/build.go

Skipping this test till the issue is fixed
https://issues.redhat.com/browse/KFLUXBUGS-1820

chore: skip multicomponent test with same git url

---

tests/release/pipelines/rh_push_to_redhat_io.go

chore: enable rh_push_to_redhat_io

---

magefiles/rulesengine/repos/release_service_catalog.go

fix: isPaired need to be set

---

tests/build/tkn-bundle.go

tkn-bundle test started failing in the e2e-tests CI, skipping it
https://issues.redhat.com/browse/KFLUXBUGS-1899

chore: skipping the tkn-bundle test

---

tests/konflux-demo/konflux-demo.go

This step is failing intermittently in our periodic jobs.
N/A

fix: wrap the pipeline run signed check inside eventually

---

tests/release/pipelines/rh_advisories.go

feat(RELEASE-1296): rh-advisories e2e test should have a cve

---

magefiles/magefile.go

feat(): Add json report to the e2e tests for analysis in the future with sealights

---

tests/build/build.go
tests/konflux-demo/konflux-demo.go
tests/release/pipelines/fbc_release.go
tests/release/pipelines/multiarch_advisories.go
tests/release/pipelines/push_to_external_registry.go
tests/release/pipelines/release_to_github.go
tests/release/pipelines/rh_advisories.go
tests/release/pipelines/rh_push_to_external_registry.go
tests/release/pipelines/rh_push_to_redhat_io.go
tests/release/pipelines/rhtap_service_push.go
tests/release/service/happy_path.go
tests/release/service/missing_release_plan_and_admission.go
tests/release/service/release_plan_and_admission_matched.go

We moved all of our managed pipelines into pipelines/managed instead of just being in pipelines/. We have sym links for backwards compatibility, but only temporarily. This commit updates the pathInRepo values to include the managed directory.

refactor(RELEASE-1320): update release pipeline pathInRepo values

---

magefiles/rulesengine/repos/release_service_catalog.go

feat(RELEASE-1317): fine tune deployed components for release-pipelines suite

---

tests/load-tests/ci-scripts/stage/cluster_read_config.yaml
tests/load-tests/run-stage-max-concurrency.sh

Collect additional ETCD metrics for loadtest.
https://issues.redhat.com/browse/KONFLUX-6576
Tested the changes through GitHub Actions in Konflux Staging and confirmed that below metrics are being collected.

feat(KONFLUX-6576): Collect additional ETCD metrics for loadtest

---

pkg/utils/build/custom_bundle.go
tests/build/build_templates.go

This PR tries to add check for package name and purl in the SBOM component/package
https://issues.redhat.com/browse/STONEBLD-3193

fix: add additional check for pkg name and purl

---

magefiles/magefile.go
magefiles/rulesengine/repos/common.go
magefiles/rulesengine/types.go

feat(KFLUXDP-160): Add a rule for tekton push events

---

OWNERS_ALIASES

This is because Pat has left the integration service team, and I would like to make his life a little bit better.

chore: Remove Pat from integration-service's alias list

---

pkg/clients/has/components.go

* The previous iteration of the WaitForComponentPipelineToBeFinished function was always using the originally supplied `sha` parameter on every attempt of retriggering a component build
* This fix ensures that the `shaToUpdate` variable is used instead and correctly updated on every new attempt
Signed-off-by: dirgim <kpavic@redhat.com>
[KONFLUX-6572](https://issues.redhat.com//browse/KONFLUX-6572)

fix(KONFLUX-6572): fix retries for WaitForComponentPipelineToBeFinished

---

integration-tests/tasks/konflux-e2e-tests-task.yaml

fix: Fix the wrong sealights test session task path

---

magefiles/rulesengine/repos/common.go

feat: Enable debug mode for ginkgo tests to detect Sealights issues

---

integration-tests/scripts/konflux-e2e-runner.sh
integration-tests/tasks/konflux-e2e-tests-task.yaml

feat: Disable by default the Sealights test selections

---

tests/release/pipelines/multiarch_advisories.go
tests/release/pipelines/rh_advisories.go

refactor(RELEASE-1397): turn release product_ids into lists

---

tests/release/const.go
tests/release/pipelines/fbc_release.go
tests/release/releaseLib.go

* Added functions CreateComponentWithNewBranch and CreatePushSnapshot
to build a new image and trigger the managed pipelineRun.
* Updated four FBC test cases to use the functions and delete the test
branches created for testing.

feat(RELEASE-1312): change FBC e2e tests back to build a image

---

tests/release/pipelines/rh_advisories.go

We are adding more and more tasks to the advisory pipeline that do things based on the issues.fixed in the releaseNotes key. To ensure testing coverage, this commit adds an issue to the advisory test. The issue used is one of the ones opened for some of the advisory issue improvements, so that we do not run the risk of interfering with anyone else's issues.

feat(RELEASE-1401): add fixed issue in release advisory test

---

tests/release/pipelines/rh_push_to_redhat_io.go

There are several containers in run-file-updates pod. It checks the log of first container to find the mrURL before. Changed to loop all the logs of the containers to find the mrURL string.

fix: the mrURL can't be found in rh_push_to_redhat_io test

---

tests/build/tkn-bundle.go

- Update tkn-bundle tests
- Enable tests

fix(KONFLUX-7413): tkn-bundle test started failing consistently

---

pkg/clients/has/components.go
pkg/clients/integration/pipelineruns.go
pkg/clients/integration/snapshots.go
tests/integration-service/group-snapshots-tests.go

* e2e test case for cancelled snapshot and integration plr

feat(STONEINTG-1051): e2e for cancelled snapshot and intg plr

---

tests/release/pipelines/fbc_release.go
tests/release/releaseLib.go

Variable `pipelineRun` may conflict in parallel test, so seperate it to several variables.

fix: variable potential conflict in parallel test

---

pkg/utils/tekton/pipelineruns.go
tests/build/build_templates.go

exclude slsa_source_correlated.source_code_reference_provided to fix conforma violation
https://issues.redhat.com/browse/KONFLUX-5787

fix: ec pipeline conforma violation in build-template.go

---

magefiles/rulesengine/repos/e2e_repo.go
magefiles/rulesengine/repos/release_service_catalog.go
tests/release/pipelines/fbc_release.go

Update the revision for the test repo in case the old tekton config files in that repo is used unexpectly. 
Extend the timeout for the test jobs with release-pipelines suite

fix: update the revision for the test repo for fbc tests

---

tests/integration-service/gitlab-integration-reporting.go

feat(STONEINTG-853): test on-push commit

---

pkg/utils/tekton/pipelineruns.go

It's to fix "panicked" issue coming from the function of GetFailedPipelineRunDetails(). If there is no failed log caught,  nil pointer leads to panic. This PR adds checking before using the variable `d` and it records the log message according to the information it can get.
An example with the failure before:
https://app-artifact-browser.apps.rosa.konflux-qe.zmr9.p3.openshiftapps.com/e2e-tests/konflux-e2e-4cpgt/e2e-tests.log

fix: test panic for no container log gotten

---

Dockerfile
pkg/utils/build/quay.go
tests/build/build_templates.go
tests/build/build_templates_scenarios.go

This PR will add a scenario with `docker` mediaType generation and also adds validation for the `oci` mediaType 
https://issues.redhat.com/browse/STONEBLD-3352

feat: add scenario to cover docker mediaType and validations

---

pkg/clients/common/namespace.go

Refactor the code that ensure required labels exist on a namespace so it can handle multiple labels.

refactor: label assignment to namespaces

---

tests/release/pipelines/fbc_release.go

Add pyxis params for fbc-release
[CLOUDDST-26262](https://issues.redhat.com//browse/CLOUDDST-26262)

feat(CLOUDDST-26262): add pyxis params for fbc-release

---

magefiles/rulesengine/scripts/find_release_pipelines_from_pr.sh

Add new filter-already-released-advisory-images for smart selecting test cases for the release pipeline suite

feat(RELEASE-1263): include new internal pipeline for standalone test

---

tests/integration-service/README.md

chore(stoneintg-1092a): update IS readme info with new tests

---

pkg/clients/integration/pipelineruns.go
tests/build/tkn-bundle.go
tests/integration-service/group-snapshots-tests.go

* log out the log of failing task for intg group snapshot tst causing infra-deployment PR 6786 failure

chore: log out the err for intg group snapshot tst

---

tests/release/service/happy_path.go

The task name was changed here https://github.com/konflux-ci/release-service-catalog/commit/57781be106fc82932aa0258f260b89e35c91804e

fix: update conforma task name in release-service happy path

---

tests/build/tkn-bundle.go

tkn-bundle test started failing after recent secret related change, disabling it temporarily to unblock CI 
https://issues.redhat.com/browse/KONFLUX-9777

chore: disable tkn-bundle test temporarily

---

tests/integration-service/group-snapshots-tests.go

Fix the [groupsnapshots handling](https://github.com/konflux-ci/e2e-tests/blob/2b3da3665f1204a7cdb454b7686fa45ef43ef9da/tests/integration-service/group-snapshots-tests.go#L483-L495)  : 
1. code has a couple of logical issues. The current order of checks can lead to a panic if groupSnapshots is nil but err is also nil. The check for err!=nil should always come first.
2. Correct Condition Check: The original code had if groupSnapshots == nil. However, a function that returns a collection will often return an empty slice ([]type{}{}) instead of a nil slice if no results are found. Checking len(groupSnapshots) == 0 is the more idiomatic and robust way to check for an empty result set
[STONEINTG-1334](https://issues.redhat.com/browse/STONEINTG-1334) 
Please describe the tests that you ran to …

fix(STONEINTG-1334): fix groupsnapshots and error handling

---

pkg/clients/has/components.go
tests/build/build.go
tests/build/build_templates.go
tests/build/multi-platform.go
tests/integration-service/gitlab-integration-reporting.go
tests/integration-service/integration.go
tests/integration-service/pipelinerun-resolution.go
tests/integration-service/status-reporting-to-pullrequest.go
tests/konflux-demo/konflux-demo.go
tests/load-tests/pkg/journey/handle_collections.go
tests/load-tests/pkg/journey/handle_component.go
tests/load-tests/pkg/journey/handle_pipeline.go

This PR adds a scenario of re running push pipeline in the build test
https://issues.redhat.com/browse/STONEBLD-1856
Locally.

feat: add rerunning push pipeline scenario

---

tests/integration-service/group-snapshots-tests.go

Improving the integration service e2e-tests stability 
1. replace the calls of function `WaitForBuildPipelineToBeFinished` to function with  [WaitForComponentPipelineToBeFinished](https://github.com/konflux-ci/e2e-tests/blob/main/pkg/clients/has/components.go#L182) 
WaitForComponentPipelineToBeFinished :
✅ Advanced Retry Logic: Implements sophisticated retry mechanism with configurable RetryOptions
✅ Intelligent Failure Handling: Only retries specific failure types (CouldntGetTask, TaskRunImagePullFailed)
✅ Automatic Recovery: Can delete and recreate failed PipelineRuns
✅ PipelineRun Reference Update: Updates passed PipelineRun object for later use
✅ Comprehensive Error Logging: Better error messages and diagnostics
✅ Flexible Pipeline Types: Supports different pipeline types via …

fix(STONEINTG-1334): improve the group snapshot suite

---

tests/integration-service/const.go
tests/konflux-demo/config/scenarios.go

See https://github.com/redhat-appstudio-qe/hacbs-test-project-konflux-demo/commit/79402df023e646c5ad108abc879ad1b28799cbc4 for more info
Updated following repos:
* https://github.com/redhat-appstudio-qe/hacbs-test-project
* https://github.com/redhat-appstudio-qe/hacbs-test-project-konflux-demo
* https://github.com/redhat-appstudio-qe/konflux-test-integration
* https://github.com/redhat-appstudio-qe/konflux-test-integration-clone
* https://github.com/redhat-appstudio-qe/konflux-test-integration-resolution
* https://github.com/redhat-appstudio-qe/konflux-test-integration-status-report
* https://gitlab.com/konflux-qe/hacbs-test-project-integration

fix: update konflux-demo test repo git ref

---

tests/integration-service/const.go

* this is a follow-up on https://github.com/konflux-ci/e2e-tests/pull/1697

fix: multi repo component git revision
