konflux-ci/e2e-tests

.github/workflows/build.yaml

Switch from docker GH actions to RedHat github actions for building
and pushing the image to quay.io.
I've tried to run this in my fork (with my credentials pushing to my quay.io repository) - Proof it's working: 
* https://github.com/rhopp/e2e-tests/runs/4458369614?check_suite_focus=true <- job run
* https://quay.io/repository/rhopp/e2e-tests?tag=latest&tab=tags <- quay.io pushed image

fix: Fix build&push GH action.

---

pkg/tests/common/appstudio.go
pkg/tests/has/application.go
pkg/utils/common/controller.go
pkg/utils/has/controller.go
report.xml

This PR contain the next changes:
* "dot imports" - to make the code shorter and easier to read for gomega
* Add a poll to wait for clusterTasks to be pre-created in cluster.

Add a wait time to e2e to wait for bundles templates to be created

---

.ci/openshift-ci/Dockerfile
.ci/openshift-ci/oci-launch-e2e.sh

Infra-deployment switched to use integrated kustomize command in `oc`
and `kubectl`.
Can be merged after https://github.com/redhat-appstudio/infra-deployments/pull/134

Remove dependency on kustomize

---

scripts/install-appstudio-e2e-mode.sh

If we run this script in separate PRs we don't need to run the e2e bin from this script.

Don't run e2e in the AppStudio installation mode.

---

pkg/tests/build/chains.go

We seem to be running into a race condition between the cosign verify*
tasks and the chains-controller creating the attestation. This disables
(skips) the test while we work on a solution for the race condition.

Temporarily disable the chains test

---

.gitignore
scripts/install-appstudio-e2e-mode.sh

Changed ROOT_E2E export to "$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"/.. to work on MacOS.

fix mac export ROOT_E2E

---

go.mod
go.sum
pkg/tests/build/chains.go
pkg/utils/tekton/controller.go
pkg/utils/tekton/controller_test.go

In the chains test we before we check the attestation and signature we
need to make sure that the chains-controller has had enough time to
create them. Otherwise we would fail the cosign* tasks due to the images
with the attestation and signature not pushed/tagged in the interlan
registry.
This adds a step to wait for a maximum of 60 seconds for the images to
be created by listing the ImageStreamTag and looking for the specific
`.att` and `.sig` image tags to be present there.
Fixes https://issues.redhat.com/browse/HACBS-278

Wait for signature and attestation

---

.ci/oci-launch-e2e.sh
pkg/constants/constants.go
pkg/framework/framework.go
pkg/utils/has/controller.go
scripts/Readme.md
scripts/install-appstudio-e2e-mode.sh
tests/build/chains.go
tests/cluster-registration/clusters.go
tests/has/const.go
tests/has/devfile_source.go

https://issues.redhat.com/browse/PLNSRVCE-149
* allow running the e2e test suite in the namespace provided via `E2E_APPLICATIONS_NAMESPACE` env var (otherwise use default namespace: 'appstudio-e2e-test')
* make sure the specified namespace has the required label: `argocd.argoproj.io/managed-by: gitops-service-argocd`, otherwise update the namespace with that label
* skip checking `has-github-token` secret in `application-service` namespace if `SKIP_HAS_SECRET_CHECK` env var is set
* with these changes, we are able to run the whole HAS test suite in custom namespace as a regular user
* follow-up PR: https://github.com/redhat-appstudio/infra-deployments/pull/298
1. Run
```bash
export GITHUB_TOKEN=<YOUR_GITHUB_TOKEN> GITHUB_E2E_ORGANIZATION=<YOUR_GITHUB_ORG> …
```

test: allow running e2e test suite in custom namespace

---

pkg/utils/tekton/controller.go

When an API returns the error it most likely will return `nil` as well
for the other tuple's value, which when used could lead to panics. So
instead of ignoring the errors lets propagate them.

Add missing error handling

---

Dockerfile
pkg/apis/github/repositories.go

https://issues.redhat.com/browse/PLNSRVCE-149
We were running e2e tests on a staging cluster and were getting the following error caused by missing certificates in the e2e-tests container image
```
E0427 13:43:41.065154      16 repositories.go:12] error when sending request to github API: Get "https://api.github.com/repos/redhat-appstudio-appdata/pet-clinic-e2e-build-templates-think-face": x509: certificate signed by unknown authority
```
Replacing the base image with ubi-minimal fixes the issue

fix: replace "scratch" base image with ubi-minimal

---

tests/has/devfile_source.go

As we move some functionality from HAS into Build operator, the test case for waiting pipeline run to be completed is not relevant to HAS anymore.

chore: Remove build test

---

tests/has/devfile_source.go

Removing this tests in favor of gitops deployments. Related [PR](https://github.com/redhat-appstudio/e2e-tests/pull/57) where gitops checks are added. This PR also fix some failures in CI like: https://github.com/redhat-appstudio/application-service/pull/104

fix: Remove unused checks

---

.ci/oci-launch-e2e.sh
pkg/framework/describe.go
pkg/utils/has/controller.go
tests/build/README.md
tests/build/build.go
tests/has/devfile_source.go

https://issues.redhat.com/browse/PLNSRVCE-185
This PR introduces build-service suite that will be used for PR e2e testing of [build-service](https://github.com/redhat-appstudio/build-service) and pipelines in [build-definitions](https://github.com/redhat-appstudio/build-definitions) repo
1. Bootstrap a cluster - follow the instructions [here](https://github.com/redhat-appstudio/e2e-tests/blob/main/docs/Installation.md#installation-of-appstudio-e2e-mode)
2. Run the build-service tests
```bash
make build && ./bin/e2e-appstudio --ginkgo.progress --ginkgo.v --ginkgo.focus="build-service-suite"
```
3. Tests should suceed

test: build-service test suite

---

.ci/openshift-ci/Dockerfile
Dockerfile

To unblock https://github.com/redhat-appstudio/e2e-tests/pull/63 and https://github.com/redhat-appstudio/e2e-tests/pull/65 which both depend on Go 1.17

test: Use Go 1.17 to build e2e-tests

---

tests/build/build.go

Increase timeout for checking PipelineRun creation. We've seen failures on slower clusters where the original timeout wasn't sufficient and caused the test to fail.

fix: build-service test: increase timeout

---

tests/build/build.go
tests/has/Readme.md
tests/has/devfile_source.go

This PR changes the output image name (used in `has` and `build-service` suites) to `quay.io/<org>/test-images` to get aligned with what we have in [redhat-appstudio quay org](https://quay.io/repository/redhat-appstudio/test-images) - we will be probably using this repo for storing images built by other tests too (not just from this repo).
(What is it good for currently? If we run the test with `QUAY_E2E_ORGANIZATION=redhat-appstudio`, the test will still pass since that repo exists and is managed by the redhat-appstudio robot account)
This repo was already created in [redhat-appstudio-qe quay org](https://quay.io/repository/redhat-appstudio-qe/test-images), so PR tests should not be failing because of that

fix: unify output image name for all test suites

---

.tekton/pull-request.yaml
.tekton/push.yaml

This will enable the e2e-tests repo to easily configure Tekton as CI for PR checks.
The goal of Pipelines as Code is to let you define your Tekton templates inside your source code repository and have the pipeline run and report the status of the execution when triggered by a Pull Request or a Push.

ci: setup Pipelines-as-Code for e2e-tests

---

docs/DeveloperFocus.md
docs/Installation.md

Added some additional setup details and information for developers to use when creating e2e tests and running said tests before merging.

docs: Developer focused e2e update

---

go.mod
scripts/e2e-openshift-ci.sh

Update to go 1.17 and fix the PULL_NUMBER environment which don't exist in periodic jobs
https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-redhat-appstudio-infra-deployments-main-appstudio-e2e-deployment-periodic/1528888861466300416

fix: Fix pull number in periodic jobs and update to go 1.17

---

tests/build/chains.go
tests/e2e-demos/const.go

We changed the output in ec-policy Rego files with the effort to switch
to using `conftest` instead of `opa`. This adjusts the expected output
in the end to end test to match this.
Ref. https://github.com/redhat-appstudio/e2e-tests/pull/86
Ref. https://github.com/redhat-appstudio/infra-deployments/pull/387
N/A
Run the chains test suite locally

fix: adjust to the latest ec-policy output

---

.ci/oci-launch-e2e.sh
scripts/spi-e2e-setup.sh

spi-e2e-setup.sh script was being [executed twice](https://github.com/redhat-appstudio/e2e-tests/blob/75ce8e726b6ac842c31970fbd329f4496aee0235/scripts/install-appstudio-e2e-mode.sh#L60) in openshift-ci

fix: remove duplicate SPI setup

---

tests/build/chains.go

A change in ec-policy modified the rule that matches the case where test
data is not available:
https://github.com/hacbs-contract/ec-policies/pull/38

fix: Update expected empty data error

---

tests/build/chains.go

Merging https://github.com/hacbs-contract/ec-policies/pull/40 will
break the EC task and also some e2e tests.
Rather than break tests, or delay merging until all the related PRs
are ready to merge, let's temporarily disable the contract related
tests.

fix: Skip enterprise contract tests temporarily

---

.vscode/launch.json
README.md

This adds launch/debug configuration in vscode. 
Locally

chore: Add launch.json with debug configuration.

---

.github/workflows/PR.yaml

fixing issues caused by golangci-lint and goversion mismatch

fix: Linter go version issues

---

OWNERS

This adds OWNERS file to the root of the repo. Since recently we enabled Tide for our repo, we should also specify approvers in this OWNERS file for tide to properly work

chore: Add OWNERS file

---

Dockerfile

fix the error that's encountered when running e2e tests as a pod in openshift:
```
[SynchronizedBeforeSuite] [FAILED] [0.000 seconds]
[SynchronizedBeforeSuite]
/github.com/redhat-appstudio/e2e-tests/cmd/e2e_test.go:27
Begin Captured GinkgoWriter Output >>
[SynchronizedBeforeSuite] TOP-LEVEL
/github.com/redhat-appstudio/e2e-tests/cmd/e2e_test.go:27
<< End Captured GinkgoWriter Output
Unexpected error:
<*fs.PathError | 0xc0009f6b10>: {
Op: "open",
Path: "/root/tests/e2e-demos/config/default.yaml",
Err: <syscall.Errno>0x2,
}
open /root/tests/e2e-demos/config/default.yaml: no such file or directory
occurred
In [SynchronizedBeforeSuite] at: /github.com/redhat-appstudio/e2e-tests/tests/e2e-demos/e2e-demo.go:43
```
tests are failing in [this …

fix: test-container

---

tests/build/chains.go

Update the assertions to match the new conftest output produced by
https://github.com/hacbs-contract/ec-policies/pull/40 so the tests
pass.
Note: This requires that
https://github.com/redhat-appstudio/build-definitions/pull/124 is merged and
visible in the task bundle being used by the e2e tests. I'm not sure what the process is to make that happen.

fix: Unskip and fix failing EC tests

---

pkg/utils/has/controller.go
tests/has/devfile_private_source.go
tests/has/devfile_source.go

This PR adds a test to verify that when the Application CR is deleted before the Component CR, the associated Component CRs should all be deleted. 
It also fixes a bug: when creating a component using CreateComponentFromStub the Application name was not set, failing to set the owner references properly.
https://issues.redhat.com/browse/DEVHAS-58

test: add has application delete test

---

pkg/utils/common/controller.go
tests/release/release-failures.go

* Fix runtime error occurring when the `release.Status.Condition` field is not populated with any items yet, e.g. [in this test run](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/redhat-appstudio_infra-deployments/466/pull-ci-redhat-appstudio-infra-deployments-main-appstudio-e2e-deployment/1542492678392909824)
* add a check for validating that "pipeline" service account is present in the test namespace before proceeding with test
N/A
Tested against quicklab cluster

fix: release: runtime error

---

.github/workflows/PR.yaml
pkg/framework/describe.go
pkg/utils/common/controller.go
tests/build/README.md
tests/build/build.go
tests/build/const.go

Allow specifying multiple component URLs to build
This PR also contains changes that allow build-service tests to run in parallel. There is a plan to run other tests in parallel too in a future - see [this doc](https://docs.google.com/document/d/1Nxy08I9AikLRADfFM4Slmmf_paSZjuocg0ECiOBOEz8/edit#heading=h.w4snan7yrscx) for more details
This PR also introduces testing of build using the HACBS pipeline (instead of base-appstudio one) in one test case.
This test case (labeled as build-templates-e2e) is then used in PR test in [build-definitions repo](https://github.com/redhat-appstudio/build-definitions/pull/156)
https://issues.redhat.com/browse/PLNSRVCE-180
```bash
export COMPONENT_REPO_URLS=https://github.com/redhat-appstudio-qe/devfile-sample-hello-world,https://github.com/devfile-samples/d …
```

test: build multiple components from input

---

pkg/utils/tekton/controller.go
tests/build/chains.go

When running the chains e2e suite it would be useful to have extra details get output to the logs to make troubleshooting failures easier. Currently we just get error strings on failure with none of the underlying state data written to the log.
https://issues.redhat.com/browse/HACBS-573
$ ./bin/e2e-appstudio --ginkgo.focus-file tests/build/chains.go --ginkgo.vv
logs:
```
[chains-suite Tekton Chains E2E tests] infrastructure is running
verify the chains controller is running
/home/chuo/gitsrc/hacbs/e2e-tests/tests/build/chains.go:28
•
------------------------------
[chains-suite Tekton Chains E2E tests] infrastructure is running
verify the correct secrets have been created
/home/chuo/gitsrc/hacbs/e2e-tests/tests/build/chains.go:32
•
------------------------------
[chains-suite Tekton …
```

refactor: add debug info for chain e2e test

---

go.mod
go.sum
pkg/apis/kubernetes/client.go
pkg/framework/describe.go
pkg/framework/framework.go
pkg/utils/jvmbuildservice/controller.go
pkg/utils/tekton/controller.go
tests/build/jvm-build.go

Adding a new suite for testing https://github.com/redhat-appstudio/jvm-build-service PR's via the openshift/release induced e2e test flow.
Certainly we'll augment this as jvm-build-service matures (including a component induced flow, gradle based builds, multi-versions, etc etc etc).  I did not initially add a run with the service registry, but that is certainly a desired target.  And lastly, once we have some meets min verification up, I envision further introspection of the artifactbuild and dependencybuild taskruns.
An added step I chose not to take on with this initial introduction PR is add a `SuiteController` that can examine the jvm-build-service `ArtifactBuild` and `DependencyBuild` CRD instances and their various states.  A subsequent story/goal I suspect.
@psturc @stuartwdouglas …

feat: PLNSRVCE-452: add initial e2e test for jvm-build-service

---

go.mod
go.sum
pkg/apis/kubernetes/client.go
pkg/framework/describe.go
pkg/utils/tekton/controller.go
pkg/utils/tekton/controller_test.go
pkg/utils/tekton/matchers.go
pkg/utils/tekton/pipelines.go
tests/build/chains.go

This should fix all outstanding issues with Enterprise contract end to end tests. I've unified all the changes made in #146 and #145 because to get the end to end test to pass all of these changes need to be lumped together.
Here is the text from the commit messages and links to individual commits to make the review somewhat easier:
[refactor: tests for cosign-verify-* tasks](https://github.com/redhat-appstudio/e2e-tests/commit/f6ae31a24418477200b35cade28cfa9a218a70f4)
Follow up on https://github.com/redhat-appstudio/build-definitions/pull/173 to remove testing of `cosign-verify-*` tasks that are removed there.
This was previously present in #146
[refactor: bundle image reference for pull requests](https://github.com/redhat-appstudio/e2e-tests/commit/d326642f8a5bcb1f3cde05601e06377dfeef988 …

fix: everything in Enterprise contract tests suite

---

.ci/oci-launch-e2e.sh
scripts/install-appstudio-e2e-mode.sh

Preview mode now sets SPI and waits on deployment of argocd applications. https://github.com/redhat-appstudio/infra-deployments/pull/518
It's going to be tested by CI process

ci: preview mode is now setting SPI and waiting for deployment

---

pkg/apis/kubernetes/client.go
pkg/utils/common/controller.go
pkg/utils/has/controller.go
pkg/utils/tekton/controller.go
tests/build/build.go
tests/has/devfile_private_source.go
tests/has/devfile_source.go
tests/integration-service/integration.go

This PR should fix intermittent issues seen with 'namespace is not managed' errors from Argo CD, as reported on [this PR](https://github.com/redhat-appstudio/infra-deployments/pull/415#issuecomment-1200940627) and elsewhere.
- This is caused by the OpenShift GitOps operator (not the GitOps Service) incorrectly handling `Namespace`s that are stuck in the 'Terminating' state. I will [follow up with the OpenShift GitOps team](https://issues.redhat.com/browse/GITOPS-2242) on the desired behaviour, here.
- Instead, this PR avoids this issue by ensuring that `PipelineRun`s (and their finalizers) are cleaned up before a `Namespace` is deleted.
See below for details of the fix.
This PR:
- When creating a test namespace (a namespace with `argocd.argoproj.io/managed-by` label), ensure that the …

fix: Wait for Argo CD Role/RoleBindings on Namespace creation, and cleanup PipelineRuns on Namespace deletion

---

tests/build/build.go

Follow-up PR on https://github.com/redhat-appstudio/e2e-tests/pull/161. Changes in that PR caused the "image repo protection" test flakey, because the new **pipelinerun** cleanup function conflicts with **component** cleanup function (which I removed in this PR)
```bash
for i in {1..10}; do echo $i && ginkgo --focus="Creating a component with a specific container image URL" --progress -v ./cmd -- --config-suites=/Users/psturc/work/redhat-appstudio/e2e-tests/tests/e2e-demos/config/default.yaml > /dev/null || echo ERROR; done
```

fix: build: image repo protection test

---

pkg/utils/tekton/controller.go
tests/build/jvm-build.go

ok @flacatus @psturc here is the attempt to add jvm-build-service e2e's back, and per https://github.com/redhat-appstudio/e2e-tests/pull/153#issuecomment-1192919677, we are reattempting with a much small / less resource intensive java app from @stuartwdouglas as well as removal of task run checks, since this runs with pruning 
Now, yesterday we had to fix some things in jvm-build-service to get it to meets-min functionality, so I expect we will need https://github.com/redhat-appstudio/infra-deployments/pull/523 to merge in order to get jvm-build-service to a functional level for the test
Let's see if that plays out in the results.
https://issues.redhat.com/browse/PLNSRVCE-452
- [/] New feature (non-breaking change which adds functionality)
Local testing as well as our in repo tests in …

feat: PLNSRVCE-538: add jvm build service test back (but with less expensive repo resource wise)

---

tests/build/jvm-build.go

temporarily disable jvm-build-service test because of this issue
```
[ERROR] Plugin org.apache.maven.plugins:maven-shade-plugin:3.2.4 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-shade-plugin:jar:3.2.4: Could not transfer artifact org.apache.maven.plugins:maven-shade-plugin:pom:3.2.4 from/to mirror.default (http://localhost:2000/maven2): Transfer failed for http://localhost:2000/maven2/org/apache/maven/plugins/maven-shade-plugin/3.2.4/maven-shade-plugin-3.2.4.pom 500 Internal Server Error -> [Help 1]
```
https://issues.redhat.com/browse/PLNSRVCE-533
```
ginkgo --focus="jvm-build-service" --progress -v ./cmd -- --config-suites=/Users/psturc/work/redhat-appstudio/e2e-tests/tests/e2e-demos/config/default.yaml
```

fix: disable jvm-build-service tests temporarily

---

tests/build/jvm-build.go

Recent changes in the jvm-build-service allowed the artifact cache to run per specific namespace, as opposed to always run in the jvm-build-service namespace (see https://github.com/redhat-appstudio/jvm-build-service/pull/105).
This PR creates a configmap in the test namespace that will configure the cache service and fix the issues of timeouts that are happening with the test suite. 
We're also reverting the change that was introduced in #165, since that needs https://github.com/redhat-appstudio/build-definitions/pull/179 to work.
Tested in a private cluster.

fix: Fix the jvm build service tests

---

.ci/oci-launch-e2e.sh
pkg/utils/tekton/controller.go
pkg/utils/tekton/controller_test.go
pkg/utils/tekton/matchers.go
pkg/utils/tekton/matchers_test.go
pkg/utils/tekton/pipelines.go
tests/build/chains.go

This includes some refactoring and fixes in order to test the verify-enterprise-contract-v2 task. Namely:
[fix: two layers needed in attestation image](https://github.com/redhat-appstudio/e2e-tests/pull/158/commits/720a04f052552c7bcfadc66ba0c7c78adb00d546)
The Tekton Chains controller will push two layers to the attestation
image. One containing the TaskRun attestation and one containing the
PipelineRun attestation. We require PipelineRun attestation to be
present. Without downloading and examining the image we can make sure
that the PipelineRun attestation is present if the `ImageStreamTag` has
two `dockerImageLayers`.
We're now fetching the `ImageStreamTag` directly rather than listing all
and filtering the items list for `ImageStreamTag` with a specific name.
[feat: JSONPath matching …

feat: e2e tests for verify-enterprise-contract-v2

---

pkg/utils/tekton/controller.go
tests/build/jvm-build.go

Still seeing intermittent failures in jvm build tests; best guess from the failed runs I have seen today is pruning of deleting completed ab's / db's before we can count them, but currently there is not logic in the jvm build service controller to generate logs or events when it does prune.
see https://github.com/redhat-appstudio/infra-deployments/pull/581 for example
I'll be crafting a PR to address the logging for future debug.  Of course pruning logging might in fact steer us in another direction if it proves this is not pruning, and we'll have to go from there.
But this may be the sign to pursue minimally the next iteration on pruning, or the throttling approach (at least for the time being) that @stuartwdouglas and I have discussed, in the upcoming sprint 10
@Michkov @brunoapimentel …

fix: comment out jvm tests yet again

---

pkg/utils/build/sbom.go
tests/build/build.go

This PR changes the SBOM test so that it validates the presence of important fields.
[PLNSRVCE-43](https://issues.redhat.com/browse/PLNSRVCE-423)
Ran the e2e "build" suite on a testing cluster.

feat: Add field validation to the SBOM test

---

tests/build/chains.go

This task is now deprecated and should no longer be used.
https://issues.redhat.com/browse/HACBS-536
Signed-off-by: Luiz Carvalho <lucarval@redhat.com>
Arguably neither since it removes deprecated code. Marked as "new feature" since it's the least incorrect option IMO.
I tested this against my development cluster. I ran the Chains test suite in two modes: the first with the current `e2e-ec` pipeline, and the second with a modified version of `e2e-ec` that does remove the v1 task. Tests were successful (as expected) in both cases.
Once this change is merged, I'll update the `e2e-ec` pipeline to remove the v1 task which should require no changes here.

feat: Remove verify-enterprise-contract (v1) task

---

pkg/constants/constants.go
tests/build/chains.go

Currently, the Tekton Chains e2e tests run multiple Pipelines in the tekton-chains namespace. This adds clutter to that namespace which makes it harder to debug Tekton Chains issues. This commit uses a dedicated namespace for executing these tests.
https://issues.redhat.com/browse/HACBS-777
Tested this against my development cluster.

feat: Run chains tests on dedicated namespace

---

cmd/e2e_test.go
tests/build/jvm-build.go

Follow-up on a discussion about analysing jvm-build-service failure
Couple of improvements
* store logs and CR contents in files if $ARTIFACT_DIR env var is not empty
* log the content of artifactBuilds and dependecyBuilds CRs
* in case the component PipelineRun is finished (`pr.IsDone() == true`), fail immediately if its condition != succeeded
https://issues.redhat.com/browse/PLNSRVCE-533
Set up the test environment in a wrong way, for example don't create a pull secret in build-templates namespace and run
```bash
ginkgo --focus="jvm-build-service" --progress -v ./cmd -- --config-suites=/path/to/e2e-tests/tests/e2e-demos/config/default.yaml
export ARTIFACT_DIR="${PWD}/artifacts"
ginkgo --focus="jvm-build-service" --progress -v ./cmd -- …
```

fix: jvm-build: improve logging, failure handling

---

pkg/constants/constants.go
tests/build/jvm-build.go

The JVM build service tests don't actually create the config map to enable rebuilds. 
CI will test it.

fix: JVM Build Service Tests

---

tests/build/chains.go

We don't want to load policies from directories outside of the `policy` directory in the `ec-policies` repository.
https://issues.redhat.com/browse/HACBS-1125
Reproduced the problem locally and tested with this modified configuration, see https://issues.redhat.com/browse/HACBS-1125 for details.

fix: load policies from the policy directory

---

pkg/apis/github/pull_request.go
pkg/utils/gitops/controller.go
pkg/utils/has/controller.go
tests/build/build.go
tests/build/jvm-build.go
tests/e2e-demos/e2e-demo.go
tests/has/devfile_private_source.go
tests/has/devfile_source.go
tests/integration-service/integration.go

Sometimes when the test namespace is nuked and there are still some workload resources present there (pods, i.e. pipelineruns), it could take minutes until the namespace is successfully terminated, which is slowing our tests down.
If we make sure that all PipelineRun related resources (Application/Component CRs) are deleted and removed from the namespace before deleting the namespace itself, it makes the deletion process faster.

feat: wait for application/component/gitOpsDeployment CR removal

---

pkg/apis/github/repositories.go
tests/build/build.go

Previously the "PaC build test" was set up in a way that it might have created merge conflicts by updating the [README.md file](https://github.com/redhat-appstudio-qe/devfile-sample-hello-world/blob/main/README.md) if there was another instance of the same test running at the same time
This PR solves this issue by creating a new file in the branch (which name is unique for each test instance): `.tekton/<component-unique-name>-readme.md`
N/A
in CI

fix: build: avoid creating conflicts in test repo

---

magefiles/magefile.go
scripts/spi-e2e-setup.sh

SPI config is broken in our CI due to [this change](https://github.com/redhat-appstudio/service-provider-integration-operator/commit/e43868a54f6eedcc55fb17d2237cb8820168002b) (for example see [this broken periodic e2e CI job](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-redhat-appstudio-infra-deployments-pre-kcp-appstudio-e2e-deployment-periodic/1571650580286279680))
This PR should fix it
N/A
in CI

fix: SPI config

---

magefiles/magefile.go
magefiles/types.go
magefiles/webhook.go

Enable sending webhooks via centralized script (using mage)
With this change merged, webhooks should be send with every PR created for e2e-tests repo. It will also allow sending webhook with appstudio periodic e2e job once we update the job definition in openshift/release repo to use centralized scripts.
It will ignore sending webhooks for: hacbs e2e periodic job, PRs in openshift/release repo (so called rehearsal jobs)
Follow-up PR: https://github.com/redhat-appstudio/e2e-tests/pull/205
https://issues.redhat.com/browse/HACBS-988
Let's see how it works in CI

feat: centralized config for sending webhooks

---

magefiles/magefile.go
tests/build/jvm-build.go

PR jobs for components that are using centralized scripts (build-service, application-service etc) were passing the env var `E2E_TESTS_COMMIT_SHA` to the bootstrap script, whilst this env vars should be provided only for e2e-tests PRs
This PR also contains a change that makes the jvm-build suite to be skipped ([as suggested to do so in the comment](https://github.com/redhat-appstudio/e2e-tests/pull/208#issuecomment-1259449579))
N/A
in CI

fix: condition for E2E_TESTS_COMMIT_SHA env var

---

.github/workflows/build.yaml
tests/build/build.go

* fix the issue when pipelinerun was considered as successful even if it was interrupted/cancelled
* update pre-kcp tag in quay.io after PR is merged to pre-kcp branch
N/A
```bash
make local/cluster/prepare
ginkgo --label-filter="build-templates-e2e" --progress -v ./cmd -- --config-suites=/Users/psturc/work/redhat-appstudio/e2e-tests/tests/e2e-demos/config/default.yaml
```

fix: build: pipelinerun conditioncheck

---

pkg/utils/build/hacbs.go
tests/build/build.go

* Remove the sast-go and sast-java-sec-check tests
Signed-off-by: dirgim <kpavic@redhat.com>
This change removes the sast-go and sast-java-sec-check e2e tests because they've been disabled in the HACBS build pipeline.
[HACBS-1072](https://issues.redhat.com/browse/HACBS-1072)

fix: remove e2e tests for disabled SAST tasks

---

.tekton/pull-request.yaml
.tekton/push.yaml

Using single PVC for all pipeline runs of PR checks (and post merge checks) does not scale (some artifacts are not deleted for some reason). Switching to using separate PVC for each run should solve this problem.
It wasnt. Should be tested as part of the PR check.

fix: RHPD-557 use volumeClaim Template instead of persistentVolumeClaim

---

README.md
cmd/loadTests.go
go.mod
go.sum
magefiles/magefile.go
magefiles/utils.go
pkg/apis/kubernetes/client.go
pkg/framework/framework.go
pkg/utils/build/hacbs.go
pkg/utils/common/controller.go
pkg/utils/gitops/controller.go
pkg/utils/has/controller.go
pkg/utils/integration/controller.go
pkg/utils/jvmbuildservice/controller.go
pkg/utils/kcp/controller.go
pkg/utils/release/controller.go
pkg/utils/spi/controller.go
pkg/utils/tekton/controller.go
pkg/utils/tekton/matchers.go
pkg/utils/tekton/matchers_test.go
scripts/install-appstudio-kcp.sh
tests/build/build.go
tests/build/chains.go
tests/build/jvm-build.go
tests/cluster-registration/clusters.go
tests/e2e-demos/e2e-demo.go
tests/e2e-demos/multi-component.go
tests/has/devfile_private_source.go
tests/has/devfile_source.go
tests/integration-service/integration.go

It results in having 5 different clients
* 4 for kcp workspaces:
* appstudio user workspace - for running appstudio tests (i.e. for working with appstudio-specific resources - application, component CRs etc)
* hacbs user workspace - for running hacbs tests (i.e. for working with appstudio **and hacbs specific** resources - integrationtestscenarios, release CRs etc)
* appstudio workspace (redhat-appstudio) - for accessing resources specific for appstudio (appstudio controllers' deployments, configmaps, secrets etc)
* hacbs workspace (redhat-hacbs) - for accessing resources specific for hacbs (hacbs controllers' deployments, configmaps, secrets etc)
* 1 for workload cluster - for gathering resources we are not able to collect via kcp (yet), for example pods' logs from PipelineRuns
Each of …

refactor: add controllers for workspaces & ocp

---

.github/workflows/build.yaml
scripts/e2e-openshift-ci.sh
scripts/install-appstudio-e2e-mode.sh
scripts/install-appstudio.sh

infra-deployments' "pre-kcp" branch merged to "main", accordingly the pre-kcp branch of this repo was renamed to "main"
This PR removes references to "pre-kcp" branch in scripts
N/A
in CI

fix: remove references to "pre-kcp" branch

---

magefiles/magefile.go
magefiles/types.go
magefiles/utils.go

We saw [the issue](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/redhat-appstudio_infra-deployments/957/pull-ci-redhat-appstudio-infra-deployments-main-appstudio-e2e-tests/1595670670245629952#1:build-log.txt%3A65) during PR pairing when there was a PR created (by a bot) in infra-deployments from an upstream branch
It was hot-fixed by https://github.com/redhat-appstudio/e2e-tests/pull/245, but the proper solution comes with this PR
With this change, the infra-deployments org will be determined from the PR's `.head.label` value. The value is split to `RemoteName:BranchName`
Examples (see `.head.label` values):
1. [Case when the PR is created from a fork](https://api.github.com/repos/redhat-appstudio/infra-deployments/pulls/954)
1. [Case when the PR is created from an …

fix: infra-deployments PR pairing

---

scripts/spi-e2e-setup.sh

With this pr https://github.com/redhat-appstudio/infra-deployments/pull/948 spi team want to change the way how vault is deployed with infra-deployment. We would like to separate it from spi main component namespace.  In the mentioned pr we changed vault namespace from "spi-system" to "spi-vault" and we no longer want to prefix all objects. That is why the default vault pod name is also changed to the one that comes from Vault's Helm chart. 
One of the parts of https://github.com/redhat-appstudio/infra-deployments development process is the usage of https://github.com/redhat-appstudio/infra-deployments/blob/main/hack/preview.sh which is calling `scripts/spi-e2e-setup.sh`. To maintain backward compatibility at least for the time when …

chore: Allow more flexible control vault podname and namespace

---

cmd/e2e_test.go
pkg/framework/custom_junit_reporter.go

* Resolved issue where it was failing to create the intial directory cause the parent directories didn't exist
* Resolved issue where the Before/AfterSuites were being filtered out but still showing up as empty test cases in the xunit file
* Resolved issue where we weren't stat checking the correct rp preproc directory for its existence
Refer to the list above
- [X ] Bug fix (non-breaking change which fixes an issue)
Ran manually with a command like …

fix: fix some issues with rp_preproc reporting

---

magefiles/magefile.go

I had a regression where if you try to generate a template spec file in a test package directory that parent directory already existed it would fail rather than creating the spec file. 
manually
- I tested creating
- [ x] I have performed a self-review of my code

fix: fix generating template spec in a package dir that exists

---

tests/build/chains.go

There's a breaking change coming that will require changes to the e2e tests, but first it needs to be merged in infra-deployments. Disabling the tests that change to go in.
Tests will be updated and re-enabled asap.
Tested against my dev cluster running on quicklab.

fix: disable EnterpriseContract/Chains tests

---

tests/build/OWNERS

add OWNERS file to subdirectories e2e-tests/tests/build, to help Enterprise Contract develpoper and QE to have complete control over.
https://issues.redhat.com/browse/HACBS-1528

fix: add OWNERS file for build

---

tests/build/OWNERS

Add build team members to build/OWNERS

fix: Add build team members to build/OWNERS

---

tests/release/release.go

A backwards incompatible change was done in the CRD EnterprisePolicyConfig. Changes in the e2e tests and infra-deployments must happen at the same time in order to proceed. Updating one without the other causes CI to fail. Since updating both at the same time is not possible, the release tests are disabled. This was also done for the EC/Chains tests.
Once the changes are merged in infra-deployments, we can change the tests to accommodate the new CRD format and re-enable them.
https://issues.redhat.com/browse/HACBS-1525
Tested on my development environment running on quicklab.

fix: disable release tests

---

pkg/utils/has/controller.go
pkg/utils/tekton/pipelines.go
tests/build/build.go

Skip execution of full pipelineRun on direct component creation with quick workflow. The checks are still enabled for PipelineAsCode workflows.
[PLNSRVCE-958](https://issues.redhat.com//browse/PLNSRVCE-958)

feat: speed-up pipelines by skipping checks for initial runs

---

tests/has/devfile_private_source.go
tests/has/devfile_source.go

e2e-tests started to fail on:
```
[FAILED] Detected language was not java
Expected
<string>: Java
to equal
<string>: java
In [It] at: /tmp/tmp.mJACcl6qYh/tests/has/devfile_source.go:125 @ 01/02/23 15:15:36.176 
```

fix: language in devfile changed from java to Java

---

magefiles/magefile.go

* removed deprecated ginkgo flag (`--progress`) - this message is currently being printed out in every e2e test run in CI:
```
You're using deprecated Ginkgo functionality:
=============================================
--progress is deprecated .  The functionality provided by --progress was confusing and is no longer needed.  Use --show-node-events instead to see node entry and exit events included in the timeline of failed and verbose specs.  Or you can run with -vv to always see all node events.  Lastly, --poll-progress-after and the PollProgressAfter decorator now provide a better mechanism for debugging specs that tend to get stuck.
To silence deprecations that can be silenced set the following environment variable:
ACK_GINKGO_DEPRECATIONS=2.5.1
```
* added `--no-color` flag to …

fix: remove deprecated ginkgo flag (--progress)

---

tests/build/chains.go
tests/release/release.go

This change allows the e2e tests to use the latest ec-policies policy and data source. It also will pin the policy and data to a specific version.
https://issues.redhat.com/browse/HACBS-1116
This was tested by running the e2e tests on cluster-bot.

fix: update the chains and release tests to use the ec-defaults configMap

---

pkg/framework/describe.go
tests/e2e-demos/multi-component.go

When `Ordered` is used, the scenarios tests "will never be randomized and they will never run in parallel with one another, though they may run in parallel with other specs".
Since the order in which the e2e-demos-suite (nodejs, dotnet, etc...) is running is irrelevant, we can remove it in order to run them in parallel.
[RHDP-579](https://issues.redhat.com/browse/RHDP-579)
`make local/test/e2e`

test(RHDP-579): remove 'Ordered' in [e2e-demos-suite]

---

tests/release/const.go

release e2e-test happy path fails in CI , to fix issue we increased the timeout 
https://issues.redhat.com/browse/HACBS-1572

fix: increatese timeout to prevent failure in CI

---

tests/e2e-demos/e2e-demo.go

Print deployment in output when it did not become ready in time.
Related to https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/redhat-appstudio_infra-deployments/1149/pull-ci-redhat-appstudio-infra-deployments-main-appstudio-e2e-tests/1613653821949480960 where deployment timeouted and it's not possible to see what happened.

feat: e2e-demo print deployment when failed to deploy

---

README.md
cmd/e2e_test.go
magefiles/magefile.go
pkg/apis/github/repositories.go
pkg/utils/build/sbom.go
pkg/utils/has/controller.go
pkg/utils/integration/controller.go
pkg/utils/release/controller.go
pkg/utils/tekton/controller.go
templates/test_suite_cmd.tmpl
tests/build/build.go
tests/build/chains.go
tests/build/jvm-build.go
tests/e2e-demos/e2e-demo.go
tests/integration-service/integration.go
tests/release/release.go

Gikngo should display the output accumulated in `GinkgoWriter` when a scenario fails, otherwise the output is quite verbose and displayed for both failing and succeeding scenarios.

chore: disable the verbose output

---

pkg/utils/has/controller.go

Set timeout to 2 minutes for all component ready checks.
Print component in the timeout message.

fix: sync timeouts of component ready and print component

---

pkg/apis/github/git.go
pkg/utils/has/controller.go
tests/build/build.go
tests/integration-service/integration.go

Improved PaC build test to use unique branch as a base branch for PaC pull requests. Since every test instance will work with a unique branch, it should eliminate the issue seen in CI when 2 or more CI jobs could have affect each other by merging to the same (`main`) branch.
See [this discussion](https://redhat-internal.slack.com/archives/C02FANRBZQD/p1673527525131399?thread_ts=1673428220.340109&cid=C02FANRBZQD) for more info
Changes in this test depend on [these changes in build-service](https://github.com/redhat-appstudio/build-service/pull/100) being merged to infra-deployments
N/A

fix: use unique base branch in PaC build test

---

magefiles/magefile.go
magefiles/utils.go

PR pairing was not working in case an author had more than 30 branches in e2e-tests repo fork ([see the default `per_page` value for listing branches](https://docs.github.com/en/rest/branches/branches?apiVersion=2022-11-28#list-branches))
With this change we are requesting the list of PRs in e2e-tests repo (instead of author's e2e-tests repo branches) during PR pairing with the limit of 100 PRs (which should be usually sufficient)
N/A
tested locally with the openshift-ci metadata from the PR in infra-deployments (where this issue was spotted):
```bash
export JOB_SPEC='{"type":"presubmit","job":"pull-ci-redhat-appstudio-infra-deployments-main-appstudio-e2e-tests","buildid":"1614921393185492992","prowjobid":"4cd242da-9582-11ed-9f4d-0a580a812ae0","refs":{"org":"redhat-appstudio","repo":"infra …
```

fix: improve PR pairing

---

tests/e2e-demos/e2e-demo.go
tests/has/devfile_private_source.go
tests/has/devfile_source.go

e2e-demos fail on build pipelines and is not possible to collect logs because afterall remove all the resources from the cluster

fix: Do not remove resources if specs failed for debuging

---

README.md
docs/DeveloperGenerateTest.md
docs/LoadTests.md
go.mod
magefiles/installation/install.go
magefiles/installation/oauth.go
magefiles/magefile.go
pkg/constants/constants.go
pkg/framework/framework.go
pkg/utils/integration/controller.go
pkg/utils/release/controller.go
pkg/utils/tekton/controller.go
tests/build/build.go
tests/build/chains.go
tests/cluster-registration/README.md
tests/cluster-registration/clusters.go
tests/e2e-demos/config/types.go
tests/e2e-demos/e2e-demo.go
tests/e2e-demos/multi-component.go
tests/has/devfile_private_source.go
tests/has/devfile_source.go
tests/integration-service/integration.go
tests/release/release.go

- Refactored `e2e-demos.go` to use integration service for Snapshot and SnapshotEnvironmentBinding creation (for `multi-component.go` is still on standby since multi components are not working as expected)
- Fixed typos
- Uniformed "It" block content. As said [here](https://github.com/redhat-appstudio/e2e-tests/pull/259#discussion_r1043130878), as good practice, 
> "It" block content should start in lower case and be conjugated in the 3rd person singular form
[STONE-336](https://issues.redhat.com/browse/STONE-336)
`make local/test/e2e`

fix(STONE-336): refactored e2e-demos.go to use integration service for Snapshot and SnapshotEnvironmentBinding creation

---

magefiles/magefile.go
pkg/constants/constants.go
pkg/utils/has/controller.go

* Uses changes made by @psturc to pair tests update with https://github.com/redhat-appstudio/build-service/pull/103
* updated PR pairing process to allow pairing with infra-deployments PRs

fix: update build-service PaC test

---

pkg/utils/common/controller.go
tests/build/build.go
tests/integration-service/integration.go

[STONE-442](https://issues.redhat.com//browse/STONE-442) - Recently we've seen too many failures in CI related to this issue. 
Given the issue is tracked in upstream and given the rate of flakiness of this issue I'm proposing to temporarliy increase the timeout to 1 minute from original 30 seconds. 
It hasn't :-D

fix: STONE-442 Temporarily increase timeout for 'pipeline' SA creation.

---

tests/e2e-demos/config/default.yaml

Change forked repos to the original one in E2E suite. 
I still did not delete the forked repos because I want to be sure that the PR is approved and the forked repos are unnecessary
[STONE-438](https://issues.redhat.com/browse/STONE-438)
`make local/test/e2e`

test: STONE-438 change forked repos to original one in E2E suite

---

tests/build/build.go

Quay is being slow these days which is reported as incident. Increasing timeouts in build tests.

fix: increase timeout for waiting on build pipelinerun

---

pkg/framework/framework.go
pkg/utils/tekton/controller.go
pkg/utils/tekton/controller_test.go
tests/build/chains.go

bundle initialization was causing problems on staging cluster, because pipeline service account in user's namespaces don't have permissions to get buildpipelineselectors from build-service namespace:
```bash
Message: "buildpipelineselectors.appstudio.redhat.com \"build-pipeline-selector\" is forbidden: User \"system:serviceaccount:tekton-ci:pipeline\" cannot get resource \"buildpipelineselectors\" in API group \"appstudio.redhat.com\" in the namespace \"build-service\"",
```
This PR moves bundle init to the only test that is using it (and it's not run on a staging cluster)
N/A
let's see if it works in CI :P

fix: remove bundle init from tekton ctrl init

---

tests/build/chains.go

The environment is taking longer than expected to fully execute a PipelineRun. A previous run exceeded the old 10 minute timeout by about 30 seconds. This change doubles the timeout to avoid such instability in tests.

fix: bump timeout for chains pipelinerun tests

---

docs/LabelsNaming.md
tests/build/build.go
tests/build/chains.go

This PR is to add label "pipeline" to mark existing tests as part of Pipeline Service tests. 

test: adding label 'pipeline' to identify the tests that are used for Pipeline Service tests

---

tests/build/build.go

when `export COMPONENT_REPO_URLS=<repo-url-1>,<repo-url-2>,...` is specified, the check for validating that pipeline finishes successfully is not working correctly due to missing assignment of the loop variable `i` to the local variable
[(Link to a detailed explanation in ginkgo docs)](https://onsi.github.io/ginkgo/#dynamically-generating-specs)
This PR fixes it. Verified on my cluster:
```
[build-service-suite Build service E2E tests] HACBS pipelines should eventually finish successfully for component with source URL https://github.com/redhat-appstudio-qe/devfile-sample-python-basic [build, HACBS, build-templates-e2e]
/Users/psturc/work/redhat-appstudio/e2e-tests/tests/build/build.go:468
PipelineRun test-component-gfcp-8d7kr Status.Conditions.Reason: Running
...
PipelineRun …
```

fix: checking pipelines running in parallel

---

go.sum
pkg/utils/jvmbuildservice/controller.go

We've seen issues with jvm build service tests that failed on deploying the JBS cache
After looking at the real resource usage by JBS cache during test I decided to lower the default resource requests (including the PVC size - we're currently using up to ~200 MB)
Addresses https://issues.redhat.com/browse/STONEBLD-718
locally
```
ginkgo --focus "JVM Build" --v ./cmd/ -- --config-suites=$PWD/tests/e2e-demos/config/default.yaml
```

fix: override default JBS cache resource requests

---

pkg/utils/integration/controller.go
pkg/utils/util.go
tests/e2e-demos/e2e-demo.go
tests/integration-service/integration.go

- Improved `It` `finds the snapshot and checks if it is marked as successful` and `It` `checks if a snapshot environment binding is created successfully`
- Added error (in case of not finding the resource) in `GetComponent`, `GetApplicationSnapshot`, and `GetSnapshotEnvironmentBinding`
- Improved error in `GetBuildPipelineRun` and `GetIntegrationPipelineRun`
[STONE-530](https://issues.redhat.com/browse/STONE-530)
`make local/test/e2e `

fix: STONE-530 check nil pointer in "finds the snapshot and checks if it is marked as successful"

---

magefiles/magefile.go

This is needed in order to be able to execute only the release tests when e2e tests are triggered from release-service repo.
https://issues.redhat.com/browse/HACBS-1669
No testing. But I verified that the label string is the one the tests in `tests/release` set.

feat(HACBS-1669): add case for running release-service PR check

---

magefiles/magefile.go

jvm-build-service CI config was accidentally broken by a [config for another service](https://github.com/redhat-appstudio/e2e-tests/pull/353/files)
This PR fixes it
N/A
in CI

fix: release-service CI config

---

pkg/framework/framework.go
tests/e2e-demos/e2e-demo.go

We are removing pipelineruns without checking if the pipelinerun failed. Im changing the flow to use `CurrentSpecReport().NumAttempts` to retrigger a pipelinerun.
https://issues.redhat.com/browse/STONEBLD-754

fix: Fixes pipelinerun retrigger

---

pkg/utils/integration/controller.go
tests/integration-service/integration.go

- Deleted DeferCleanup in IntegrationServiceSuite
- Integration test scenario name random in order to avoid error related to "example-pass already exists" when running locally
- Updated CreateIntegrationPipelineRun (that is not being used. maybe we could delete it)
- Increased timeout from 60s to 5min
- Improved GetIntegrationTestScenarios to consider application
[STONE-604](https://issues.redhat.com/browse/STONE-604)

test: STONE-604 increase timeout and improve GetIntegrationTestScenarios to consider application

---

README.md

It turns out different labels are used nowadays.
N/A

fix: update e2e issue reporting section in README

---

magefiles/magefile.go
magefiles/utils.go

* should handle issues caused by PRs created from upstream branches (not forks), for example [PRs created by dependabot](https://github.com/redhat-appstudio/e2e-tests/pull/364)
* handle reponse statuscode >299 as error (and print the response body) during PR pairing
N/A
TBD

fix: CI setup for PRs from upstream branch

---

go.sum
tests/mvp-demo/mvp-demo.go
tests/release/e2e-test-default-bundle.go
tests/release/e2e-test-default-with-deployment.go

* fix release-service and mvp-demo tests
* follow-up on https://github.com/hacbs-contract/ec-policies/pull/358
* update release-service test to postpone the framework init to `BeforeAll` node
N/A
```
ginkgo -p --label-filter="mvp-demo,withDeployment,defaultBundle,ec" --v ./cmd -- --config-suites=$PWD/tests/e2e-demos/config/default.yaml
```

fix: EC: exclude CVE check

---

magefiles/magefile.go

When using MY_GITHUB_ORG env value different from redhat-appstudio-qe, it was creating repositories on my local github organization, so to clean up the repositories in my github org, we have to use the same MY_GITHUB_ORG environment when set.
I have tested it with setting my github org.

fix: cleanup repositories when using github org seperate from redhat-appstudio-qe

---

tests/mvp-demo/mvp-demo.go

the "untrusted" docker-build pipeline bundle had to be updated due to [latest changes in build-definitions](https://github.com/redhat-appstudio/build-definitions/pull/337)
This is just a hot fix to make e2e in https://github.com/redhat-appstudio/infra-deployments/pull/1441 pass. There will be a follow-up fix to add a functionality for building the "untrusted" bundle from the latest build templates at the beginning of the test, so the bundle is always up-to-date
N/A
```
ginkgo --label-filter="mvp-demo" --v ./cmd -- --config-suites=$PWD/tests/e2e-demos/config/default.yaml
```

fix: update mvp-demo "untrusted" build template

---

pkg/constants/constants.go
pkg/utils/has/controller.go
pkg/utils/integration/controller.go
tests/build/build.go
tests/integration-service/integration.go

* workaround an issue with checking the pipelinerun status in openshift pipelines 1.9
* issue in OSP reported [here](https://issues.redhat.com/browse/SRVKP-2880)
* the issue in the test mentioned [here](https://github.com/redhat-appstudio/infra-deployments/pull/1441#issuecomment-1458165050)
* updated `WaitForComponentPipelineToBeFinished` method to use [pr.IsDone()](https://pkg.go.dev/github.com/tektoncd/pipeline@v0.45.0/pkg/apis/pipeline/v1beta1#CustomRun.IsDone) method instead of checking the `condition.Reason` field, which could lead to issues (similar to what's mentioned above) when we move to OSP 1.9
N/A
in CI

fix: PR and TR status checks

---

pipelines/sync-hac-frontend-configs/README.md
pipelines/sync-hac-frontend-configs/cronjob.yaml
pipelines/sync-hac-frontend-configs/eventlistener.yaml
pipelines/sync-hac-frontend-configs/pipeline.yaml
pipelines/sync-hac-frontend-configs/tasks.yaml
pipelines/sync-hac-frontend-configs/triggertemplate.yaml

This adds pipeline that's intended to be deployed on internal ocp-c1 cluster.
This pipeline will run every day at 1AM. In case of failure it will send a message to #forum-stonesoup-qe slack channel.
The mirroring from private to public repo is done with approval from the internal repo owners.
https://issues.redhat.com/browse/STONE-524
I've created the pipeline in ocp-c1 cluster and tested different scenarios.
* public repo is out of date - job correctly updated this public repo
* public repo is in sync - job did nothing
* public repo has conflict - job correctly failed and sent a message to slack channel asking for human intervention.

feat: Add pipeline for syncing frontend-configs to public github.

---

README.md

Updated readme to avoid pull limits when doing docker pull during the cluster installation. When I was not using DOCKER_IO_AUTH token while running `make local/cluster/prepare` got this error `Failed to pull image "docker.io/minio/mc:RELEASE.2023-01-28T20-29-38Z": rpc error: code = Unknown desc = reading manifest RELEASE.2023-01-28T20-29-38Z in docker.io/minio/mc: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit`
Tried again after setting the DOCKER_IO_AUTH and the installation was successful.

docs: Mention docker token env variable in the readme for avoiding pull limits

---

pkg/constants/constants.go
pkg/utils/tekton/controller.go
tests/build/jvm-build.go
tests/e2e-demos/e2e-demo.go

Added an e2e-test that verifies that a rebuild of the same component uses cached dependencies from [jvm-build-service](https://github.com/redhat-appstudio/jvm-build-service/pull/199/files#diff-a298302321bbcd7e01a1f88bc21771a734b8c31b3a05c26cc70070afbba083fbR272).
I also had to add a test that checks if all artifactbuild and dependencybuilds are complete and I added a `ComponentInitialBuildAnnotationKey` constant and edited files that use it.
https://issues.redhat.com/browse/STONEBLD-61
```
ginkgo -v --label-filter "jvm-build" ./cmd -- --config-suites="$PWD/tests/e2e-demos/config/default.yaml"
```

test: added e2e test that verifies if rebuild uses cached dependencies

---

README.md
go.mod
go.sum
pkg/apis/kubernetes/client.go
pkg/utils/tekton/controller.go
tests/build/build_templates.go
tests/build/chains.go
tests/mvp-demo/README.md
tests/mvp-demo/mvp-demo.go
tests/release/e2e-test-default-bundle.go
tests/release/e2e-test-default-with-deployment.go
tests/release/release.go

The `hacbs-contract` GitHub organization has been renamed to `enterprise-contract`. This change updates the references to avoid reliance on the redirect links generated by GitHub.
https://issues.redhat.com/browse/HACBS-2004
Verified compilation works locally.

fix: HACBS-2004 update refs new EC GitHub org

---

tests/build/build_templates.go

Since the sanity checks have been renamed, temporarily remove sanity checks to unblock e2e tests
[STONEINTG-233](https://issues.redhat.com//browse/STONEINTG-233)

fix(STONEINTG-233): Remove sanity checks to unblock e2e tests

---

tests/build/build_templates.go

Enabling sbom check in the build-templates-e2e tests
Tested in the build-definitions repo PR https://github.com/redhat-appstudio/build-definitions/pull/364 enabling this in the custom image

fix: Enabling sbom check in the build-templates-e2e tests

---

magefiles/magefile.go

-  [This log ](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/redhat-appstudio_e2e-tests/418/pull-ci-redhat-appstudio-e2e-tests-main-redhat-appstudio-e2e/1643561864908509184) reports the error "Test Report unavailable because a Ginkgo parallel process disappeared". In order to mitigate this, the present PR adds ginkgo flag `--output-interceptor-mode=none` to get more additional information
[RHTAPBUGS-34](https://issues.redhat.com/browse/RHTAPBUGS-34)

test: RHTAPBUGS-34 added ginkgo flag --output-interceptor-mode=none

---

tests/build/build.go

blocker for https://github.com/redhat-appstudio-qe/devfile-sample-hello-world/pull/6156
with changes made in https://github.com/redhat-appstudio-qe/devfile-sample-hello-world/pull/6156 a component requires the `containerImage` field specified
```
ginkgo --label-filter="github-webhook" --focus "Build service E2E tests" --v ./cmd/ -- --config-suites=$PWD/tests/e2e-demos/config/default.yaml
```

fix: build: add container image field to PaC comp

---

pkg/utils/pipeline/results.go

After adding ginkgo flag `--output-interceptor-mode=none`, another test failed with this error on Apr 06 [643988124960821248](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/redhat-appstudio_e2e-tests/434/pull-ci-redhat-appstudio-e2e-tests-main-redhat-appstudio-e2e/1643988124960821248/build-log.txt).
From the `--output-interceptor-mode=none` logs, we can see that it fails on the function [sendRequest](https://github.com/redhat-appstudio/e2e-tests/blob/main/pkg/utils/pipeline/results.go#L50):
```
[1mOutput from proc 13:[0m
"level"=0 "msg"="Starting Red Hat App Studio e2e tests...\n"2023/04/06 15:19:08 failed to access Tekton Result Service with status code: 401 and
body: {"code":16,"message":"permission denied","details":[]}
```
I think it is the …

fix: RHTAPBUGS-34 return the error instead of fatal log it

---

scripts/spi-e2e-setup.sh

Since the spi-e2e-setup script is being used in infra-deployments preview script, it would be nice to be able to have the SPI providers configured with actual values using environment variables.

feat: Make SPI service providers configurable from env variables

---

tests/mvp-demo/mvp-demo.go

Due: https://github.com/redhat-appstudio/infra-deployments/pull/1725 the pac namespace has changed

fix: Point pac to openshift-pipelines namespace

---

tests/build/build.go
tests/mvp-demo/mvp-demo.go

Check for pipeline routes in pipeline-as-code or openshift-pipelines.

fix: revert e2e namespace to pipeline-as-code

---

tests/mvp-demo/mvp-demo.go

See https://redhat-internal.slack.com/archives/C02FANRBZQD/p1682614030044649 
bottom line: the Release only was progressing for short periods, per what we saw in the condition time stamps, and could sneak past the 2 second polling interval
let's just worry about the desired end state, not some short lived intermediate state
/assign @Dannyb48 
/assign @flacatus 
- [/] Bug fix (non-breaking change which fixes an issue)

fix: just check for end fail release, lose intermediate is progressing check

---

tests/release/e2e-test-push-image-to-pyxis.go

The issue in the release pyxis test was caused
by bugs in a tekton task that is part
of the push-to-external-registry pipeline.
It was fixed here:
- https://github.com/redhat-appstudio/release-service-bundles/pull/111
- https://github.com/redhat-appstudio/release-service-bundles/pull/112
The test was disabled earlier today because it was failing: https://github.com/redhat-appstudio/e2e-tests/pull/477
If it passes as part of the e2e run of this PR, that should prove that it's fixed now.

fix(RHTAPBUGS-197): enable pyxis tests again

---

tests/release/e2e-test-default-with-deployment.go
tests/release/e2e-test-push-image-to-pyxis.go

As agreed on today's HACBS Release Retrospective call, let's switch to using fixed versions when referencing pipeline bundles.
This will avoid situations like the one we hit recently in [RHTAPBUGS-197](https://issues.redhat.com//browse/RHTAPBUGS-197) when a new task was added to a new version of a pipeline and this was immediately used in e2e tests and it failed (due to a bug in the new task).
Going forward, we'll update the version in e2e tests as needed. Typically we'll have an epic for a new feature and updating e2e tests will be one of the stories there.
No testing needed - the e2e test run in this PR will verify that the tests still pass with the fixed versions.

refactor: use fixed versions for release pipeline bundles

---

Makefile
go.mod
go.sum
magefiles/magefile.go
magefiles/utils.go
magefiles/utils_test.go

Is depending on https://github.com/redhat-appstudio/image-controller/pull/22. (merged)
Added mage target CleanupQuayTags which deletes all tags older than 7 days in the `test-images` repo.
https://issues.redhat.com/browse/STONEBLD-1193
Covered by unit tests and tested in my own quay organization on mock tags.
Be advised that this will delete all the tags older than 7 days in the repository.
In order to reproduce, create some tags that you don't mind getting deleted in a repository and either:
- change your `$DEFAULT_QUAY_ORG` and `$DEFAULT_QUAY_ORG_TOKEN`
- change values of `quayOrg` and `quayOrgToken` in the [mage target](https://github.com/tnevrlka/e2e-tests/blob/tag-cleanup/magefiles/magefile.go#L197-L201)
Don't forget to change the repository in the [return …

feat: add CleanupQuayTags

---

pkg/utils/common/resource_quota.go
tests/spi/get-file-content.go
tests/spi/link-secret-sa.go
tests/spi/quay-imagepullsecret-usage.go
tests/spi/token-upload-k8s.go
tests/spi/token-upload-rest-endpoint.go

Unfortunately, we came across with `status unknown for quota error`. It seems that it is an isolated case, since it seems that it did not happen again. However, in order to mitigate this error in further failures, ResourceQuota metrics were added to the SPI tests.
[SVPI-473](https://issues.redhat.com/browse/SVPI-473)

test: SVPI-473 collect SPI ResourceQuota metrics (temporary)

---

tests/enterprise-contract/contract.go

using specific data and policy configuration bundle  to ensure task 'build-container' bundle "'quay.io/redhat-appstudio-tekton-catalog/task-buildah:0.1@sha256:c3712257615d206ef40013bf1c5c681670fc8f7fd6aac9fa4c86f7afeff627ef' always in the [acceptable bundle list.](https://github.com/enterprise-contract/ec-policies/blob/main/data/acceptable_tekton_bundles.yml)
https://issues.redhat.com/browse/RHTAPBUGS-236

fix: using specific data and policy for Release policy "out of date" test case

---

tests/mvp-demo/mvp-demo.go

During my fix in https://github.com/redhat-appstudio/e2e-tests/pull/495 there was one spot I forgot to take into account
wrt `DEFAULT_QUAY_ORG`
- [ /] Bug fix (non-breaking change which fixes an issue)
Ran mvp-demo locally

fix: sample app can be built successfully should use DEFAULT_QUAY_ORG

---

pkg/utils/common/resource_quota.go
tests/e2e-demos/e2e-demo.go
tests/e2e-demos/multi-component.go
tests/spi/get-file-content.go
tests/spi/link-secret-sa.go
tests/spi/quay-imagepullsecret-usage.go
tests/spi/token-upload-k8s.go
tests/spi/token-upload-rest-endpoint.go

Although `status unknown for quota` seemed to not appear in the past few days, it appeared yesterday, as can be checked [here](https://search.ci.openshift.org/?search=status+unknown+for+quota&maxAge=336h&context=1&type=build-log&name=.*e2e-tests.*&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=jobl). Unfortunately, in the failed testcase, the metrics were not printed. Probably because something went wrong on getting the ResourceQuota information.
So, this PR adds some improvements to the `GetResourceQuotaInfo` function in order to add more logs when there is an error getting the ResourceQuota and when the ResourceQuota does not have any available or used resources.
Furthermore, this PR also collects the metrics before the SPI tests (the current code only collects after). Since this …

test: SVPI-473 collect SPI ResourceQuota before and after + add more logs to GetResourceQuotaInfo function

---

pkg/constants/constants.go
tests/release/e2e-test-default-bundle.go

Pushing images to target repo fails due to bug in test  where service account was missing the correct secret 

fix: bug in e2e-test default bundle 

---

cmd/loadTests.go
pkg/utils/has/controller.go
pkg/utils/util.go
tests/load-tests/ci-scripts/collect-results.sh
tests/load-tests/ci-scripts/load-test.sh
tests/load-tests/ci-scripts/setup-cluster.sh
tests/load-tests/run.sh

This PR:
* Introduces CI scripts for load test
* Fixes the component names for tenant users that are now generated by `ComponentDetectionQuery`s
* Modifies the check for existence gitops repo to not use the GH token to avoid token's primary rate limits being quickly spent.
[RHTAP-668](https://issues.redhat.com/browse/RHTAP-668)
Part of [rehearsal tests](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/37577/rehearse-37577-periodic-ci-redhat-appstudio-e2e-tests-main-load-test-concurrent/1658147748395880448) of https://github.com/openshift/release/pull/37577

feat(RHTAP-668): Introduce CI scripts for load test

---

tests/mvp-demo/mvp-demo.go
tests/utils.go

An example of failing fast when possible, and always providing useful debug messages so that users unfamiliar with your test have a starting point for searching the must-gather data, and don't have to start reading the e2e-test code to see where to start triage
Ideally QE start creating additional stories off of https://issues.redhat.com/browse/RHTAP-914 to apply these patterns across the board.
https://issues.redhat.com/browse/RHTAP-915
- [/] Bug fix (non-breaking change which fixes an issue)
ran e2e's against my local cluster

fix: RHTAP-912: fail Eventually ginkgo clauses on terminal failure states; all ginkgo 'Should' clauses should have debug info including keys

---

pkg/utils/build/task_results.go
tests/build/build_templates.go
tests/mvp-demo/mvp-demo.go

+ included taskrun validation in build templates e2e and mvp-demo
[RHTAPBUGS-207](https://issues.redhat.com//browse/RHTAPBUGS-207)
```
ginkgo  --focus "HACBS pipelines" --v ./cmd/ -- --config-suites=$PWD/tests/e2e-demos/config/default.yaml
```

fix: refactored taskrun results validation

---

pkg/utils/tekton/pipelines.go
tests/enterprise-contract/const.go
tests/enterprise-contract/contract.go

add case of cmd 'ec-cli validate' accepts a list of image references to validate images, signature and attestationa
https://issues.redhat.com/browse/HACBS-1837
```
$ ./bin/e2e-appstudio --ginkgo.focus-file tests/enterprise-contract/contract.go --ginkgo.vv
...
...
Ran 3 of 331 Specs in 36.731 seconds
SUCCESS! -- 3 Passed | 0 Failed | 5 Pending | 323 Skipped
PASS
```

feat: ec validate can take mulitiple images as input

---

OWNERS

some people listed in [CODEOWNERS file](https://github.com/redhat-appstudio/e2e-tests/blob/5a05bc2d057c2c0de09f11e998337b0e906c70e8/.github/CODEOWNERS#L8) and people with write permissions to the repo are not able to approve PRs via the usual prow workflow (i.e. by adding the `/approve` comment), because they are not listed in OWNERS file
N/A
-

chore: added collaborators to root OWNERS file

---

pkg/constants/constants.go
tests/build/chains.go
tests/enterprise-contract/contract.go

Although test cases run serially within a test suite, the test suites run in parallel to each other. This caused random issues in tests that rely on the default EnterpriseContractPolicy across different test suites if those test suites use the same test namespace.
This change modifies ChainsSuite and EnterpriseContractSuite to use a unique namespace for executing their tests.
https://issues.redhat.com/browse/HACBS-2259

fix: ensure chains and EC suites run in unique ns

---

pkg/constants/constants.go
pkg/framework/framework.go
pkg/sandbox/keycloak.go
pkg/sandbox/sandbox.go

* If a username passed to a `NewFramework()` method has length more than 20 characters, it is shortened by a toolchain controller, but the resulting value is not picked up by e2e-tests framework. That issue was found while investigating the CI failure for [this change](https://github.com/redhat-appstudio/e2e-tests/pull/541/commits/3a73fe9a3f0a62bc4f297a1734fc1fb407304890). This PR should address the issue [here](https://github.com/redhat-appstudio/e2e-tests/compare/main...psturc:update-framework-init?expand=1#diff-d6d998723333eefe28e969421f10d0d6792ea384314d77c99dc7d6b5edc1a347R225)
* added a [warning message](https://github.com/redhat-appstudio/e2e-tests/compare/main...psturc:update-framework-init?expand=1#diff-b247c3614709818eed09ee97e1d6988bd26d0d11e7ad8269143bb84745e5b273R54) about …

fix: framework init, log more info during fw init

---

pkg/utils/integration/controller.go
pkg/utils/release/controller.go

A new feature in the Release service relies on an author label existing in the ReleasePlan for the automated usecase. This is done via webhooks, so the author label should be manually added to the ReleasePlan CRs.

feat(HACBS-2127): add author to ReleasePlan labels

---

pkg/utils/tekton/controller.go
tests/spi/get-file-content.go
tests/spi/link-secret-sa.go
tests/spi/quay-imagepullsecret-usage.go
tests/spi/token-upload-k8s.go
tests/spi/token-upload-rest-endpoint.go

We came across a [CI job](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/redhat-appstudio_e2e-tests/527/pull-ci-redhat-appstudio-e2e-tests-main-redhat-appstudio-e2e/1663454847149543424) that failed on getting SPIAccessCheck and SPIFileContentRequest right after its creation. It seems to report `504 Gateway Time-out` in both tests.
Since this error is being targeted in the `Eventually`, this PR proposes getting the resource after the resource creation in the same `It` to be more clear to read the error.
[RHTAPBUGS-354](https://issues.redhat.com/browse/RHTAPBUGS-354)
[RHTAPBUGS-355](https://issues.redhat.com/browse/RHTAPBUGS-355)
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details …

test: spi tests - get resource after resource creation

---

OWNERS

To be added to the [openshift/release: ci-operator/config/redhat-appstudio/e2e-tests/OWNERS](https://github.com/openshift/release/blob/master/ci-operator/config/redhat-appstudio/e2e-tests/OWNERS) and [openshift/release: ci-operator/jobs/redhat-appstudio/e2e-tests/OWNERS](https://github.com/openshift/release/blob/master/ci-operator/jobs/redhat-appstudio/e2e-tests/OWNERS) I should be in the root OWNERS file of this repo.

chore: add pmacik to root OWNERS file

---

cmd/loadTests.go
tests/load-tests/ci-scripts/max-concurrency/collect-results.sh
tests/load-tests/ci-scripts/max-concurrency/load-test.sh
tests/load-tests/run-max-concurrency.sh

[RHTAP-970](https://issues.redhat.com/browse/RHTAP-970)
Tested in OpenShift CI - https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/39960/rehearse-39960-periodic-ci-redhat-appstudio-e2e-tests-main-load-test-max-concurrency-basic/1664662821641654272

feat(RHTAP-970): Create a load test that tracks max concurrency with builds below given threshold

---

pkg/utils/integration/controller.go
pkg/utils/release/controller.go

The StandingAttribution label should have been set in ReleasePlans, not the Author label.

fix: set StandingAttribution label in ReleasePlans

---

pkg/utils/has/controller.go

Multiple controller are updating a component at the same time. This PR use retryOnConflict method to update component resources.
[RHTAPBUGS-398](https://issues.redhat.com//browse/RHTAPBUGS-398)

fix: RHTAPBUGS-398: RetryOnConflict when update a component

---

pkg/constants/constants.go
tests/release/e2e-test-push-image-to-pyxis.go

This will update the release tests to use the latest versions of the release and push-to-external-registry pipelines. The new versions use the new failOnEmptyResult parameter when using the apply-mapping task.
As a result, when the mapping results in an empty component list, the apply-mapping task will fail in the pipeline. This should make debugging of failed e2e tests a little more convenient - this is something that happened repeatedly in the last month and it's often not easy to realize what's going on - until now, the typical symptom would be a failed EC test - but the rest of the pipeline would happily pass. …

feat(HACBS-2222): update release pipeline versions

---

tests/integration-service/integration.go

Deleted a duplicated code in the test and used Gomega's `Succeed()` matcher here since its more concise and does the same job as `Expect(err).NotTo(HaveOccurred())`.
From the Ginkgo docs:

fix: Remove duplicated code and use "Succeed()" for concise code

---

README.md
magefiles/installation/install.go
pkg/constants/constants.go
pkg/utils/build/image.go
pkg/utils/build/sbom.go
tests/build/build.go

Created two new e2e-tests for checking if pruning labels are set / not set correctly. Added new pkg image.go with common functions for working with images 
[STONEBLD-1210](https://issues.redhat.com/browse/STONEBLD-1210)
Tested locally with `./bin/e2e-appstudio --ginkgo.label-filter="github-webhook" --ginkgo.v`

feat: add pruning e2e-test

---

tests/mvp-demo/mvp-demo.go

* Bundles are deprecated and are replaced by resolvers
Remove the check for bundle to unlock migration to Tekton resolvers.
[STONEINTG-401](https://issues.redhat.com//browse/STONEINTG-401)

fix(STONEINTG-401): remove check for integration bundle

---

tests/build/chains.go

The chains-ca-cert Secret is no longer needed. See https://issues.redhat.com/browse/HACBS-2216. This change removes the test that verifies it exists, so we can actually remove it from the cluster in https://github.com/openshift-pipelines/pipeline-service/pull/673.
https://issues.redhat.com/browse/HACBS-2216
Tested against my dev cluster.

feat(HACBS-2216): Removem chains-ca-cert support

---

tests/build/build.go

`Label(buildTemplatesTestLabel)` belongs only to build-templates.go test file. This was probably a copy-paste issue.
N/A
N/A

fix: build: remove inappropriate label

---

pkg/constants/constants.go
tests/release/e2e-test-default-with-deployment.go
tests/release/e2e-test-push-image-to-pyxis.go

These new pipeline versions take the verify-ec-task bundle version from the enterprise contract configmap instead of hardcoding it

chore(HACBS-2304): bump release pipeline versions

---

cmd/loadTests.go
docs/LoadTests.md
pkg/constants/constants.go
pkg/utils/util.go
tests/load-tests/ci-scripts/load-test.sh
tests/load-tests/ci-scripts/max-concurrency/load-test.sh
tests/load-tests/run-max-concurrency.sh
tests/load-tests/run.sh

With #482 the `redhat-appstudio-registry-pull-secret` secret is created (and set to the value of `QUAY_TOKEN` variable) by the e2e framework automatically, so when the load test attempts to create the secret, it fails for "already exist" reason.
This PR:
* Removes the step to create `redhat-appstudio-registry-pull-secret` secret
* Removes use of the `DOCKER_CONFIG_JSON` environment variable that was used to set the above secret
In OpenShift CI: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/40331/rehearse-40331-periodic-ci-redhat-appstudio-e2e-tests-main-load-test-max-concurrency-basic/1669345903418281984

fix(load-test): Stop creating redhat-appstudio-registry-pull-secret in user namespace

---

pkg/utils/release/controller.go
tests/release/e2e-test-default-bundle.go
tests/release/e2e-test-default-with-deployment.go
tests/release/e2e-test-push-image-to-pyxis.go
tests/rhtap-demo/rhtap-demo.go

A new ClusterRole was created within the Release Service to allow the Release PipelineRuns to access Custom Resources in the dev and managed namespaces. This commit adds RoleBindings for it.

feat(HACBS-2310): add RoleBindings for Release PLR ClusterRole

---

pkg/constants/constants.go
pkg/utils/has/controller.go
tests/build/build.go
tests/rhtap-demo/rhtap-demo.go

This PR changes e2e tests expectations regarding Component image repository lifecycle. With [new behavior](https://github.com/redhat-appstudio/image-controller/pull/34), Image Controller always deletes image repository of the Component, when the Component gets deleted.
Annotation `image.redhat.com/delete-image-repo` is deprecated and will have no effect.
[STONEBLD-1340](https://issues.redhat.com/browse/STONEBLD-1340)

test: Change tests according to image controller always deletes component image repository

---

tests/release/e2e-test-default-bundle.go
tests/release/e2e-test-default-with-deployment.go

There was an [update](https://github.com/redhat-appstudio/application-service/pull/351) of component name creation on CDQ. Now, the random chars are only appended if the component name already exists in the namespace. If not, it will have the predicated name.
This affected the creation of a new branch on `e2e-test-default-bundle` and `e2e-test-default-with-deployment` since the branch name input of  `CreateRef` should be a random branch name, which is not the current case of the tests now:
`error when creating a new branch 'dc-metro-map' for the repo 'strategy-configs'`
So, this PR changes the branch name input on `CreateRef` for `e2e-test-default-bundle` and `e2e-test-default-with-deployment` to address it as random.
[RHTAPBUGS-440](https://issues.redhat.com/browse/RHTAPBUGS-440)
Please …

test: RHTAPBUGS-440 change branch name input on CreateRef in e2e-test-default-bundle and e2e-test-default-with-deployment tests

---

pkg/utils/build/quay.go
pkg/utils/has/components.go

This PR addresses story: https://issues.redhat.com/browse/STONEBLD-1183 and also added a missing error checking when component is recreated.
https://issues.redhat.com/browse/STONEBLD-1183
Tested locally.

fix: Check image controller annotations in component when image generate is set

---

pkg/utils/tekton/controller.go
pkg/utils/tekton/controller_test.go

With HACBS-2209, Tekton Chains will only produce a single attestation, for the PipelineRun. This is expected. This change updates the tests to no longer assert that the attestation image has 2 layers. This is an implementation detail anyways. It is better asserted indirectly by testing the actual functionality of Enterprise Contract.
Note that this assertion has failed before due to a different issue which is explained in the second comment in [RHTAPBUGS-375](https://issues.redhat.com//browse/RHTAPBUGS-375). It is expected that this patch will also address that issue by making the originaly reported underlying problem more obvious. There the PipelineRun failed for a different reason.
https://issues.redhat.com/browse/RHTAPBUGS-375
Please describe the tests that you ran to verify your …

fix: Do not require attestations to have 2 layers

---

tests/release/const.go
tests/release/e2e-test-default-with-deployment.go

There is a recent [PR](https://github.com/redhat-appstudio/e2e-tests/commit/a0a9bfd558f9dfb56dd46c2095ec8485c4391985#diff-0ef984b13662fe17a6a6a36aadf17220299b09e9af0e7e59b3f9ebe6f2dfd2e8R226) that changed the timeout on _It Spec_ `tests a Release CR reports that the deployment was successful`, from 10 to 5, which sometimes is not enough for the release to be marked as deployed (more details, see https://github.com/redhat-appstudio/e2e-tests/pull/601).
So, this PR reverts it, since some jobs are failing because the timeout is not enough. Example:
job: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/redhat-appstudio_e2e-tests/619/pull-ci-redhat-appstudio-e2e-tests-main-redhat-appstudio-e2e/1677202396054294528#1:build-log.txt%3A1016
logs: …

test: fix timeout

---

tests/release/e2e-test-default-with-deployment.go

We commented the AfterAll cleanup method for test `e2e-test-default-with-deployment.go` due to resources was not deleted by the finalizer of k8s, it was solved in [RHTAPBUGS-409](https://issues.redhat.com/browse/RHTAPBUGS-409).
was tested locally and it's working as expected.

fix: uncomment the AfterAll method due to the fix of RHTAPBUGS-409.

---

pkg/utils/release/controller.go
pkg/utils/release/sbom.go
tests/release/const.go
tests/release/e2e-test-push-image-to-pyxis.go

Pyxis containerImage object will no longer
contain the embedded contentManifestComponent objects.
If we really still wanted to check that there is at least one component in Pyxis, we could use graphql and edges to get this information.
But it's probably ok for us to just check that a manifest is included in the image - that still confirms that upload_sbom script did something. If the upload_sbom script didn't run, the manifest id would be empty.
https://issues.redhat.com/browse/HACBS-2375
I wrote a simple go program where I copied the `GetPyxisImageByImageID` function and ran it on two different images - one with a linked manifest object and one without it. That way I was able to confirm that when the manifest object is not there, the id will be an empty string in the resulting struct …

refactor(HACBS-2375): adjust release test to pyxis changes

---

go.mod
go.sum
pkg/utils/has/componentdetectionqueries.go
tests/e2e-demos/e2e-demo.go

* https://issues.redhat.com/browse/RHTAPBUGS-441 was fixed -> now it's possible to create multiple components via CDQ from the same Git repository in parallel using `GenerateComponentName: true` field
* updated `application-api` dependency in order to allow using the new `GenerateComponentName` field
[RHTAPBUGS-441](https://issues.redhat.com//browse/RHTAPBUGS-441)
```
ginkgo -p --focus "create an nodejs application" --v ./cmd/ -- --config-suites=$PWD/tests/e2e-demos/config/default.yaml
```

fix: remove workaround for creating multiple comp

---

magefiles/magefile.go

It looks like that as part of a refactor, my fix from https://github.com/redhat-appstudio/e2e-tests/pull/495 was lost as logic was moved to the magefile stuff.
This is adding it back, to allow for running the e2e's locally using an individual's quay repos instead of the official appstudio e2e ones.
- [ /] Bug fix (non-breaking change which fixes an issue)
- [/ ] I have performed a self-review of my code

fix: add back ability to override the quay repo used for push/pull images

---

pkg/constants/constants.go
tests/release/e2e-test-default-with-deployment.go
tests/release/e2e-test-push-image-to-pyxis.go

[HACBS-2290](https://issues.redhat.com//browse/HACBS-2290) is about passing the snapshot object reference instead of as a json string due to character size limits. This commit updates the release pipelines to versions to accept the object reference instead of json strings.

feat(HACBS-2290): bump release pipeline versions

---

tests/enterprise-contract/contract.go

These tests were skipped when running tests in infra-deployments from[1]:
```
exec: ginkgo "-p" "--output-interceptor-mode=none" "--timeout=90m" "--output-dir=/logs/artifacts" "--junit-report=e2e-report.xml" "--label-filter=e2e-demo,rhtap-demo,spi-suite,integration-service,o11y,ec,byoc" "./cmd" "--" "--config-suites=/tmp/tmp.NlhpfTvYoJ/tests/e2e-demos/config/default.yaml" "--generate-rppreproc-report=true" "--rp-preproc-dir=/logs/artifacts"
```
Notice that `enterprise-contract` label is not included but `ec` label is.
This leads to issues like on [2] run going undetected.
So this changes the label to `ec` so the test suite runs on changes to infra-deployments.
[1] https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/redhat-appstudio_infra-deployments/2122/pul …

fix: `ec` label instead of `enterprise-contract`

---

tests/build/build_templates.go

With the addition of Cachi2 components in the final SBOM, some components will no longer have a version in it. Currently, the check that covers SBOM generation requires all components to have non-empty version.
Example of a Cachi2 reported component without a version: Golang std packages
```
{
"name": "vendor/golang.org/x/text/unicode/bidi",
"properties": [
{
"name": "cachi2:found_by",
"value": "cachi2"
}
],
"purl": "pkg:golang/vendor/golang.org/x/text/unicode/bidi?type=package",
"type": "library"
}
```
Related PRs:
https://github.com/redhat-appstudio/build-definitions/pull/481
https://github.com/containerbuildsystem/cachi2/pull/223
[STONEBLD-1357](https://issues.redhat.com//browse/STONEBLD-1357)
This PR removes a single line that's causing the CI for …

test: Removes the check requiring a SBOM component to have a version

---

tests/rhtap-demo/rhtap-demo.go

With https://issues.redhat.com/browse/RHTAPBUGS-356 resolved, these tests should be running.
Ref. https://issues.redhat.com/browse/HACBS-2402
I'll let the CI do it's work...

chore: reinstate skipped tests

---

tests/load-tests/run-max-concurrency.sh

Currently, in `max-concurrency` scenarios the sequence of the number of threads starts with number 1 and then it is increased by 1 until the thread number reaches `MAX_THREADS` value or the `THRESHOLD` value for max pipeline run time is exceeded.
With the current performance of RHTAP the max concurrency in CI the max concurrency is not reached before the [job to execute the test](https://prow.ci.openshift.org/job-history/gs/origin-ci-test/logs/periodic-ci-redhat-appstudio-e2e-tests-main-load-test-max-concurrency-basic) times out (8 hours) - which causes the job to fail.
We need to increase the step in thread count sequence to be able to reach higher concurrency sooner.
This PR:
* Adds possibility to configure the size of the step in sequence via `MAX_CONCURRENCY_STEP` (with the default …

feat(load-test): Make it possible to specify thread increase step in max-concurrency scenarios

---

tests/spi/remote-secret.go

https://github.com/redhat-appstudio/remote-secret/pull/57 will break the tests since it will introduce a new logic. Deploying to different namespaces is going to be disallowed by default. So, in order to not break the tests, we need to skip them provisory and update them after merging the new logic on remote secret repo side

test: skip remote secret test

---

tests/load-tests/ci-scripts/max-concurrency/collect-results.sh
tests/load-tests/cluster_read_config.yaml

Curious about scheduling delays in our CI based testing, and if these upstream tekton / pipeline service metrics help expose them.

chore: add some additional metrics to perf wg CI based testing collections

---

tests/load-tests/ci-scripts/setup-cluster.sh

Currently `infra-deployments` that the load test uses to install RHTAP in CI is always based on upstream `main` branch.
This PR:
* Modifies the `setup-cluster.sh` CI script to take variables `INFRA_DEPLOYMENTS_ORG` and `INFRA_DEPLOYMENTS_BRANCH` from environment set by the CI jobs to the respective org and branch (e.g. https://github.com/openshift/release/pull/41722)
* Introduces `TWEAK_INFRA_DEPLOYMENTS` variable to only touch infra deployments with load-test specific changes when that variable is set to `true`.
[RHTAP-1304](https://issues.redhat.com/browse/RHTAP-1304)

feat(RHTAP-1304): Make it possible to override infra-deployments org and branch for load test

---

pkg/utils/build/task_results.go

As part of [HACBS-2401](https://issues.redhat.com/browse/HACBS-2401), the label-check is no longer included in the build pipelines. This change updates the tests to no longer check for its presence.
https://issues.redhat.com/browse/HACBS-2401

feat(HACBS-2401): Remove label-check task

---

pkg/apis/github/git.go
tests/rhtap-demo/rhtap-demo.go

Tests sometime fail in BeforeAll in rhtap-demo.go on "branch not found" right after the branch was created & tests tries to create file there. This PR adds wait for the branch to actually exist (GH GetRef() returns true). This should hopefully resolve [RHTAPBUGS-536](https://issues.redhat.com//browse/RHTAPBUGS-536)
https://issues.redhat.com/browse/RHTAPBUGS-536
Run locally few times. Worked fine.

fix: RHTAPBUGS-536 Wait for branch to exist

---

tests/spi/quay-imagepullsecret-usage.go

The current timeout is 1min when checking if taskrun is complete, which can not be enough, as is the example of [this job](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/redhat-appstudio_infra-deployments/2172/pull-ci-redhat-appstudio-infra-deployments-main-appstudio-e2e-tests/1686352720824373248#1:build-log.txt%3A1015) (it took around 2min). This PR increases it to 5min to cover edge cases like this.
[RHTAPBUGS-541](https://issues.redhat.com/browse/RHTAPBUGS-541)

fix: RHTAPBUGS-541 increasing timeout when checking if taskrun is complete

---

.github/workflows/PR.yaml
.github/workflows/build.yaml
.github/workflows/conventional-commits.yaml

Github Actions give the following warnings about deprecating node12 based actions:
```
* This version of the CodeQL Action was deprecated on January 18th, 2023, and is no longer updated or supported. For better performance, improved security, and new features, upgrade to v2. For more information, see https://github.blog/changelog/2023-01-18-code-scanning-codeql-action-v1-is-now-deprecated/
* Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2, actions/setup-go@v2. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
```
This PR:
* Updates version of actions that use `node12` to versions that use at least `node16` …

fix(github-actions): bump deprecated versions of GH actions

---

.tekton/pull-request.yaml
.tekton/push.yaml

Recently the RHTAP CI check in the [PRs started failing](https://github.com/redhat-appstudio/e2e-tests/pull/662/checks?check_run_id=15575405866) with a similar error as shown below:
```
Error retrieving pipeline for pipelinerun tekton-ci/integration-service-pull-request-8mdtv: failed to get pipeline:
error requesting remote resource: error getting "bundleresolver" "tekton-ci/bundles-2eaa2963a940eb40a21b75a6baacc12b":
could not find object in image with kind: Task and name: docker-build
```
This is due to some recent changes in the PipelineRun definition in the tekton-ci, where we'd need to specify the bundles inside a resolver format and also specifically mention the `kind: Pipeline` (by default it would pick up the value `Task` and that explains the error seen above).
You can read the …

chore(ci): add workaround for new OSP ver

---

tests/build/build_templates.go

After updating syft, this testcase is failing as it is counting only purls of type "library". But currently syft generates purls also for type "application". For example:
"type": "application",
"name": "python",
"version": "3.11.1",
"cpe": "cpe:2.3:a:python_software_foundation:python:3.11.1:*:*:*:*:*:*:*",
"purl": "pkg:generic/python@3.11.1",

fix: count the application type purls in test 

---

pkg/constants/constants.go
pkg/utils/tekton/controller.go
tests/build/chains.go
tests/enterprise-contract/contract.go

Tekton Chains is now managed as part of the OpenShift Pipelines operator. As such, its resources now reside in the `openshift-pipelines` namespace instead of `tekton-chains`.
This also removes some of the infrastructure checks performed by the e2e tests. This is deemed too low-level for these tests. Instead, let's continue to use the e2e tests to test the expected behavior and not care too much about the implementation details.
https://issues.redhat.com/browse/HACBS-2400

feat(HACBS-2400): Chains secret from OpenShift Pipelines

---

tests/enterprise-contract/contract.go

The tests may fail if the error message exceeds a certain length which causes a multi-line string to be used, for example:
```yaml
msg: |-
No image attestations found matching the given public key
```
Prior to this change, the tests expect it to be:
```yaml
msg: No image attestations found matching the given public key
```
With this change, either format matches.

fix: Improve error message matching

---

tests/load-tests/ci-scripts/collect-results.sh
tests/load-tests/ci-scripts/load-test.sh
tests/load-tests/ci-scripts/max-concurrency/load-test.sh
tests/load-tests/ci-scripts/user-prefix.sh

[RHTAP-1416](https://issues.redhat.com/browse/RHTAP-1416)

fix(RHTAP-1416): Add PR number to USER_PREFIX to avoid naming collisions while running multiple PRs in parallel

---

tests/build/build.go
tests/spi/access-control.go

Unfortunately, some jobs are failing with an empty buffer string when the guest user makes a POST request to `spifilecontentrequests`, from within a pod.
In order to investigate it (since I was not able to reproduce it locally yet), this PR changes the order of the assertions and improves it to check first if the `errBuffer` is empty in order to get more information, in case it fails.
[RHTAPBUGS-556](https://issues.redhat.com/browse/RHTAPBUGS-556)

test: RHTAPBUGS-556 check first errorBuffer before buffer on spi access control e2e test

---

cmd/loadTests.go
tests/load-tests/run-max-concurrency.sh
tests/load-tests/run-stage.sh
tests/load-tests/run.sh

Currently, the progress bars are shown for deployments, integration tests and pipelines is shown and handled even when the load test is not set to wait for those.
With this PR the progress bars are only handled and shown for those phases, that are enabled.
That in case of max-concurrency scenario (that has the deployments and integration tests disabled) leads to failures and timeouts.

fix(load-test): Do not show respective progress bars when not waiting for pipelines, deployments or integration tests

---

cmd/loadTests.go
pkg/utils/has/applications.go
pkg/utils/has/componentdetectionqueries.go

Add StageCleanupSingle function to cleanup component and CDQ per user
Figure out how to properly do a cleanup in Stage
We noticed that StageCleanup(selectedUsers) after the load-test didn't clean the user's CDQ so
I have fixed the StageCleanup function executed after the load-tests, tht function delete all the user's applications and
CDQs in the user's namespace
Dependencies:
1. framework.AsKubeDeveloper.HasController.DeleteAllApplicationsOneByOneInASpecificNamespace - 
a new function in pkg/utils/has/applications.go
2. framework.AsKubeDeveloper.HasController.DeleteAllComponentDetectionQueriesOneByOneInASpecificNamespace - 
a new function I've created in pkg/utils/has/componentdetectionqueries.go
Both functions were needed because the deletecollection verb for the application, component, …

feat(RHTAP-1337): Properly cleanup in stage

---

cmd/loadTests.go
tests/load-tests/ci-scripts/collect-results.sh
tests/load-tests/ci-scripts/load-test.sh
tests/load-tests/ci-scripts/max-concurrency/collect-results.sh
tests/load-tests/run-max-concurrency.sh
tests/load-tests/run-stage.sh
tests/load-tests/run.sh

Currently, the output files generated by the load test (such as `load-tests.json`) are always stored under `tests/load-tests` directory.
This PR introduces `OUTPUT_DIR` env variable that can be used to specify the directory where those files are stored instead. That is useful in CI and makes it easy to [share the output files between steps](https://docs.ci.openshift.org/docs/architecture/step-registry/#sharing-data-between-steps) of the CI workflow.
That is necessary for [splitting the load test run and result collection in CI](https://github.com/openshift/release/pull/42332) each being part of a different step of the workflow (load-test in `test` step and collect-results in `post` step.
The default value of the `OUTPUT_DIR` is `.` which corresponds to the current behavior for backwards …

feat(RHTAP-1415): Make it possible to specify output directory for load test

---

tests/build/build_templates.go

When running selected test with label `build-templates-e2e` it was failing while deleting ProxyPlugin in the AfterAll block, since we were creating ProxyPlugin in the It block. Moved it to BeforeAll so that the running tests with `build-templates-e2e` won't fail.

fix: Moved the proxyplugin creation to BeforeAll section

---

tests/spi/quay-imagepullsecret-usage.go

this typo introduced in [this PR](https://github.com/redhat-appstudio/e2e-tests/pull/558/files#diff-187fb95c8b52e8469e782ef42317b23127605df981ac319badb89aaf5b5be682R211) resulted in hundreds of repositories being created in quay.io org account 🤦  
I'm currently cleaning up these repositories from quay.io. After merging this PR (and rebasing other PRs) no other repos like this should get created anymore
N/A
N/A

fix: spi: repository name typo

---

pkg/constants/constants.go
tests/rhtap-demo/rhtap-demo.go

Use build.appstudio.openshift.io/request instead of the depracated appstudio.openshift.io/pac-provision
[STONEBLD-1315](https://issues.redhat.com//browse/STONEBLD-1315)

fix: replace deprecated annotations 

---

pkg/utils/tekton/controller.go
pkg/utils/tekton/pipelines.go
tests/build/build_templates.go
tests/build/chains.go
tests/enterprise-contract/const.go
tests/enterprise-contract/contract.go

- tekton.VerifyEnterpriseContract now has a top-level app.SnapshotSpec (Snapshot) field
- two new helper methods on tekton.VerifyEnterpriseContract: - WithComponentImage - AppendComponentImage
- tekton.VerifyEnterpriseContract.Bundle renamed to tekton.VerifyEnterpriseContract.TaskBundle
- tekton.PipelineRunGenerator returns an error from Generate method
- SSLCertDir set to a fixed value, less repetition this way
- commented out code removed
Ref. https://issues.redhat.com/browse/HACBS-2200
Run tests against quickcluster instance

refactor: tekton.VerifyEnterpriseContract

---

tests/release/const.go
tests/release/e2e-test-default-bundle.go

In [HACBS-2472](https://issues.redhat.com/browse/HACBS-2472) we realized a gap in the testing putting the Release pipeline at risk if the `verify-enterprise-task` changes in an incompatible way with the Release pipeline.
This adds a coverage to test that `verify-enterprise-task` is included in the Release PipelineRun and that it has succeeded.
The success is assumed by the release PipelineRun succeeding, though there is no check to make sure that `verify-enterprise-task` is included and that it succeeds individually.
Currently it is not possible to ignore errors from Tasks in PipelineRuns so this safeguards in case TEP-0050 gets implemented.
[1] https://github.com/tektoncd/community/blob/fe0c2bbedb0754cd6b4352eab5d344683a73c296/teps/0050-ignore-task-failures.md
Ref. …

feat: test that EC Task is run in Release pipeline

---

pkg/constants/constants.go
pkg/utils/tekton/controller.go
pkg/utils/tekton/pipelines.go
tests/build/chains.go

The EC pipelines from the build-definitions repository are used by the auto-created IntegrationTestScenario. This adds test coverage to those Tekton pipelines.
By default it tests the pipelines from the main branch of the build-definitions repo. The branch as well as the repository url can be overwritten via environment variables. This will be used in the future to test pull requests in the build-definitions repository.
Tested with clusterbot.

feat: Test EC pipelines

---

pkg/apis/github/pull_request.go
tests/build/chains.go

This change allows the EC pipeline tests to be executed against the source of a pull request in the build-definitions repo. This allows us to run these tests as part of the CI of the build-definitions repo in order to catch issues in the EC pipelines.
Cluster in resourcehub.

feat: Allow EC pipeline tests from fork PR

---

tests/build/chains.go

The EC pipelines tests are expected to be used by the build-definitions CI. When it runs there, it runs directly on the prod cluster. The tests in `tests/enterprise-contract/contract.go` don't work with that setup. Also, they are not really related to changes in build-definitions.
This commit adds a new label, `ec-pipelines-e2e`, so the build-definitions CI can include just the relevant tests.
Dev cluster.

fix: use custom label for ec pipelines

---

pkg/constants/constants.go
tests/release/e2e-test-default-with-deployment.go
tests/release/e2e-test-push-image-to-pyxis.go

This test was disabled because of a bug
in release service that is being fixed in
https://github.com/redhat-appstudio/release-service/pull/232
This reverts commit de77bb5cbf22788597d55111ed7a04ed6ba20d2b.
https://issues.redhat.com/browse/RHTAPBUGS-560
A successful e2e run in https://github.com/redhat-appstudio/release-service/pull/232 will confirm this is fixed.

chore: enable release-pyxis test again

---

tests/build/chains.go

Need to exclude the test that verifies the Chains controller is running because the build-definitions CI doesn't have access to do so.
Dev cluster in resourcehub

fix: move ec-pipelines label

---

tests/build/build_templates.go
tests/build/chains.go

The tests for the EC pipelines are meant to, mostly, be executed from the build-definitions CI. That runs directly against prod. As such, the user has no access to things like the quay.io secret. The previous iteration of these tests relied on such access in order to run a pipeline for a test repo.
This change makes it so an Application is used to build the test repo. This removes any sort of access issues. Also, this removes the need to build a specific test image just for these tests. Instead, the same test image is used for all the tests.
On a dev cluster.

fix: move EC pipelines tests to build-templates

---

tests/spi/access-control.go

Unfortunately, some jobs are failing with an empty buffer string when the guest user makes a POST request to `spifilecontentrequests`, from within a pod. The "interesting aspect" is that returns no error. 
I was not able to reproduce locally but I hope that adding a timeout flag could help to understand what is going on.
[RHTAPBUGS-556](https://issues.redhat.com/browse/RHTAPBUGS-556)

test: RHTAPBUGS-556 added timeout flag to curl command

---

pkg/constants/constants.go
pkg/utils/build/quay.go
pkg/utils/has/components.go
tests/build/build.go

This PR included tests step related to private repository requests by image-controller and switching between `public` to `private` after the image got created.
https://issues.redhat.com/browse/STONEBLD-1601
Tested locally using my quay org, subscribing to private organizations.

feat: Private image repo flow

---

cmd/loadTests.go
tests/load-tests/load-tests-example.json

Fixing typo in JSON field name, alligning with the rest
No test

fix: Typo in JSON field name, alligning with the rest

---

pkg/utils/gitops/deploymenttargetclasses.go
pkg/utils/gitops/environments.go
pkg/utils/integration/integration_test_scenarios.go
pkg/utils/integration/pipelineruns.go
pkg/utils/integration/snapshots.go
tests/README.md
tests/integration-service/README.md
tests/integration-service/integration.go
tests/integration-service/namespace-backed-environments.go

This addition to the mvp-demo test suite's Chapter 2 deals with executing an IntegrationTestScenario on a Snapshot inside an ephemeral environment. The test makes sure that the snapshot passes the testing and gets marked as "passed".
[STONEINTG-398](https://issues.redhat.com/browse/STONEINTG-398)

test: (STONEINTG-398) Add Happy Path coverage for namespace-backed envs

---

tests/load-tests/cluster_read_config.yaml

Fixes [RHTAP-1566](https://issues.redhat.com//browse/RHTAP-1566).
PR adds this to the status data JSON:
"parameters": {
"cluster": {
"compute-nodes": {
"count": "5",
"flavor": "m6a.2xlarge",
"nodes": [
"ip-10-0-153-208.ec2.internal",
"ip-10-0-181-118.ec2.internal",
"ip-10-0-204-39.ec2.internal"
]
},
"control-plane": {
"count": "3",
"flavor": "m6a.8xlarge",
"nodes": [
"ip-10-0-153-208.ec2.internal",
"ip-10-0-181-118.ec2.internal",
"ip-10-0-204-39.ec2.internal"
]
}
},
"env": {
"BUILD_ID": "1701573181531230208",
"HOSTNAME": "load-test-ci-10u-10t-nodejs-redhat-appstudio-load-test",
"JOB_NAME": "pull-ci-redhat-appstudio-e2e-tests-main-load-test-ci-10u-10t-nodejs",
"OPENSHIFT_API": "https://api.ci-op-ftk8sjn2-1c995.origin-ci-int-aws.dev.rhcloud.com:6443",
"PROW_JOB_ID": …

feat(RHTAP-1566): Add more metadata to our status data JSON

---

tests/integration-service/namespace-backed-environments.go

This PR enables the test that was skipped (https://github.com/redhat-appstudio/e2e-tests/pull/764), because the [fix for the change](https://github.com/redhat-appstudio/infra-deployments/pull/2402) now has been merged and has solved the issue (see the green CI).
[RHTAPBUGS-769](https://issues.redhat.com/browse/RHTAPBUGS-769)
I've tested this locally in my cluster.

fix(RHTAPBUGS-769): Enable the namespace-backed-environments test again

---

README.md
default.env
magefiles/installation/install.go
magefiles/magefile.go
magefiles/sprayproxy.go
pkg/apis/github/pull_request.go
pkg/constants/constants.go
pkg/utils/util.go
tests/build/build.go
tests/rhtap-demo/rhtap-demo.go

This PR is to modify the exiting Pac test to adapt Github App  and add logics for registering/unregistering Pac server. It depends on the PRs [42057](https://github.com/openshift/release/pull/42057) , [2207](https://github.com/redhat-appstudio/infra-deployments/pull/2207) , [2267](https://github.com/redhat-appstudio/infra-deployments/pull/2267) and [42622](https://github.com/openshift/release/pull/42622) 

feat: Enable existing tests working with Pac+ Github App

---

pkg/constants/constants.go
pkg/utils/common/snapshot_environment_bindings.go
pkg/utils/gitops/environments.go
pkg/utils/integration/pipelineruns.go
pkg/utils/integration/snapshots.go
tests/integration-service/integration.go
tests/integration-service/namespace-backed-environments.go

This is an enhancement PR for the [previously merged PR](https://github.com/redhat-appstudio/e2e-tests/pull/496), because https://github.com/redhat-appstudio/e2e-tests/pull/496 got merged too soon before I could address the non-blocking review comments.
The test suite still works fine without this PR but this is just an attempt to make this test suite even more readable, concise, and resilient. This PR:
* Removes the top-level Describe block from both the files
* Moves 3 functions out of the Describe blocks to reduce code duplication
* Adds a util function to wait for PLR to get started to make test suites slimmer
* Adds a retry logic within the test suite where the GetEphemeralEnvironment function gets called
* Ensures each test uses a unique test namespace
* Improves the Eventually …

feat(STONEINTG-398): this is a follow-up enhancement PR

---

tests/load-tests/cluster_read_config.yaml
tests/load-tests/run-max-concurrency.sh
tests/load-tests/run.sh

Currently, the load test output JSON contains the `.metadata.stringContent` field with the content of the `SCENARIO` variable set by the CI. However, since the variable is provided by the CI as secret, the actual value in the JSON is censored by the CI (assuming the `SCENARIO` value is `export USER_PREFIX=ci-quarkus USERS_PER_THREAD=10 THREADS=10`):
```
...
"metadata": {
...
"env": {
...
"SCENARIO": "ci-daily-10u-10t"
},
"scenarioContent": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
},
...
```
This PR replaces the `.metadata.scenarioContent` string value with a parsed set of key=value pairs found in the `SCENARIO` variable (since the content format is `export env=value env2=value2 ...`) and renames the field to `.metadata.scenario`
So, with this PR the respective part …

fix(load-test): replace scenarioContent string with a key=value set in the output JSON

---

pkg/framework/utils.go
pkg/logs/utils.go
tests/byoc/byoc.go
tests/rhtap-demo/rhtap-demo.go

This PR is based on top of https://github.com/redhat-appstudio/e2e-tests/pull/745. It addressed the one change request I had there (as @jsmid1 is not working this week).
It also (which is the main part of this PR) stores (hopefully) all relevant (and some probably unrelevant) artifacts when `DeleteAllComponentsInASpecificNamespace` fails. This should help with investigation of [RHTAPBUGS-540](https://issues.redhat.com//browse/RHTAPBUGS-540).
https://issues.redhat.com/browse/RHTAPBUGS-540
For a while I had a commit that would trigger the archivation logic for each afterall in `rhtap-demo.go`. This is the result: https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/redhat-appstudio_e2e-tests/757/pull-ci-redhat-appstudio-e2e-tests-main-redhat-appstudio-e2e/17001 …

feat: RHTAPBUGS-540 archive artifacts when DeleteAllComponentsInASpecificNamespace fails.

---

tests/spi/get-file-content.go

https://github.com/redhat-appstudio/service-provider-integration-operator/pull/706 will break the `get-file-content` test. Skipping it temporarily until the PR is merge and the test rewrite

test: skip get-file-content test

---

magefiles/magefile.go

Since PaC tests [now require Github App](https://github.com/redhat-appstudio/e2e-tests/pull/703), we need to register every PaC server (that's created by every e2e job) to the [PaC spray proxy server](https://github.com/redhat-appstudio/e2e-tests/pull/703/files#diff-d7a1577b2d546e34aaf816bdd1b83edef28a66a555f049767bafa83268b7efbbR228) in every e2e-tests job that is configured to run PaC tests (you can find more details about this in [the linked PR](https://github.com/redhat-appstudio/e2e-tests/pull/703))
This was not done for periodic jobs which explains why PaC tests were failing to register a PipelineRuns for created Components.
https://issues.redhat.com/browse/RHTAPBUGS-841
it has to be tested in a periodic job

fix: register PaC proxy server in nightly job

---

pkg/apis/github/pull_request.go
tests/build/build.go
tests/rhtap-demo/rhtap-demo.go

* fix for [RHTAPBUGS-844](https://issues.redhat.com//browse/RHTAPBUGS-844)
* removed superfluous code related to PaC
* getting PaC controller route from `pipelines-as-code` namespace
* deleting GitHub webhooks after the test is finished
https://issues.redhat.com/browse/RHTAPBUGS-844
```
ginkgo -v --label-filter='pac-build' ./cmd/
```

fix: build: validating PaC checks status

---

cmd/loadTests.go
tests/load-tests/ci-scripts/max-concurrency/collect-results.sh
tests/load-tests/run-max-concurrency.sh

To detect KPI, let's use whole workload as deployment might take tenths of seconds as well. This approach is also used when I measure Stage KPI.
Going to test this in CI in this PR

feat: To detect KPI, let's use whole workload as deployment might take tenths of seconds as well

---

tests/build/build.go

[version bump to OSP 1.12](https://github.com/redhat-appstudio/infra-deployments/pull/2521) caused one test to fail due to API incompatibility. this PR fixes it
https://issues.redhat.com/browse/RHTAPBUGS-872
in CI 🤷

fix: compatibility with OSP 1.12

---

tests/load-tests/run-max-concurrency.sh

Fixing python command name.
This fixes change done in https://github.com/redhat-appstudio/e2e-tests/pull/806
- Bug fix (non-breaking change which fixes an issue)

fix: Python command does not exist

---

pkg/apis/github/pull_request.go
tests/build/build.go

this PR fixes a bug that is caused by a missing feature in spray-proxy - more details here: [PLNSRVCE-1488](https://issues.redhat.com//browse/PLNSRVCE-1488)
the test is updated to validate a status of individual [checkrun](https://docs.github.com/en/rest/checks/runs?apiVersion=2022-11-28) instead of checksuite. it is still a proper way to test the PaC functionality and at the same time it's a workaround for the spray-proxy issue.
https://issues.redhat.com/browse/RHTAPBUGS-848
tested on 2 different clusters to reproduce the issue with spray proxy and verify that the test works as expected
```
ginkgo -v --label-filter='custom-branch' ./cmd/
```

fix: use CheckRuns for validating PaC build result

---

pkg/constants/constants.go
tests/build/chains.go

Adds a test to check if the Tekton Chains signing secret required to generate image and attestation signatures is present.
Ref. https://issues.redhat.com/browse/HACBS-2623
We'll see on the test run

feat: check Chains signing secret is present

---

tests/build/build_templates.go

In fixing [RHTAPBUGS-880](https://issues.redhat.com//browse/RHTAPBUGS-880) we found out that the policy did not correctly handle undefined source revision, which lead to [RHTAPBUGS-883](https://issues.redhat.com//browse/RHTAPBUGS-883).
Before we merge [RHTAPBUGS-883](https://issues.redhat.com//browse/RHTAPBUGS-883) we need to make sure that the revision is passed via the parameters to EC so that the change for fixing [RHTAPBUGS-883](https://issues.redhat.com//browse/RHTAPBUGS-883) doesn't break e2e tests.
[RHTAPBUGS-883](https://issues.redhat.com//browse/RHTAPBUGS-883), relates to [RHTAPBUGS-880](https://issues.redhat.com//browse/RHTAPBUGS-880)
Prow will take care of this... :crossed_fingers:

fix(RHTAPBUGS-883): make sure revision is set

---

tests/enterprise-contract/contract.go

The test "ec cli supports the current policy config fields" looks at the output of the verify ec task and looks for the presence of a certain string. This is taken as a way to verify the policy config is being propagated to the task properly. This is a weak assertion because the particular string may appear somewhere else. Also, this is checking a very specific behavior of the EC cli and not an integration test. There is already sufficient test coverage on the EC cli's own tests.

fix: remove faulty EC test

---

pkg/utils/build/task_results.go

In https://github.com/redhat-appstudio/build-definitions/pull/630, I am removing the inspect-image task from all but the FBC pipeline. This requires the current e2e tests to fail as it was previously required for all pipeline definitions. Removing the requirement for all but FBC pipelines.
- ~[ ] I have made corresponding changes to the documentation~
- ~[ ] I have added meaningful description with JIRA/GitHub issue key(if applicable), for example HASSuiteDescribe("STONE-123456789 devfile source")~
- ~[ ] I have updated labels (if needed)~

fix: only require the inspect-image task for FBC PLRs

---

tests/build/build_templates.go

* disable EC test to unblock other PRs. the failure will be investigated and fix delivered as a part of https://issues.redhat.com/browse/RHTAPBUGS-930
https://issues.redhat.com/browse/RHTAPBUGS-930
```
ginkgo --focus-file tests/build/build_templates.go --v ./cmd
```

test: temporarily disabling failing EC test

---

tests/build/build_templates.go

`pipelinesascode.tekton.dev/sha` was not a correct PipelineRun annotation to get the revision from, because build-templates test doesn't run PaC type of build.
`build.appstudio.redhat.com/commit_sha` annotation is valid for both simple and custom (PaC) type of builds
https://issues.redhat.com/browse/RHTAPBUGS-930
```
ginkgo --focus-file tests/build/build_templates.go --v ./cmd
```

fix: build-templates: get valid git revision

---

.github/workflows/loadtest.yaml
tests/load-tests/ci-scripts/stage/collect-results.sh

This PR implements the needed updates per the usage of the new Stage Prometheus SA created by Jan
The SA secret will be used as a token to login to the Stage member cluster hence having the authorization to query Stage Prometheus service
OCP_PROMETHEUS_TOKEN env var is the perf-team-prometheus-reader-cluster-sa Prometheus service account secret
Added PROMETHEUS_HOST env var into logic and as new secret
https://issues.redhat.com/browse/RHTAP-1726 - Fix GitHub action against Stage
1. Renamed OCP_TOKEN GITHUB Actions secret to OCP_PROMETHEUS_TOKEN and populated it with the Stage Prometheus SA secret
a. Get your personal token for Staging member cluster (https://console-openshift-console.apps.stone-stg-m01.7ayg.p1.openshiftapps.com/dashboards) and login with your personal OCP Token into the …

feat(RHTAP-1726): Fix-GitHub-action-against-Stage

---

tests/remote-secret/environments.go

The remote secrets cleanup by spi will now [only clean targets in the RS that explicitly have the environment name in labels on annotations](https://github.com/redhat-appstudio/service-provider-integration-operator/pull/758). That will make the test fail.
[RHTAPBUGS-936](https://issues.redhat.com/browse/RHTAPBUGS-936)

test: RHTAPBUGS-936 skip cleanup verification in spi environments test

---

pkg/apis/github/pull_request.go
pkg/utils/has/components.go
tests/build/build.go
tests/build/const.go

This PR covers a scenario for recently added feature of preventing unnecessary pipeline runs when multi component are in a single repo. 
https://issues.redhat.com/browse/STONEBLD-1762
Locally with installing RHTAP in a cluster.

feat: add test for prevent unnecessary pipelineruns feature

---

tests/load-tests/ci-scripts/stage/cluster_read_config.yaml
tests/load-tests/ci-scripts/stage/collect-results.sh

This update remained from the previous PR (https://github.com/redhat-appstudio/e2e-tests/pull/848) which was merged
Fixed the cluster_read_config.yaml metrics used to discard the nodes related metrics and adjusted the metadata.scenario calculation
https://issues.redhat.com/browse/RHTAP-1726
Ran the load-test workflow in https://github.com/naftalysh/e2e-tests/actions/workflows/loadtest.yaml
And observed the monitoring-collection.log file in the workflow artifacts

feat(RHTAP-1726): Fix-GitHub-action-against-Stage - Update monitoring configuration adjusted to Prometheus SA authorization

---

tests/spi/oauth.go

-  Fixes were addressed to [cypress-browser-oauth-flow repo](https://github.com/redhat-appstudio-qe/cypress-browser-oauth-flow) in other to fix [RHTAPBUGS-939](https://issues.redhat.com/browse/RHTAPBUGS-939). So, we are good to reenable the test.
[RHTAPBUGS-939](https://issues.redhat.com/browse/RHTAPBUGS-939)

fix: RHTAPBUGS-939 reenable "SPITokenBinding should be in Injected phase"

---

tests/build/build_templates.go
tests/release/pipelines/e2e-fbc.go
tests/release/pipelines/e2e-test-push-image-to-pyxis.go

We deprecated SLSA1 and SLSA2 collections/configurations/pipelines, this removes those from e2e tests.
https://issues.redhat.com/browse/EC-195
In CI :)

chore: remove/replace SLSA1 and SLSA2 tests

---

docs/Installation.md
tests/remote-secret/environments.go

The remote secrets cleanup by spi will now [only clean targets in the RS that explicitly have the environment name in labels on annotations](https://github.com/redhat-appstudio/service-provider-integration-operator/pull/758). So, the cleanup verification should be adjusted to this new logic.
[RHTAPBUGS-936](https://issues.redhat.com/browse/RHTAPBUGS-936)

test: RHTAPBUGS-936 reenable cleanup environment verification in remote-secret test

---

cmd/loadTests.go

Removing GitOpsRepo check from Load test, instead, we'll rely on Application CR conditions
[RHTAP-1531](https://issues.redhat.com//browse/RHTAP-1531): https://issues.redhat.com/browse/RHTAP-1531

chore: Get rid of GitOpsRepo check from Load test

---

docs/Installation.md
pkg/utils/integration/integration_test_scenarios.go
pkg/utils/integration/pipelineruns.go
tests/integration-service/README.md
tests/integration-service/const.go
tests/integration-service/integration.go
tests/integration-service/namespace-backed-environments.go
tests/integration-service/status-reporting-to-pullrequest.go

This PR adds a new test file within the integration-service test suite, that automates the status reporting of integration tests within the CheckRuns.
[STONEINTG-609](https://issues.redhat.com/browse/STONEINTG-609)
Ran the test locally in a fresh cluster by running the command: `./bin/e2e-appstudio --ginkgo.label-filter="status-reporting" ginkgo -vv`

test(STONEINTG-609): e2e automation for reporting integration test status

---

Makefile
magefiles/magefile.go
magefiles/utils.go

This PR adds a make target `cleanupPrivateRepos` to cleanup private repos older than 7 days.
https://issues.redhat.com/browse/STONEBLD-1764
Tested locally using `make clean-private-repos`

chore: cleanup private repos older than 7 days

---

magefiles/magefile.go

tests running in integration-service repo are now using PaC, so the sprayproxy needs to be enabled there
it wasn't 🤷

fix: register sprayproxy for integration-service

---

pkg/utils/tekton/bundles.go
pkg/utils/util.go
tests/build/build.go

The name+bundle pipelineRef style is deprecated, Tekton API v1 will support only the resolver+params style [1]. Build-service added v1 support in https://github.com/redhat-appstudio/build-service/pull/205.
Add support for v1-style pipelineRefs by taking the bundle reference either from the 'bundle' attribute or from the 'params'.
[1]: https://tekton.dev/docs/pipelines/pipelineruns/#tekton-bundles
[STONEBLD-1772](https://issues.redhat.com//browse/STONEBLD-1772)
Via branch pairing in https://github.com/redhat-appstudio/infra-deployments/pull/2709

feat: support v1-style BuildPipelineSelector pipelineRef

---

pkg/utils/integration/pipelineruns.go
pkg/utils/tekton/pipelineruns.go
pkg/utils/util.go
tests/build/build.go
tests/build/jvm-build.go

Tekton v1 no longer supports the v1beta1 pipelineRef style (name+bundle), switch to the v1 style (resolver+params).
Using the v1 pipelineRef style for BuildPipelineSelectors will allow build-service to drop support for the v1beta1 style.
Use the v1 style for PipelineRuns as well for consistency.
[STONEBLD-1772](https://issues.redhat.com//browse/STONEBLD-1772)
Only with CI

chore: prepare pipelineRef syntax for Tekton v1

---

tests/integration-service/const.go
tests/integration-service/integration.go
tests/integration-service/namespace-backed-environments.go

* defines finalizer string within the const.go
* add finalizer-check in an Eventually block to fix this bug
* add a new "When" node to make it easy to read, write, and debug tests
* cleanup task to remove hardcoded strings from the tests
Note: for more details, please read the commit messages.
[RHTAPBUGS-989](https://issues.redhat.com/browse/RHTAPBUGS-989)
I've executed the test by running it multiple times on my cluster using the command: `./bin/e2e-appstudio --ginkgo.focus="with happy path for general flow of Integration service" –ginkgo.vvv`, and it passed each time.

fix(RHTAPBUGS-989): Expected Build PLR to contain finalizer added by integration-service

---

tests/rhtap-demo/config/scenarios.go

](https://redhat-appstudio.github.io/docs.appstudio.io/Documentation/main/getting-started/get-started/#choosing-a-bundled-sample)

fix: Disable dotnet samples. They are not supported in rhtap

---

pkg/clients/has/components.go
tests/rhtap-demo/rhtap-demo.go

Reverts redhat-appstudio/e2e-tests#917

fix: Revert "fix: RHTAPBUGS-985: retry pipelineruns always when error occurs"

---

pkg/clients/has/components.go
tests/build/build.go
tests/build/build_templates.go
tests/build/jvm-build.go
tests/byoc/byoc.go
tests/integration-service/integration.go
tests/integration-service/namespace-backed-environments.go
tests/integration-service/status-reporting-to-pullrequest.go
tests/release/pipelines/fbc_release.go
tests/release/pipelines/push_to_external_registry.go
tests/release/service/happy_path.go
tests/release/service/happy_path_with_deployment.go
tests/remote-secret/component-annotation-image-pull-remote-secret.go
tests/remote-secret/environments.go
tests/remote-secret/image-repository-cr-image-pull-remote-secret.go
tests/rhtap-demo/rhtap-demo.go

This will address failures like: https://github.com/redhat-appstudio/infra-deployments/pull/2836#issuecomment-1833476228
or https://issues.redhat.com//browse/RHTAPBUGS-985

fix: RHTAPBUGS-1028: Add a struct to helper to retrigger pipelineruns in case of flaky registries

---

pkg/utils/pipeline/results.go

The test for tekton-results logs needs to be changed according to the latest API change in tekton-results. Here is the change [PR](https://github.com/tektoncd/results/pull/632) of tekton-results.
- [x ] I have performed a self-review of my code

fix: Change the test of tekton-results logs to meet the latest API change in tekton-results

---

.tekton/update-build-definitions.yaml

this will update the reference to the e2e-tests image in build-definitions
We'll want to merge this after https://github.com/redhat-appstudio/build-definitions/pull/692 merges
https://issues.redhat.com/browse/PLNSRVCE-1533
- [/ ] New feature (non-breaking change which adds functionality)
unfortunately we cannot test PaC based push jobs until after merge; we may have to iterate on this to get the generation of PRs in the build-defintions repo correct
- [/ ] I have performed a self-review of my code
- [n/a ] I have commented my code, particularly in hard-to-understand areas
- [n/a ] I have made corresponding changes to the documentation
- [n/a ] I have added meaningful description with JIRA/GitHub issue key(if applicable), for example HASSuiteDescribe("STONE-123456789 devfile source") 
- [ …

chore: PLNSRVCE-1533: create a PaC on push job to update refs to the e2e-tests image used in build-definitions

---

tests/integration-service/status-reporting-to-pullrequest.go

* This if condition checks if the "constants.SKIP_PAC_TESTS_ENV" flag is set to "true".
* If that flag is set to true ([right here](https://github.com/redhat-appstudio/e2e-tests/blob/91966584ae5fda8a84cda8cb87a46d4e1c1a5deb/magefiles/magefile.go#L253)), that indicates there was an error registering the sprayproxy server.
* Hence, the test gets skipped automatically in that case.
I've not tested this locally, but this flag is already in use by the other PaC-related test suites, see: [build.go](https://github.com/redhat-appstudio/e2e-tests/blob/91966584ae5fda8a84cda8cb87a46d4e1c1a5deb/tests/build/build.go#L578) and [rhtap-demo.go](https://github.com/redhat-appstudio/e2e-tests/blob/91966584ae5fda8a84cda8cb87a46d4e1c1a5deb/tests/rhtap-demo/rhtap-demo.go#L350)

fix: automatically skip the PaC-related test of integration service when there's an issue with sprayproxy server

---

tests/load-tests/ci-scripts/setup-cluster.sh

fix go setup by "go mod vendor" to allow load test to work
https://issues.redhat.com/browse/RHTAP-1991
By issuing a successful openshift-ci load test 
once we get the load-tests.json result file we know the test succeeded

fix(RHTAP-1991): Daily-CI-test-does-not-produce-JSON-file

---

cmd/loadTests.go
tests/load-tests/ci-scripts/utility_scripts/measure-time-skew.sh

Fix time skew between the testing machine and the cluster which impacts on load-tests accuracy
I am converting mixed timers calculations to cluster-side calculations so the time skew between local machine time and cluster time won't affect the calculations.
https://issues.redhat.com/browse/RHTAP-1892
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)
The timing calculations will be implemented resource by resource and be tested by an openshift-ci load test job
Application, CDQ, Component, 
The other resources - user  - don't have mixed timers issue,
integrationTestScenario, component build pipelineRuns, IntegrationTests pipelineRuns, Deployments have proper non-mixed timers calculation 
Verifications - 
1. Verify in the load-tests.json …

fix(RHTAP-1892): time-skew-between-the-testing-machine-and-the-cluster

---

pkg/clients/integration/pipelineruns.go
tests/integration-service/const.go
tests/integration-service/integration.go
tests/integration-service/namespace-backed-environments.go
tests/integration-service/status-reporting-to-pullrequest.go

build PLRs will only be reconciled by the buildpipeline controller after the Chains controller adds the annotation "chains.tekton.dev/signed" to it, no matter if its value is "true" or "failure".

fix(stoneintg): fix e2e-tests so buil PLR be reconciled on chains

---

magefiles/magefile.go

The e2e-tests for the release-service-catalog suite should not set the RELEASE_SERVICE_IMAGE_{REPO,TAG}. It should use whatever is the default like other tests do. This commit fixes that logic.

fix(RHTAPREL-732): fix magefile for release-service-catalog

---

go.mod
pkg/clients/integration/snapshots.go
tests/integration-service/const.go
tests/integration-service/integration.go
tests/integration-service/namespace-backed-environments.go

* The integration service recreates a new Integration PipelineRun based on the value of the test.appstudio.openshift.io/run label on a Snapshot
* This change adds e2e tests for the new functionality by adding the label in integration e2e tests and observing the retriggered pipelineRun is handled correctly

feat(STONEINTG-702): add tests for integration pipeline re-runs

---

pkg/clients/has/components.go
tests/byoc/byoc.go
tests/remote-secret/environments.go
tests/rhtap-demo/rhtap-demo.go

- Unfortunately, 10min to wait for the component to be deleted can be not enough, which is the example of this [job](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/redhat-appstudio_e2e-tests/952/pull-ci-redhat-appstudio-e2e-tests-main-redhat-appstudio-e2e/1734489406808526848#1:build-log.txt%3A1338). The present PR increases it to 15min.
[RHTAPBUGS-978](https://issues.redhat.com/browse/RHTAPBUGS-978)

test: RHTAPBUGS-978 increase timeout of component deletion from 10min to 15min

---

magefiles/magefile.go

The QE org has 10k+ repos, most of them are left over gitops repos. I think the easiest way to fix this would be to just clean up all repos with the description 'GitOps Repository', rather than trying to expand the name regex to match every application used in the test suite.
This large number of repos means that any code that attempts to iterate over them will take minutes to complete, e.g. the current renovate code takes about 5 minutes.

chore: cleanup Gitops repos

---

tests/build/multi-platform.go

This is needed for [STONEBLD-1779](https://issues.redhat.com//browse/STONEBLD-1779) to verify we are not leaving credentials on the remote host
Verifies that after a multi platform build the cleanup is successful. 
https://issues.redhat.com/browse/STONEBLD-1779

test: verify multiplatform cleanup

---

tests/integration-service/namespace-backed-environments.go

* The re-run integration test doesn't need to succeed in order to test the re-run functionality. Running multiple namespace-backed environment integration tests can run into resource limitations, failing the test.

fix(STONEINTG-702): remove check for successful Snapshot after re-run

---

tests/integration-service/namespace-backed-environments.go

* create timeout and integration when checking DLC phase in namespace-backed-environment

fix(RHTAPBUGS-980): increase timeout and internal in NBE case

---

tests/integration-service/namespace-backed-environments.go

* increase timeout when waiting for snapshot to be marked as succeeded in namespace-backed-environments.go which often fails with timeout. [See https://github.com/redhat-appstudio/integration-service/pull/481](https://github.com/redhat-appstudio/integration-service/pull/481#issuecomment-1868913625). 

fix: increase timeout for NPE case

---

tests/build/build_templates.go

Till the fix is available in RHTAP for the issue [RHTAPBUGS-948](https://issues.redhat.com//browse/RHTAPBUGS-948)
https://issues.redhat.com/browse/RHTAPBUGS-948

chore: skipping pipelinerun log check step which fails intermittently

---

pkg/clients/integration/pipelineruns.go
tests/integration-service/README.md
tests/integration-service/integration.go

The integration service removes the finalizers from the Integration Pipelineruns after its test results are reported to the Snapshot and the overall test result is used to mark the Snapshot as Passed/Failed. So, this PR updates the current test suites to test this behaviour.
[STONEINTG-704](https://issues.redhat.com//browse/STONEINTG-704)
I've tested this code locally and the test suite passed 10/10 times.

fix(STONEINTG-704): e2e tests should check if the finalizer is removed from Integration PLRs

---

magefiles/magefile.go
pkg/constants/constants.go
tests/release/const.go
tests/release/pipelines/fbc_release.go
tests/release/pipelines/rh_push_to_external_registry.go

1. Fixed the additionalComponentName in mapping and changed to use development branch as default branch and updated the name of pipeline
2. Added the envirionment variables required by release-pipelines-suite
3. Updated some FBC constants to variables to make the test repeatable with failure.

fix: issues in release pipelines suite

---

tests/integration-service/namespace-backed-environments.go

Problem:
* Currently, our nbe.go test suite re-runs an integration test on the Snapshot within an "ephemeral namespace".
* This test coverage was added as part of Integration service's re-run feature.
* However, this new addition is causing failures specifically on the CI of the integration-service repo.
* Why? Because Integration service uses smaller cluster pool to run its CI jobs.
(Temporary) Solution:
* Just to be clear, this is just what I believe is causing the problem.
* In order to confirm it, I'm confirming the related test nodes, and monitor the CI jobs to see if it made any difference.
[RHTAPBUGS-1051](https://issues.redhat.com//browse/RHTAPBUGS-1051)
CI :crossed_fingers:

fix(RHTAPBUGS-1051): skip the ginkgo nodes that are re-running NBE tests

---

tests/rhtap-demo/rhtap-demo.go

Turns out I removed one change from https://github.com/redhat-appstudio/e2e-tests/pull/916 in one of the rebases I did in that PR. 
This PR adds this logic back.
RHTAPBUGX-890
CI

fix: Add missing logic for RHTAPBUGS-890

---

tests/release/service/release_plan_and_admission_matched.go

After ReleasePlanAdmission CR is deleted, the status checking of ReleasePlan
need some delay some time.

fix: add delay for rp status checking after rpa is deleted

---

pkg/clients/integration/pipelineruns.go
tests/integration-service/namespace-backed-environments.go

When the snapshot is not found (nil), a runtime error occurs when calling GetNamespace and GetName. 
[RHTAPBUGS-1098](https://issues.redhat.com/browse/RHTAPBUGS-1098)

fix: RHTAPBUGS-1098 - nil pointer error in Namespace Backed Environment (NBE) test suite

---

magefiles/magefile.go

The job `ci/prow/appstudio-hac-e2e-tests` is PR check, but is running with the main branch, not with the branch from a PR. This PR should fix it.
https://issues.redhat.com/browse/HAC-5623

fix(test): set env vars if the job is running from PR check

---

Makefile
magefiles/magefile.go

related PR: https://github.com/openshift/release/pull/47866
[the PR we merged yesterday](https://github.com/redhat-appstudio/e2e-tests/pull/1005) was not working, because the bootstrap target used for HAC E2E didn't include the ci:init target, which is crucial for determining Github PR's remote name and branch.
This PR fixes the issue
N/A
in CI

feat: add new bootstrap target for hac e2e

---

tests/spi/access-control.go
tests/spi/oauth.go

Sometimes cluster is busy and, even if the flow completes correctly, the spi oauth flow times out. Increasing the timeout to avoid such cases. 
[RHTAPBUGS-1110](https://issues.redhat.com/browse/RHTAPBUGS-1110)

fix: adjust SPI oauth flow timeouts

---

tests/rhtap-demo/rhtap-demo.go

* Currently when we run e2e tests of any suite, it fails with the message `Failed: Please set the required Stage Variables for user` because related code was placed within the Container node rather than a subject/setup node.
* This PR moves that code within a Setup node instead by moving the current code within rhtap-demo test suite within a new `Describe` node.
I tested locally by running the integration-service's E2E tests before and after these changes and can now confirm that I can run the tests.

fix: Move assertions in a setup node

---

tests/build/build.go

pac-build test was skipped if the private image repo creation failed, it should be skipped when running locally but should fail the tests in case private repo creation does not work

fix: fail pac-build tests for redhat-appstudio-qe org if private image repo creation fails

---

tests/load-tests/ci-scripts/offline-token-regeneration/json_split_and_encode_v2.sh

Fix json_split_and_encode_v2.sh
Fixed json_split_and_encode_v2.sh to correctly split the user list json file to 4 parts
The previous script missed the last record from each part, this script fixes that to enable full list of users to
exist within the 4 parts
https://issues.redhat.com/browse/KONFLUX-1090
https://issues.redhat.com/browse/KONFLUX-1007
https://issues.redhat.com/browse/KONFLUX-1031
I used it to update the users secrets in https://github.com/redhat-appstudio/e2e-tests/settings/secrets/actions 
And in https://github.com/naftalysh/e2e-tests/settings/secrets/actions
As part of my tests for https://issues.redhat.com/browse/KONFLUX-1031

fix(KONFLUX-1090): KONFLUX-1090-Update-offline-token-secrets-in-GitHub

---

tests/build/multi-platform.go

The hosts should no longer have disk space issues, and cleanup should already be much more reliable.

chore(RHTAPBUGS-1125): re-enable tests

---

magefiles/magefile.go

The fbc tests go against the stage cluster so they shouldn't be run on paired catalog PRs.

refactor(RHTAPREL-852): don't run fbc tests in catalog PRs

---

tests/build/build.go
tests/release/pipelines/push_to_external_registry.go
tests/release/pipelines/rh_push_to_external_registry.go
tests/release/service/happy_path.go
tests/release/service/happy_path_with_deployment.go
tests/release/service/missing_release_plan_and_admission.go
tests/release/service/release_plan_and_admission_matched.go
tests/release/service/release_plan_owner_ref.go
tests/rhtap-demo/rhtap-demo.go

The release-service libraries in the e2e-tests repo was called releasecommon in some places and releaseConst in others. This commit changes it to be releasecommon everywhere. Also, this commit updates some lingering ReleasePlanAdmissions that were using hardcoded values for the release-service-catalog instead of the variables.

refactor: consistently call release-service imports

---

tests/release/pipelines/push_to_external_registry.go
tests/release/pipelines/rh_push_to_external_registry.go
tests/release/service/happy_path.go

The RoleBinding granting access to the release-pipeline-resource-role in the dev namespace is now created by the Release controller so no longer has to be created manaully in the Release tests.

refactor(RHTAPREL-371): don't create rolebinding in release tests

---

magefiles/upgrade/upgrade.go

we might want to test ocp upgrades with different types of upgrade channels (stable, fast, candidate, etc..)
previously the **fast** channel was hardcoded. with the current change, any type of channel is supported
[KONFLUX-2063](https://issues.redhat.com//browse/KONFLUX-2063)
```
❯ make ci/test/openshift-upgrade
./mage -v ci:performOpenShiftUpgrade
Running target: CI:PerformOpenShiftUpgrade
I0227 11:31:59.300799   97823 upgrade.go:77] current channel is "candidate-4.13", current ocp version is "4.13.32"
I0227 11:31:59.445403   97823 upgrade.go:112] desired major.minor version is "4.14", desired channel is "candidate-4.14"
I0227 11:31:59.900868   97823 upgrade.go:190] admin ack {"data":{"ack-4.13-kube-1.27-api-removals-in-4.14":"true"}} successfully applied
I0227 11:32:00.049246   97823 …
```

fix: ocp upgrade: support any channel type

---

tests/build/build_templates.go

re-enable the test after https://issues.redhat.com/browse/KFLUXBUGS-99 was fixed
https://issues.redhat.com/browse/KFLUXBUGS-99
```
ginkgo --focus-file tests/build/build_templates.go --v ./cmd/
```

chore: re-enable test for checking pipeline logs

---

tests/build/build.go

this test fails from time to time due to [insufficient timeout](https://issues.redhat.com/browse/KFLUXBUGS-101?focusedId=24247693&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-24247693)
this PR increases doubles the timeout and improves logging
[KFLUXBUGS-101](https://issues.redhat.com//browse/KFLUXBUGS-101)
```
ginkgo -v --label-filter='annotations' ./cmd/
```

fix: increase timeout for invalid annotation test

---

tests/build/build_templates.go

When `pipelineRuns, err := kubeadminClient.HasController.GetAllPipelineRunsForApplication(applicationName, testNamespace)` returns an error, we might leak the finalizers and removing finalizer will be skipped.
Added retry mechanism to try it multiple times.
https://issues.redhat.com/browse/KFLUXBUGS-1133

fix: Retry removing finalizer from pipelineruns

---

tests/rhtap-demo/rhtap-demo.go

fix test bug in rhtap-demo suite on ITS snapshot check 

fix(kfluxbugs-1128): fix rhtap-demo falkiness

---

pkg/utils/build/task_results.go

In https://github.com/release-engineering/rhtap-ec-policy/pull/19, I removed the requirement of multiple checks for FBC pipelines due to their special nature where the images produced are not themsleves pushed, instead metadata is extracted from it and published to the index for OLM.
Therefore, we no longer need to require clair-scan images to be present for these pipelines either.

fix: The clair-scan task is not required for FBC pipelines

---

tests/build/build_templates.go

Recently [this change](https://github.com/redhat-appstudio/build-definitions/pull/839) in build-definitions broke the fbc builds, failure was not detected by the tests. This check will ensure avoid repetitions of the same.

fix: show-summary task check 

---

pkg/constants/constants.go
tests/build/build_templates.go
tests/build/jvm-build.go
tests/enterprise-contract/contract.go

It can take The Tekton Chains operator a long time to attest images. Recently, in the build-definitions test suite, we observed Chains taking nearly 30 minutes - even an hour in extreme cases - to do its job.
We don't have much data at the moment, only these 6 cases (time taken between the push of the binary image and the push of the attestation, based on timestamps in quay.io):
56m
49m
14m
13m
24m
27m
A timeout of 30 minutes seems to be necessary to handle the common case (while still not enough for the worst case).

fix: extend the Chains attestation timeout

---

cmd/loadTests.go

Update PVC function for ITS
Add handling also for ITS pipelineRuns
Signed-Off-By: Siddardh R A <siddardh27@gmail.com>

fix(KONFLUX-2311): Fix PVC function in load test

---

magefiles/magefile.go

Related to [KFLUXBUGS-348](https://issues.redhat.com//browse/KFLUXBUGS-348) where a big portion of failures were caused by [periodic cleanup job](https://prow.ci.openshift.org/job-history/gs/test-platform-results/logs/periodic-ci-redhat-appstudio-rhtap-installer-main-rhtap-dump-external-resources) that takes care of cleaning up quay.io robot accounts/images/tags and **invalid PaC endpoints registered to sprayproxy**
And the last mentioned functionality has a bug that caused deletion of valid PaC endpoint from sprayproxy while the related e2e job (that relied on the PaC endpoint being registered there) was still running. The reason why it was deleted was that our CI clusters don't use valid certificates for application endpoints, thus when an http request was sent to such endpoint (without …

fix: do not delete hosts with invalid certs

---

OWNERS
pkg/clients/imagecontroller/OWNERS
pkg/clients/integration/OWNERS
pkg/clients/jvmbuildservice/OWNERS
pkg/clients/release/OWNERS

* Remove other teams than rhtap-qe from reviewers in the root OWNERS file
* Add teams as reviewers to their pkg/clients folder
Discussion is welcome.
[KONFLUX-2406](https://issues.redhat.com/browse/KONFLUX-2406)
It hasn't. I don't think it's even possible.

ci: refine OWNERS files

---

tests/release/pipelines/fbc_release.go

The fbc test cases need to take several minutes for build pipelineRun and release pipelineRun. Since the access token expired sooner than before, the test cases
are refined and added the token refreshing during the test.

chore: add token refreshing and refine the fbc test cases

---

tests/release/pipelines/rh_push_to_external_registry.go

Drop the pyxis sbom push task
See corresponding change at https://github.com/redhat-appstudio/release-service-catalog/pull/382
This is triggered by https://issues.redhat.com/browse/PSSECMGT-3181
Removing an old task.
Not tested outside of CI yet.

perf: drop the push-sbom-to-pyxis task

---

pkg/constants/constants.go

* Because the build-definitions PR checks are running on the production cluster, due to the heavy load chains controller is overwhelemed more often.
* This is causing test timeout while waiting for chains controller to attest artifacts.
* These days, we're hitting the worst case more often making it difficult for us to merge PRs on build-def repo.
* This PR increases the timeout from 30 mins to 90mins
* We should reduce this timeout as soon as the situation is improved by shifting the checks to execute on the staging cluster instead, which has comparatively less load.
[STONEBLD-2265](https://issues.redhat.com/browse/STONEBLD-2265)
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test …

fix(STONEBLD-2265): increase chains timeout since chains controller is overwhelmed

---

tests/load-tests/ci-scripts/max-concurrency/cluster_read_config.yaml
tests/load-tests/ci-scripts/max-concurrency/collect-results.sh
tests/load-tests/run-max-concurrency.sh

fix(load-test): fix max concurrency collect results script, add tekton result watcher metrics

---

tests/integration-service/status-reporting-to-pullrequest.go

* Add the on-pull-request suffix to differentiate the build pipelineRun checkRun from the integration tests since they now both contain the component name

fix(KFLUXBUGS-1147): update checkRun name for build pipelineRun

---

go.mod
pkg/clients/tekton/taskruns.go
pkg/utils/build/image.go
pkg/utils/build/source_image.go
tests/build/build_templates.go
tests/build/source_build.go

This PR add tests to check if sources coming from parent image are included into the built source image.
[STONEBLD-1832](https://issues.redhat.com//browse/STONEBLD-1832)
Requires https://github.com/redhat-appstudio/build-definitions/pull/883

feat(STONEBLD-1832): add tests to check parent sources are included

---

pkg/utils/util.go

Since build-tasks-dockerfiles 5805b6, only files are recorded in the headers of generated tar archive. Then, during Untar, the parent directories have to be created firstly.
https://github.com/redhat-appstudio/build-definitions/pull/855
This change does not break anything. After merge, e2e tests should work for https://github.com/redhat-appstudio/build-definitions/pull/855 by untaring the source archive.

fix: Fix Untar to create parent dirs when necessary

---

magefiles/magefile.go

MP test was failing due to a bug introduced in https://github.com/redhat-appstudio/build-definitions/pull/862/files, which was merged and related task pushed to `quay.io/redhat-appstudio-tekton-catalog/task-buildah-remote:0.1`, that is used by the MP test
more details in [related jira](https://issues.redhat.com/browse/KFLUXBUGS-1189) and linked slack thread
specifying a fixed tag (instead of a floating one) prevents this issue from happening
https://issues.redhat.com/browse/KFLUXBUGS-1189
in CI ([link to successful CI run](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/redhat-appstudio_e2e-tests/1109/pull-ci-redhat-appstudio-e2e-tests-main-redhat-appstudio-e2e/1775911774357295104))

fix: fixed tag of buildah-remote task for MP test

---

tests/load-tests/ci-scripts/utility_scripts/runs-to-csv.sh

Add script to convert bunch of downloaded benchmark JSONs into CSV
Script mostly comes from https://github.com/redhat-performance/backstage-performance/blob/951326083bacc7e8dafc0650d1cb32cc85d4ac8c/ci-scripts/runs-to-csv.sh
N/A
New feature (non-breaking change which adds functionality)
Locally on 2 downloaded issues for some recent testing.

feat: Add script to convert bunch of downloaded benchmark JSONs into CSV

---

pkg/clients/has/components.go
pkg/constants/constants.go
tests/build/build_templates.go

re-triggering of non-pac builds did not work, this PR fixes it
[KFLUXBUGS-1190](https://issues.redhat.com//browse/KFLUXBUGS-1190)
```
ginkgo -v --label-filter='build-templates-e2e' ./cmd/
```

fix: re-trigger non-pac build

---

tests/build/build_templates.go

All, but the original enterprise-contract Pipeline, are now considered deprecated. Users have been notified. The alternative Pipelines will be removed on May 13th. Testing these Pipelines provides very little value right now. Let's stop doing so in order to speed up the tests.
https://issues.redhat.com/browse/EC-330

test: Stop testing deprecated ec pipelines

---

go.mod
go.sum
tests/integration-service/integration.go

This commit updates the `operator-toolkit` refrence
as result of migration to `konflux-ci` from `redhat-appstudio`
more details parent EPIC:
https://issues.redhat.com/browse/RHTAPREL-800

feat(RHTAPREL-806): update operator toolkit refrence

---

tests/integration-service/README.md
tests/integration-service/integration.go

* Remove the check points for SEB created for successful snapshot since integration stop deloying successful snapshot to root env

feat(STONEINTG-697): remove SEB case created for successful snapshot

---

tests/enterprise-contract/contract.go

The policy rule `attestation_task_bundle.task_ref_bundles_acceptable` was recently renamed to
`attestation_task_bundle.task_ref_bundles_trusted`. This commit updates the test to include either to facilitate the transition. Once all users are up to date, we can drop inclusion of the old name.
This change is required because the test relies on this particular policy rule to fail.
https://issues.redhat.com/browse/KFLUXBUGS-1225

fix: update EC policy inclusion

---

tests/remote-secret/component-annotation-image-pull-remote-secret.go
tests/remote-secret/image-repository-cr-image-pull-remote-secret.go
tests/rhtap-demo/rhtap-demo.go

As part of the feature of decoupling the ephemeral environments in konflux,
this PR is about removing the checks related to SEB(snapshot environment binding )
and Gitops from the e2e-test rhtap-demo .
this PR replaces the closed [PR#1118](https://github.com/redhat-appstudio/e2e-tests/pull/1125)

feat(KONFLUX-2456): remove SEB and Env checks from rhtap-demo and remote

---

pkg/utils/build/source_image.go

Related to [STONEBLD-1831](https://issues.redhat.com//browse/STONEBLD-1831)
Counter within file name extra-src-*.tar will be replaced with extra-src archive checksum. Regex is updated and it is compatible with the existing numeric counter.
[STONEBLD-1831](https://issues.redhat.com//browse/STONEBLD-1831)

feat: match new extra-src filename form

---

tests/release/const.go
tests/release/pipelines/README.md

This commit updates the `release-service-catalog` refrence
as result of migration to `konflux-ci` from `redhat-appstudio`
more details parent EPIC:
https://issues.redhat.com/browse/RHTAPREL-800

feat(RELEASE-500): update release service catalog reference to konflux ci

---

pkg/testspecs/ginkgosspec.go
pkg/testspecs/templates.go

- Package name in .go file is generated by taking the part of filename before dash, e.g. integration-service -> integration
- Handle [Ginkgo automatically changing](https://github.com/onsi/ginkgo/blob/master/ginkgo/generators/generators_common.go#L25) `-` to `_`
https://issues.redhat.com/browse/KFLUXBUGS-1212
Manually by running `./mage GenerateTeamSpecificGinkgoSpecFromTextOutline` with a path containing a dash `-`.

fix: ginkgo spec generation if path contains dash

---

pkg/clients/release/plans.go
tests/integration-service/integration.go
tests/release/const.go
tests/release/pipelines/fbc_release.go
tests/release/pipelines/push_to_external_registry.go
tests/release/pipelines/release_to_github.go
tests/release/pipelines/rh_advisories.go
tests/release/pipelines/rh_push_to_external_registry.go
tests/release/service/happy_path.go
tests/release/service/release_plan_and_admission_matched.go
tests/release/service/release_plan_owner_ref.go
tests/rhtap-demo/rhtap-demo.go

Added e2e tests for create-advisory pipeline
Added data paramater to the CreateReleasePlan function and update it in the repo
Changed release_to_github.go for the conflicting secret usage

feat(RHTAPREL-869): add e2e tests for create-advisory pipeline

---

tests/byoc/byoc.go
tests/rhtap-demo/README.md
tests/rhtap-demo/config/scenarios.go
tests/rhtap-demo/rhtap-demo.go

* Now that integration-service will no longer deploy successful snapshots to all the available root envs, we won't have any component deployments.
* So, we should update the tests to stop checking for component deployments.
[STONEINTG-697](https://issues.redhat.com/browse/STONEINTG-697)
I've tested this change locally on a couple of fresh clusters by deploying the changes from https://github.com/redhat-appstudio/integration-service/pull/677 and running the changes of this PR. The rhtap-demo test passed.

fix(STONEINTG-697): e2e-tests will stop watching for successful deployments

---

cmd/loadTests.go
pkg/clients/integration/integration_test_scenarios.go
tests/integration-service/integration.go
tests/integration-service/status-reporting-to-pullrequest.go
tests/rhtap-demo/rhtap-demo.go

Remove CreateIntegrationTestScenarioV2() and extend signature of original function.
This is a followup on https://github.com/redhat-appstudio/e2e-tests/pull/1092, so that is why it contains all the commits from that as well. Will rebase once 1092 is merged.
N/A
- Bug fix (non-breaking change which fixes an issue)
Manual load test run against Stage. I would rely on CI here.

refactor: Remove CreateIntegrationTestScenarioV2() and extend signature of original function

---

pkg/clients/has/components.go
tests/build/build.go
tests/build/build_templates.go
tests/build/jvm-build.go
tests/build/multi-platform.go
tests/integration-service/integration.go
tests/integration-service/status-reporting-to-pullrequest.go
tests/release/pipelines/fbc_release.go
tests/release/pipelines/push_to_external_registry.go
tests/release/pipelines/release_to_github.go
tests/release/pipelines/rh_advisories.go
tests/release/pipelines/rh_push_to_external_registry.go
tests/release/service/happy_path.go
tests/remote-secret/component-annotation-image-pull-remote-secret.go
tests/remote-secret/image-repository-cr-image-pull-remote-secret.go
tests/rhtap-demo/rhtap-demo.go

when PaC PLR gets re-triggered, the commit SHA changes and if the original one (or related PipelineRun object) is later used in the test, the test would fail
[KFLUXBUGS-348](https://issues.redhat.com//browse/KFLUXBUGS-348)
```
ginkgo -v --focus="Maven project - Simple and Advanced build" ./cmd/
```

fix: PaC: get correct commit SHA after PLR rerun

---

pkg/utils/tekton/pipelineruns.go
tests/enterprise-contract/contract.go

resolves: [CVP-4098](https://issues.redhat.com//browse/CVP-4098)
Tests for enterprise contract should build and test the golden-container image. Also, it should always use the latest golden-container build.
[CVP-4098](https://issues.redhat.com//browse/CVP-4098)
- [ x] Bug fix (non-breaking change which fixes an issue)
Used cluster bot to spin up a cluster and ran `./bin/e2e-appstudio --ginkgo.focus="enterprise-contract-suite"`

fix: Use golden-container latest images in enterprise contract tests

---

go.mod
pkg/clients/common/controller.go
pkg/clients/gitlab/client.go
pkg/clients/gitlab/git.go
pkg/constants/constants.go
tests/integration-service/const.go
tests/integration-service/gitlab-integration-reporting.go

in this PR we implement happy-path of feature integration gilab reporting ensure that the build and integration pipelinerun are reported in the associated gitlab branch as we validate the status of pipelineruns succeeded as expected.
Signed-off-by: Kasem Alem <kasem.alem@gmail.com>

feat(STONEINTG-869): e2e test of gitlab integration reporting

---

.gitignore
pkg/utils/build/image.go
pkg/utils/build/source_image.go
tests/build/build_templates.go
tests/build/source_build.go

Update tests for source container build to ensure builds based on Konflux images work well to generate source images.
PR adding a test repository: https://github.com/redhat-appstudio/build-definitions/pull/1006
[STONEBLD-2256](https://issues.redhat.com//browse/STONEBLD-2256)
Should pass the CI.
- [-] I have made corresponding changes to the documentation
- [-] I have updated labels (if needed)

feat: check source images built on top of Konflux images

---

tests/release/const.go
tests/release/pipelines/rh_push_to_redhat_io.go

Add e2e tests for rh_push_to_redhat_io pipeline and check if a MR is created from "run_file_updates" task at last. 

feat(RELEASE_425): add e2e tests for rh_push_to_redhat_io pipeline

---

tests/integration-service/const.go
tests/integration-service/gitlab-integration-reporting.go

* Add e2e case for reporting failing integration test to GL commitStatus and note
This PR need a base after [PR](https://github.com/redhat-appstudio/e2e-tests/pull/1153/files)

feat(STONEINTG-870): add e2e for reporting failing integration test to GL

---

pkg/clients/release/sbom.go

This commit changes the release suite utility function to support there being multiple task logs to fetch the pyxis image IDs from instead of only supporting one log.

fix: release pyxis tests properly fetch imageIDs

---

magefiles/magefile.go
pkg/constants/constants.go
pkg/framework/framework.go
tests/build/build.go
tests/integration-service/gitlab-integration-reporting.go
tests/integration-service/status-reporting-to-pullrequest.go

After following tests were added/updated to use PaC webhooks  https://github.com/redhat-appstudio/e2e-tests/pull/1107/files, the webhooks started to pile up in the repos [devfile-sample-hello-world](https://github.com/redhat-appstudio-qe/devfile-sample-hello-world) and [secret-lookup-sample-repo-two](https://github.com/redhat-appstudio-qe/secret-lookup-sample-repo-two) until we started hitting [KFLUXBUGS-1280](https://issues.redhat.com//browse/KFLUXBUGS-1280)
The webhooks were manually removed from those repos for now, but we need a logic to cleanup the related webhook after test and an addition to the list of repositories that are being cleaned up by the nightly job: https://github.com/redhat-appstudio/e2e-tests/pull/1165/commits/4c220ad10ff78abda0f655701b599fd2d0d34a64 …

fix: cleanup PaC webhooks after test's finished

---

magefiles/installation/install.go
magefiles/utils.go
tests/load-tests/ci-scripts/setup-cluster.sh

* refer to original remote of `e2e-tests` and `infra-deployment` repos as "upstream" (see [explanation](https://stackoverflow.com/a/9257901))
* add a logic to always rebase with main before running tests, to make sure the branch is always up-to-date
* tested with https://github.com/openshift/release/pull/52146
* follow-up item: delete lines below `TODO` comments introduced in [this PR](https://github.com/openshift/release/pull/52146/files)
https://issues.redhat.com/browse/KFLUXBUGS-1185
https://github.com/openshift/release/pull/52146/files

fix: always rebase e2e-tests and infra-deployments

---

Makefile
magefiles/magefile.go
pkg/constants/constants.go
tests/build/build_templates.go
tests/build/const.go

adds a make target to build-bundle with source build image and update build-pipeline-selector in test namespace
part of story: https://issues.redhat.com/browse/STONEBLD-2353

feat: add a make target to build-bundle with custom source build image

---

.tekton/update-build-definitions.yaml

[STONEBLD-2339](https://issues.redhat.com//browse/STONEBLD-2339)
The build-definitions repo has moved from github.com/redhat-appstudio to
github.com/konflux-ci. Update references accordingly.
Signed-off-by: Adam Cmiel <acmiel@redhat.com>

chore: update build-definitions references to new org

---

magefiles/installation/install.go
magefiles/utils.go

This is a fix for the[ bug in upgrade-job in infra-deployments](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/redhat-appstudio_infra-deployments/3694/pull-ci-redhat-appstudio-infra-deployments-main-appstudio-upgrade-tests/1792894391031959552#1:build-log.txt%3A1670-1675)
the error was:
```
merge: <branch-name> - not something we can merge
Did you mean this?
upstream/<branch-name>
```
It was caused by a conflict with the local remotes `upstream` and `origin`, which was fixed in this PR by replacing the `origin` remote name with `upstream`
Also the error was not visible in the output (see the link above), which was fixed in this PR too
[KFLUXBUGS-1185](https://issues.redhat.com//browse/KFLUXBUGS-1185)
1.
```
export UPGRADE_BRANCH=pipeline-service-test-osp-nightly …
```

fix: upgrade job

---

tests/release/pipelines/fbc_release.go
tests/release/pipelines/release_to_github.go
tests/release/pipelines/rh_advisories.go
tests/release/pipelines/rh_push_to_redhat_io.go

Added managedFw in the ticker to avoid access token expired issue. 
Updated to use WaitForComponentPipelineToBeFinished function and removed the other loop.

fix: access token expired during pipelineRun

---

tests/release/pipelines/fbc_release.go
tests/release/pipelines/release_to_github.go
tests/release/pipelines/rh_advisories.go
tests/release/pipelines/rh_push_to_external_registry.go
tests/release/pipelines/rh_push_to_redhat_io.go

Use WaitForSnapshotToGetCreated and WaitForComponentPipelineToBeFinished function to get CRs to avoid flakness.

fix: use loop or function with loop to get CRs

---

.tekton/update-build-definitions.yaml

[STONEBLD-2339](https://issues.redhat.com//browse/STONEBLD-2339)
The build-definitions repo has moved to the konflux-ci org. The
https://github.com/apps/rh-tap-build-team app had to be reinstalled in
the new org, thus changing the installation ID.
Signed-off-by: Adam Cmiel <acmiel@redhat.com>
https://github.com/konflux-ci/build-definitions/pull/1034

chore: fix GH app installation ID for PR creation

---

pkg/framework/framework.go

Refresh framework before access token expires on Stage
[KONFLUX-2465](https://issues.redhat.com//browse/KONFLUX-2465)
Bug fix (non-breaking change which fixes an issue)
Using this script:
```
package main
import "fmt"
import "os"
import "time"
import "encoding/json"
import "github.com/redhat-appstudio/e2e-tests/pkg/framework"
import "github.com/redhat-appstudio/e2e-tests/pkg/utils"
// User represents a user in the list
type User struct {
Username string `json:"username"`
Password string `json:"password"`
Token    string `json:"token"`
SSOURL   string `json:"ssourl"`
APIURL   string `json:"apiurl"`
Verified bool   `json:"verified"`
}
func LoadStageUsers(filePath string) ([]User, error) {
jsonData, err := os.ReadFile(filePath)
if err != nil {
return nil, err
}
// Parse JSON into an array of …
```

fix(KONFLUX-2465): Refresh framework before access token expires on Stage

---

.github/workflows/estimate-review.yaml

update the org of qe-tools repo to konflux-ci
```bash
❯ gh release download v0.1.0 -R konflux-ci/qe-tools
❯ echo $?
0
```

chore: qe-tools moved to konflux-ci org

---

magefiles/installation/install.go
magefiles/magefile.go

fix of the bug reported [here](https://redhat-internal.slack.com/archives/C02FANRBZQD/p1716896368884529)
the removal of "upstream" remote name [here](https://github.com/redhat-appstudio/e2e-tests/pull/1180/files#diff-be9cd886dab1d153a199cd4e8e53764a124d2bb335339a13d24993b774d0d0f7L223) was not correct - it was causing issues for infra-deployments PRs which were based on a fork that did not contain `main` branch
[KFLUXBUGS-1185](https://issues.redhat.com//browse/KFLUXBUGS-1185)
Similarly like in [this PR](https://github.com/redhat-appstudio/e2e-tests/pull/1180#issue-2308662907) with one extra test scenario:
```
export UPGRADE_BRANCH=ec-batch-update UPGRADE_FORK_ORGANIZATION=enterprise-contract
```

fix: remote names

---

tests/enterprise-contract/contract.go

Some of the EC tests validate images via floating tags (as designed). This makes it hard to provide the expected git commit. Here we just ignore that particular check.

fix: ignore source correlated check in EC tests

---

pkg/clients/github/git.go
tests/build/build.go
tests/build/const.go

secret-lookup tests changed to use organization where github app is not installed
Credits: https://github.com/konflux-ci/e2e-tests/pull/1200

fix: secret-lookup tests changed to use organization where github app is not installed

---

pkg/clients/github/pull_request.go
pkg/constants/constants.go
tests/build/build.go
tests/integration-service/status-reporting-to-pullrequest.go

* removal of [these lines](https://github.com/konflux-ci/e2e-tests/commit/a6ef178c8f0e0587f81ad893141977db17ece30c#diff-938ddf0d569d68c3df496d8b4065614ff56cc303c33555755621cffcec97ef74L66-L68) accidentally broke validating build PLR CheckRun's status - this PR fixes it and unifies the logic for getting CheckRun conclusion for build and integration-service tests
https://issues.redhat.com/browse/KFLUXBUGS-20
```
ginkgo build ./cmd && ginkgo -p -v --label-filter='build-custom-branch,status-reporting' ./cmd/cmd.test
```

fix: checking CheckRuns conclusion in GitHub

---

pkg/clients/has/applications.go
pkg/clients/has/components.go
tests/rhtap-demo/rhtap-demo.go

Removes test code that is no longer needed as a result of the deprecation of the Application and Component controllers within HAS. 
As a result of the removal of the HAS controllers, HAS will no longer set the following fields in the status, and they can be removed:
- status.Devfile in the Application CR
- create/update status condition in the Application CR
- create/update status condition in the Component CR
https://issues.redhat.com/browse/DEVHAS-651

chore(DEVHAS-651): Remove test code for deprecated controllers

---

magefiles/magefile.go

until now, PR pairing worked only for:
* component repo PR + e2e-tests PR
* e2e-tests PR + infra-deployments PR (and vice versa)
this change allows pairing `component repo PR (+ e2e-tests PR) + infra-deployments PR` (if all PRs were created from the same org + branch)
N/A
N/A

feat: allow pairing 3 repositories

---

tests/release/pipelines/fbc_release.go
tests/release/pipelines/push_to_external_registry.go
tests/release/pipelines/release_to_github.go
tests/release/pipelines/rh_advisories.go
tests/release/pipelines/rh_push_to_redhat_io.go
tests/release/releaseLib.go
tests/release/service/happy_path.go

when we merged [this PR](https://github.com/konflux-ci/e2e-tests/pull/1192) related to devfile dependency removal and build-pipeline-selector we broke the few release service tests, we should use fbc-builder pipeline instead of docker-build in those tests
https://issues.redhat.com/browse/KFLUXBUGS-1332

fix: use fbc-builder pipeline instead of docker-build

---

pkg/clients/gitlab/git.go
tests/integration-service/gitlab-integration-reporting.go

On Gitlab integration e2e-tests, webhooks created for PaC components
was not deleted after each run, this caused a Webhooks to be exceeded 
so requests were failing,  in this PR we ensure deleting webhooks after test is done 
When tested locally, I ran it multiple times and get to that Webhooks were deleted as it improved the cleaning of repo after each test

feat(stoneintg-937): add cleanup of webhooks in afterall

---

tests/build/build.go

A follow-up on https://github.com/konflux-ci/e2e-tests/pull/1139, which should have fixed the issue caused by re-triggering PaC build PLR (in case the initial PLR failed)
This PR:
* fixes an issue mentioned above by [updating the `prHeadSha` variable](https://github.com/konflux-ci/e2e-tests/pull/1214/files#diff-938ddf0d569d68c3df496d8b4065614ff56cc303c33555755621cffcec97ef74R343) after PLR is finished, which then ensures that the PR head SHA is the most recent one and is used in verifications later in the test
* unifies the assignments of PLR variable in `pac-build` test scenario
https://issues.redhat.com/browse/KFLUXBUGS-20
in CI 🤷

fix: update PLR SHA if PLR was retriggered

---

go.mod
magefiles/magefile.go
pkg/clients/has/components.go
pkg/clients/tekton/bundles.go
pkg/constants/constants.go
pkg/utils/tekton/bundle.go
pkg/utils/tekton/pipeline_extraction_test.go
tests/build/build_templates.go
tests/build/multi-platform.go

This PR complete removes any usage of `BuildPipelineSelector` since it's deprecated and will be removed soon.
To configure bundle to use, `build.appstudio.openshift.io/pipeline` annotation used instead.
For example:
```
build.appstudio.openshift.io/pipeline: '{"name": "docker-build", "bundle": "quay.io/my-user/my-pipeline-docker-build:ab6b0b8e40e440158e7288c73aff1cf83a2cc8a9"}'
```
[STONEBLD-2500](https://issues.redhat.com/browse/STONEBLD-2500)
CI should succeed without BuildPipelineSelector

chore: Remove BuildPipelineSelector

---

tests/release/pipelines/rh_advisories.go
tests/release/pipelines/rh_push_to_redhat_io.go

This commit refactors the release pipeline tests to use the new tag format and remove the old one.

refactor(RELEASE-920): release pipeline tests use new tag format

---

pkg/constants/constants.go
tests/build/build_templates.go
tests/build/build_templates_scenarios.go
tests/build/const.go

These changes are needed after build-pipeline-selector got removed and are part of the build-definitions CI e2e-tests 
https://issues.redhat.com/browse/STONEBLD-2284
Change has been tested with [this PR](https://github.com/konflux-ci/build-definitions/pull/1066)

fix: changes to build-defintions CI e2e-tests after build-pipeline-selector removal

---

Makefile
magefiles/magefile.go

* register sprayproxy function call moved to a bootstrap function
* sprayproxy unregistering moved to a separate mage target
* failing konflux-ci check is fixed in [another PR](https://github.com/konflux-ci/e2e-tests/pull/1224)
[KFLUXBUGS-1358](https://issues.redhat.com//browse/KFLUXBUGS-1358)
via this PR: https://github.com/openshift/release/pull/53285

fix: unregister PaC from sprayproxy separately

---

tests/load-tests/ci-scripts/max-concurrency/collect-results.sh
tests/load-tests/run-max-concurrency.sh

Followup to https://github.com/konflux-ci/e2e-tests/pull/1163

fix(max-concurrency): fix result collection of max-concurrency test for new iteration directories

---

pkg/clients/has/components.go

In function WaitForComponentPipelineToBeFinished, if the PipelineRun creation times out, variable pr will be nil. Then, function call pr.GetName() will panic.
No issue ticket. Found this issue from a CI run, https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/redhat-appstudio_infra-deployments/3863/pull-ci-redhat-appstudio-infra-deployments-main-appstudio-e2e-tests/1804001654681374720
Excerpt:
```
PipelineRun has not been created yet for the Component rhtap-demo-titr-tenant/quarkus-devfile
PipelineRun has not been created yet for the Component rhtap-demo-titr-tenant/quarkus-devfile
PipelineRun has not been created yet for the Component rhtap-demo-titr-tenant/quarkus-devfile
PipelineRun has not been created yet for the Component rhtap-demo-titr-tenant/quarkus-devfile …
```

fix: nil pointer reference to PipelineRun object

---

Makefile
magefiles/magefile.go

we create a nightly webhooks cleanup form the Gitlab e2e-tests, 

feat(STONEINTG-937): add nightly Gitlab webhooks cleanup

---

magefiles/utils.go
magefiles/utils_test.go

we had around 17k+ leftover robot accounts in [QE quay org](https://quay.io/organization/redhat-appstudio-qe/?tab=robots) which were not cleaned up due to cleanup regex not being updated
N/A
```
DEFAULT_QUAY_ORG_TOKEN=<redacted> DEFAULT_QUAY_ORG=redhat-appstudio-qe  make clean-quay-repos-and-robots
```

fix: update quay cleanup regexp

---

magefiles/magefile.go

[slack conversation](https://redhat-internal.slack.com/archives/C02FANRBZQD/p1719427922490049)
load tests are failing on sprayproxy setup (that should not be triggered for load test jobs) due to this recent change: https://github.com/konflux-ci/e2e-tests/pull/1223
since load tests do not use sprayproxy, this PR introduces the change that will cause sprayproxy setup being skipped for load-tests jobs
N/A
in CI 🤷

fix: no extra setup for load tests

---

tests/build/build.go

This small change will complete work needed for the story to add scenario for `Component onboarding to PaC using github token instead of the PaC github App`, since [this scenario](https://github.com/konflux-ci/e2e-tests/blob/2e39ddce4b49e89bf191614dec64e0f8c439680e/tests/build/build.go#L859) already covers the onboarding part, this PR add the vaidation for offboarding as well. 
https://issues.redhat.com/browse/STONEBLD-2486
Locally

chore: validate offboarding is done successfully with github token

---

tests/build/build.go
tests/build/build_templates.go
tests/build/build_templates_scenarios.go
tests/build/const.go

This PR adds the validation for the floating tag functionality, when additional tags are added in the dockerfile, build pipeline should create the additional tags for them in the quay image repo   
https://issues.redhat.com/browse/STONEBLD-2425
Tested locally and also in the build-defintions CI through [PR](https://github.com/konflux-ci/build-definitions/pull/1106)

feat: Add validation for floating tags functionality

---

pkg/clients/has/components.go
pkg/clients/imagecontroller/image_repository.go
pkg/utils/build/quay.go
tests/build/build.go

This PR changes the e2e-tests to adapt to backward compatibility reconciler in Image Controller, to check the image repo CR instead of annotations
https://issues.redhat.com/browse/STONEBLD-2569

fix: adapt e2e tests to backward compatibility reconciler in Image Controller

---

tests/release/pipelines/multiarch_rh_advisories.go

In this test case, a dedicated repo with PaC configuration to staging cluster is
used. The repo is tied to a fixed component in an application which need to be
created before the test case is ran. 
The test case uses a push event (merging a PR) to trigger the build pipelineRun.
Rh-advisories release pipelineRun is used for the multi-arch test.

feat(RELEASE-927): add multi arch test with rh-advisories pipeline

---

pkg/clients/gitlab/git.go
pkg/clients/has/components.go
pkg/clients/has/controller.go

use GitLab API when retriggering GitLab-based Build PLRs
[KFLUXBUGS-1310](https://issues.redhat.com//browse/KFLUXBUGS-1310)
```
./bin/e2e-appstudio --ginkgo.focus="Gitlab Status Reporting of Integration tests"
```

fix(KFLUXBUGS-1310): use GitLab API when retriggering GitLab-based Build PLRs

---

pkg/utils/build/source_image.go
tests/build/source_build.go

Stop checking BASE_IMAGES_DIGESTS. Most build tasks are about to stop returning this result.
As a consequence, it is currently not possible to check the parent image
sources for non-docker build pipelines. The support could be added (read
the base image from the SBOM), but it seems unnecessary at the moment.
[STONEBLD-2326](https://issues.redhat.com//browse/STONEBLD-2326)
About to be tested ~via branch pairing (hopefully)~ by using the e2e-tests image built for this PR in https://github.com/konflux-ci/build-definitions/pull/1160

fix: stop checking BASE_IMAGES_DIGESTS

---

tests/load-tests/pkg/journey/handle_collections.go

Do not be this vocal about it then. E.g. see https://github.com/kubernetes/client-go/issues/861#issuecomment-686766515

fix: Looks like missing kind is a known bug

---

tests/build/build.go

Two pipelineruns getting created when build-secret is created and onboarding component repo has github app installed, which might be the root cause for the issue
https://issues.redhat.com/browse/KFLUXBUGS-1462

fix: stop creating build-secret when github app installed

---

tests/build/build_templates.go

This proposes not to print the whole SBOM data to stdout. That makes the e2e-tests logs hard to read.

fix: don't print SBOM

---

tests/load-tests/loadtest.go
tests/load-tests/pkg/journey/handle_repo_templating.go
tests/load-tests/pkg/journey/journey.go

GitHub does not allow forking more than 3 at a time anyway. If 3 are forking already, it returns 403 for more forking requests and as we are retrying after 2 seconds, we soon used whole rate_limit.
With parralel forking it also often happened that process was stuck in loop with 403 and only think that helped was cleaning all 10 temporary repos like "<source_repo>-1".
Anyway, fingers crossed, this will be slower but more stable.

refactor(KONFLUX-3773): Fork repositories sequentially

---

pkg/constants/constants.go
tests/load-tests/loadtest.go
tests/load-tests/pkg/journey/handle_component.go
tests/load-tests/pkg/options/options.go

Adding a possibility for Loadtest to add `mintmaker.appstudio.redhat.com/disabled=true` annotation to components.
It is important when testing PaC build (multi-arch), because 'on-pull-request' builds that these Mintmaker PRs causes might interfere with testing.
https://issues.redhat.com/browse/KONFLUX-3857

feat(KONFLUX-3857): Stop Mintmaker creating 'chore: ...' update PRs that provoke 'on-pull-request' builds that might interfere with testing

---

magefiles/rulesengine/repos/common.go
magefiles/rulesengine/repos/e2e_repo.go
magefiles/rulesengine/types.go

* Remove the checks for filtering on "D" status which was causing a bug
* Changed FilterByDirString implementation to use filepath.match to support glob expression
* Changed conditional Any implementation to eval all conditionals
* Added more smaller nuanced rules for specific test directories
- [ X] Bug fix (non-breaking change which fixes an issue)
- [ X] I have performed a self-review of my code
- [ X] I have commented my code, particularly in …

fix: fix and improve test selection rules for e2e-tests repo

---

.tekton/konflux-e2e-tests-pull-request.yaml
.tekton/konflux-e2e-tests-push.yaml
integration-tests/tasks/konflux-e2e-tests-task.yaml

1. Fix the exit code in the trap oras.
2. Fix buildah task. See more at: https://github.com/konflux-ci/build-definitions/blob/main/task/buildah/0.2/MIGRATION.md
3. Seems like only 7 processes are running in the e2e tests. Increasing memory..

fix: Fix task exit_code, improve memory and fix deprecated-img

---

tests/konflux-demo/konflux-demo.go

The rhtap-demo test suite will sometimes fail due to the integration service lagging when marking a snapshot as succeeded. A test expecting the snapshot in a passing state can fail as a result.
[KFLUXBUGS-1297](https://issues.redhat.com/browse/KFLUXBUGS-1297)

fix(KFLUXBUGS-1297): failure for an already successful snapshot

---

integration-tests/pipelines/konflux-e2e-tests-pipeline.yaml

fix: Remove fla bull shits code

---

integration-tests/pipelines/konflux-e2e-tests-pipeline.yaml

rh-pre-commit.version: 2.1.0
rh-pre-commit.check-secrets: ENABLED
This PR relies on PR https://github.com/konflux-ci/konflux-qe-definitions/pull/29

fix: adapt the change of spliting aws-secret into 2 secrets

---

integration-tests/pipelines/konflux-e2e-tests-pipeline.yaml

Tasks which takes more than 1h fail with timeout and will not be visible in Konflux UI. The message is: Logs are no longer accessible for konflux-e2e-wdvd5-lplsl-konflux-e2e-tests task

chore: Ussually a task have by default 1h timeout. Increase timeout to 2h

---

integration-tests/scripts/konflux-e2e-runner.sh
magefiles/magefile.go
pkg/clients/common/controller.go
pkg/clients/gitlab/git.go
pkg/clients/has/components.go
pkg/clients/has/controller.go
pkg/constants/constants.go
tests/build/const.go
tests/integration-service/const.go
tests/integration-service/gitlab-integration-reporting.go

~~Depending on https://github.com/openshift/release/pull/55025 getting merged first~~ merged
`PAC_GITLAB_URL` and `PAC_GITLAB_ID` will be getting removed from Hashicorp Vault
- Introduce new env var `GITLAB_BOT_TOKEN` (already in Hashicorp Vault)
- Change logic of getting GitLab project id since more than one repo will now be used
- Default values for API URL and QE org
- Rename PAC_GITLAB_* env vars
[STONEBLD-2388](https://issues.redhat.com/browse/STONEBLD-2388)

refactor: remove PAC_GITLAB_* env vars

---

docs/Installation.md
tests/integration-service/const.go
tests/integration-service/integration-with-env.go
tests/integration-service/integration.go
tests/integration-service/status-reporting-to-pullrequest.go

* We are unsure of the implications of merging 3 of our test suites into 1.
* This commit reverts their deletion to ensure we return to where we were.
* Now, the:
*  `integration.go` suite uses [redhat-appstudio-qe/hacbs-test-project-integration](https://github.com/redhat-appstudio-qe/hacbs-test-project-integration) repo
* `integration-with-env.go` uses [redhat-appstudio-qe/test-integration-with-env](https://github.com/redhat-appstudio-qe/test-integration-with-env) repo
* `status-reporting-to-pullrequest.go` uses [redhat-appstudio-qe/test-integration-status-report](https://github.com/redhat-appstudio-qe/test-integration-status-report) repo
* Refactor the tests to use the common [createComponent](https://github.com/konflux-ci/e2e-tests/pull/1325/files#diff-fdb9bad9e6467c3d33fe63e08637192c69 …

chore(STONEINTG-1028): revert deletion of Integration service e2e-tests

---

magefiles/rulesengine/repos/e2e_repo.go
tests/integration-service/const.go

* The GitLab e2e-test of Integration service was failing because the test was creating a component using an non-existent GitLab repo.
* This commit updates the repo name.
[STONEINTG-1028](https://issues.redhat.com//browse/STONEINTG-1028)

fix(STONEINTG-1028): correct the name of GL repo

---

docs/Installation.md
tests/integration-service/const.go
tests/integration-service/gitlab-integration-reporting.go

* the previous repo names matched [the regex string](https://github.com/konflux-ci/e2e-tests/blob/ef7f3a7b3f5e1e495ecf415f151a5b573d633109/magefiles/magefile.go#L58) that which is used to delete stale GH repos.
* so this commit, renames the repos in a way to not get matched with it
* here are the new repos:
* https://github.com/redhat-appstudio-qe/konflux-test-integration
* https://github.com/redhat-appstudio-qe/konflux-test-integration-with-env
* https://github.com/redhat-appstudio-qe/konflux-test-integration-status-report
[STONEINTG-1028](https://issues.redhat.com/browse/STONEINTG-1028)
I tested the new repo names on regex101.com with [this regex expression](https://github.com/konflux-ci/e2e-tests/blob/ef7f3a7b3f5e1e495ecf415f151a5b573d633109/magefiles/magefile.go#L58) which is used to …

chore: update GH repo name to prevent auto-cleanup

---

tests/release/pipelines/push_to_external_registry.go
tests/release/pipelines/rh_push_to_external_registry.go
tests/release/service/happy_path.go

We should not be replacing the global public key, there are tests that rely that the `public-key` Secret corresponds to the `signing-secrets` Secret in the `openshift-pipelines` namespace.
[KFLUXBUGS-1555](https://issues.redhat.com/browse/KFLUXBUGS-1555)
It was not

fix: do not overwrite the global public key

---

integration-tests/scripts/konflux-e2e-runner.sh

openshift-ci takes care of unregistering PaC server in a [separate step](https://github.com/openshift/release/blob/1cafdb8605e559c8b2f174d25927eaa401bbf212/ci-operator/step-registry/konflux-ci/unregister-sprayproxy/konflux-ci-unregister-sprayproxy-commands.sh#L16). So we need to update the e2e script to take care of it
N/A
in CI 🤷

fix: unregister PaC server after konflux-ci test run

---

pkg/clients/has/components.go
pkg/constants/constants.go

* When a build PLR, due to some reason, fails, we have a util function that retriggers it if we like.
* But when a GitLab-based build PLR fails, that retrigger function throws an error.
* This is because the projectID, used to create a dummy file in the comp branch, is an empty string.
* This PR fixes this situation by pointing the projectID to the 'hacbs-test-project-integration' GitLab repo
Note: This does mean that when a different GitLab repo is used as a component URL and it fails on its 1st attempt, then the retrigger call would fail too due to the URL conflict with the 'hacbs-test-project-integration' GitLab repo.
[KFLUXBUGS-1533](https://issues.redhat.com/browse/KFLUXBUGS-1533)
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. …

fix(KFLUXBUGS-1533): GitLab build PLR fails on retrigger due to empty projectID

---

tests/enterprise-contract/contract.go

The golden-container image is no longer built into the quay.io/redhat-appstudio organization. Instead, it is now built into quay.io/konflux-ci. The image from the redhat-appstudio organization is now stale.
https://issues.redhat.com/browse/KFLUXBUGS-1575

fix: Use new location for golden-container image

---

.tekton/konflux-e2e-tests-pull-request.yaml
.tekton/konflux-e2e-tests-push.yaml
go.mod
pkg/utils/build/task_results.go

As part of [STONEINTG-931](https://issues.redhat.com//browse/STONEINTG-931) we marked sbom-json-check as deprecated in build-defnitions, removing it from templates, leaving just information to customer about how to remove that task from their pipeline.
We no longer need to test for this task since it will be removed.

feat(STONEINTG-931): remove sbom-json-check

---

go.mod
magefiles/magefile.go
magefiles/rulesengine/engine/engine.go
magefiles/rulesengine/readme.md
magefiles/rulesengine/repos/common.go
magefiles/rulesengine/repos/e2e_repo.go
magefiles/rulesengine/repos/infra_deployments.go
magefiles/rulesengine/repos/release_service_catalog.go
magefiles/rulesengine/repos/rule_demo.go
magefiles/rulesengine/types.go
magefiles/utils.go
pkg/utils/util.go

* introduced CI Rule Chain **for e2e-tests repo** (CI Rule Chains for other repositories - infra-deployments, integration-service etc. - will follow in other PRs) that replaces the messy code in `magefile.go`
* updated the [`Eval` method signature](https://github.com/konflux-ci/e2e-tests/compare/main...psturc:[KONFLUX-3902](https://issues.redhat.com//browse/KONFLUX-3902)-e2e-tests?expand=1#diff-2435cc2f992f298a556c7d35d119ae02f1899dbd6d0715106267bc5fbfe5760bR307) to return also an `error` type when evaluating conditions
* eventually we will create rules for every repository where we run e2e tests, and once it's done, duplicated code from magefile.go will be removed
[KONFLUX-3902](https://issues.redhat.com//browse/KONFLUX-3902)
locally by mocking the CI-provided values:
```
export …
```

feat: e2e-tests repo CI rule chain

---

magefiles/magefile.go
magefiles/rulesengine/engine/engine.go
magefiles/rulesengine/repos/common.go
magefiles/rulesengine/repos/e2e_repo.go
magefiles/rulesengine/repos/integration_service.go
magefiles/rulesengine/types.go

* follow-up on https://github.com/konflux-ci/e2e-tests/pull/1344
* added integration-service repository specific CI rule
* updated `runLoadedCatalog` method to fix the bug when iterating over rule catalog wasn't terminated right away after rule chain evaluation passed
[KONFLUX-3902](https://issues.redhat.com//browse/KONFLUX-3902)
```
export KONFLUX_CI=true
export COMPONENT_IMAGE=quay.io/redhat-user-workloads/rhtap-integration-tenant/integration-service/integration-service@sha256:75c4356e8fdefea826e067b18e0f8d816911d547f48bd876e5b9fa89c50d517f
export JOB_SPEC='{
"container_image": "quay.io/redhat-user-workloads/konflux-qe-team-tenant/konflux-e2e/konflux-e2e-tests@sha256:70adb47a4e050232cbc53cbcd3b1e8db07e806e5cf083f355afbcebbf9cfba01",
"konflux_component": "konflux-e2e-tests",
"git": { …
```

feat: integration-service repo CI rule

---

pkg/clients/release/releases.go
pkg/utils/tekton/pipelineruns.go
tests/release/pipelines/fbc_release.go
tests/release/pipelines/multiarch_advisories.go
tests/release/pipelines/release_to_github.go
tests/release/pipelines/rh_advisories.go
tests/release/pipelines/rh_push_to_redhat_io.go
tests/release/pipelines/rhtap_service_push.go

Increase the timeout in WaitForReleasePipelineToBeFinished.
Increase the ticker time for refreshing token.
Add the FailedTaskRunName to the log.

chore: several changes for release pipelines

---

integration-tests/tasks/konflux-e2e-tests-task.yaml

Instead of creating oras-credentials secret in every namespace, start to use the credentials stored in vault to push to OCI- Registry. 

chore: Mount konflux test infra volume to access oci storage

---

default.env
pkg/clients/gitlab/git.go
pkg/clients/has/components.go
pkg/constants/constants.go
pkg/utils/build/git.go
tests/build/build.go
tests/build/build_templates.go
tests/build/const.go
tests/build/jvm-build.go
tests/build/multi-platform.go
tests/integration-service/gitlab-integration-reporting.go

- Add GitLab coverage for the `test PaC component build` path in the build tests (more can be added the same way in a new PR since this one is already complex enough)
- Every test case in the `test PaC component build` path is now ran for each git provider
- Add env vars originally created for `gitlab-integration-reporting` to the default env file
- Add new variables to the `tests/build/const.go` file relevant for the new tests
[STONEBLD-2388](https://issues.redhat.com/browse/STONEBLD-2388)
Added `Focus` decorator to the changed `DescribeTableSubtree` node and ran `make build && ./bin/e2e-appstudio`

feat: add GitLab coverage for PaC component build tests

---

pkg/constants/constants.go
tests/release/const.go

This commit adds the placeholder {{ OCP_VERSION }} to the indexes used by the FBC Release pipeline e2e test.
Required by https://github.com/konflux-ci/release-service-catalog/pull/502

fix(KFLUXBUGS-1416): FBC fragment released to the wrong OCP version

---

go.mod
pkg/clients/oras/client.go
tests/build/build_templates.go
tests/build/multi-platform.go

Require https://github.com/konflux-ci/build-definitions/pull/1129 to be merged.
[STONEBLD-2522](https://issues.redhat.com//browse/STONEBLD-2522)

feat: check pushed Dockerfile

---

.github/workflows/PR.yaml

- upload-sarif GA is failing with error `Error: Unable to upload "results.sarif" as it is not valid SARIF:` for which a upstream issue https://github.com/securego/gosec/issues/1214 is open, using gosec version of 2.20 temporarily, till it is fixed in upstream
- seeing a warning like `Warning: CodeQL Action v2 will be deprecated on December 5th, 2024. Please update all occurrences of the CodeQL Action in your workflow files to v3. For more information, see https://github.blog/changelog/2024-01-12-code-scanning-deprecation-of-codeql-action-v2/ `, so updated workflow to use v3 of upload-sarif action
NA

fix: Pin gosec and upgrade upload-sarif action

---

tests/release/pipelines/fbc_release.go
tests/release/releaseLib.go

1. Remove useless left code 
2. Change the way of handling failure in the loop of waiting pipelineRun finished
3. Increase the duration of refreshing token

fix(RELEASE-1149): e2e keeps checking pipelinerun even if it failed

---

magefiles/rulesengine/repos/infra_deployments.go

This PR fixes the scenario that was not triggering the right test suites  : 
- any file in `components/build-service `  was changed 
lead to applying `build-service` label even when only files under components/build-service/base/build-pipeline-config/* are changed
also the fix is for the scenario where : 
- any files `components/build-service/base/build-pipeline-config/* `are changed 
- any file unde build-service and not in `components/build-service/base/build-pipeline-config/*`  
it will add the `build-service`  and  `build-templates` label as expected 

feat(KONFLUX-3187): infra-deployments test selection fix 

---

tests/build/build_templates.go
tests/build/build_templates_scenarios.go

for hermetic builds, the original Dockerfile is modified and the one pushed to quay with `.dockerfile` tag is the modified one, does not match the original Dockerfile in the repo, so skipped the check till the issue [STONEBLD-2795](https://issues.redhat.com//browse/STONEBLD-2795) is fixed
https://issues.redhat.com/browse/STONEBLD-2795
https://github.com/konflux-ci/build-definitions/pull/1410

fix: skip the dockerfile check for hermatic and fbc scenarios

---

tests/load-tests/evaluate.py
tests/load-tests/run-max-concurrency.sh

If all the journeys failed, do not compute avg KPI time.
If we had 0 measurements in some metric, that means not a single build made it through all steps, so kpi_sum metric does not make sense as it would only cover part of the journey.
N/A
- Bug fix (non-breaking change which fixes an issue)
Just local run of the script on data that trigger the issue.

fix: If all the journeys failed, do not compute avg KPI time

---

tests/load-tests/ci-scripts/utility_scripts/github-org-cleanup-repos.py

This adds script to list and remove GitHub repos in organization so we can do manual cleanups as needed
N/A
- New feature (non-breaking change which adds functionality)
Locally, cleaning repos in "rhtap-perf-test" in multiple iterations

feat: Script to list and remove GitHub repos in org

---

tests/load-tests/run-max-concurrency.sh
tests/load-tests/run.sh

Adds a check to ensure that errors in [loadtest.go](https://github.com/konflux-ci/e2e-tests/blob/main/tests/load-tests/loadtest.go) is captured. Also based on its non-zero status code, the test execution is terminated.
[KONFLUX-997](https://issues.redhat.com/browse/KONFLUX-997)
Manually evaluated part of the code change by running through success and failure scenarios.

fix(KONFLUX-997): Adds a check to handle loadtest.go errors

---

tests/release/const.go

[STONEBLD-2339](https://issues.redhat.com//browse/STONEBLD-2339)
All the images built in build-definitions CI now get released to the
quay.io/konflux-ci organization.
Replace the relevant redhat-appstudio[-tekton-catalog] references in
this repo with konflux-ci[/tekton-catalog] references.
Signed-off-by: Adam Cmiel <acmiel@redhat.com>

chore: migrate build-definitions redhat-appstudio images

---

tests/build/build_templates.go
tests/build/build_templates_scenarios.go

Observed that multiple component/pipelineruns getting created for the symlink component test after [this PR](https://github.com/konflux-ci/e2e-tests/pull/1384) got merged, we expect to run symlink component with only one pipeline bundle `docker-build`, since it is just a negative scenario
NA
Locally

fix: skip creating multiple component for symlink test

---

magefiles/magefile.go
magefiles/rulesengine/engine/engine.go
magefiles/rulesengine/repos/release_service.go
tests/release/const.go

feat(RELEASE-1172): add a mage engine rule for release-service

---

tests/release/pipelines/multiarch_advisories.go
tests/release/pipelines/rh_advisories.go
tests/release/pipelines/rh_push_to_redhat_io.go
tests/release/pipelines/rhtap_service_push.go

This commit change the repository value from quay* to registry*
in RPA mapping. This was implemented in release-238.

feat(RELEASE-1147): update repository to registry.redhat.io in rpa

---

tests/build/build_templates.go
tests/enterprise-contract/contract.go

We removed the YAML output in [EC-568](https://issues.redhat.com/browse/EC-568), this is a followup to use the JSON logs instead.
Resolves: https://issues.redhat.com/browse/EC-885
n/a

feat(EC-885): step-report to step-report-json

---

integration-tests/scripts/konflux-e2e-runner.sh

I saw the docker pull issue in test cluster recently
it affected not only the `minio-operator` ns, but also` tekton-results`
This PR adds docker pull secret to both of those namespaces to avoid the docker pull limit issue
N/A 
in CI 🤷

fix: add docker secret to tekton-results and minio

---

tests/build/build_templates.go

[STONEBLD-2795](https://issues.redhat.com//browse/STONEBLD-2795)
Hermetic builds should now push the original dockerfile, not the modified one. Enable the check.

feat: enable dockerfile check for hermetic builds

---

pkg/utils/tekton/pipelineruns.go
tests/release/const.go

The terminated reason can be "TaskRunImagePullFailed", so adding the condition check for similar reasons.

fix: add more checking in getfailedtask

---

pkg/clients/has/components.go

`RetriggerComponentPipelineRun` was failing for gitlab build test with below error
```
unable to retrigger pipelinerun for component build-e2e-vulo-tenant:gl-test-custom-branch-evasji: failed to retrigger PipelineRun gl-test-custom-branch-evasji-on-pull-request-t4t8p in build-e2e-vulo-tenant namespace: error when creating file contents: response (&{0xc0015f9950 0 0 0 0 0 0    }) and error: POST XXXXXXXXXXXXXXXXXXXXXXXXX/projects/konflux-qe/hacbs-test-project-integration/repository/files/aweow: 400 {message: You can only create or edit files when you are on a branch}
```
https://issues.redhat.com/browse/KFLUXBUGS-1615

fix: re-trigger pipeline run failure issue

---

magefiles/magefile.go
magefiles/rulesengine/engine/engine.go
magefiles/rulesengine/repos/image_controller.go

feat(KONFKUX-4009): Add mage engine rules for image-controller repo

---

magefiles/magefile.go

By default ginkgo use colors in the output and that uglify that logs and make them confused

feat: add no-color flag to e2e tests

---

tests/integration-service/gitlab-integration-reporting.go

* Removes the unused PaC secret in the GitLab test suite.
* But that is not the root cause, still finding that one...
[KFLUXBUGS-1487](https://issues.redhat.com//browse/KFLUXBUGS-1487)

fix(KFLUXBUGS-1487): Duplicated build PLRs in GitLab e2e test

---

tests/build/build_templates.go

The EC test in build-definitions was failing because the PipelineRun was garbage collected mid-test, so the logs that are asserted were not available.
This uses a finalizer lock on the PipelineRun to make sure it is still present while the logs are asserted in the test scenario.
Ran with this version in build-definitions on https://github.com/konflux-ci/build-definitions/pull/1460

fix: use finalizer lock in EC build-definitions

---

pkg/sandbox/sandbox.go

When we are creating 100 users in Load test in CI cluster it takes 30+ iterations to create first user. Adding 1 second delay will lower amount of output we are getting from this function given the price of about 0.5 seconds longer user creation.
N/A
- New feature (non-breaking change which adds functionality)
I rely on CI, running some jobs with this change in https://github.com/konflux-ci/e2e-tests/pull/1382

feat: Lower number of iterations when creating user

---

magefiles/magefile.go
magefiles/rulesengine/engine/engine.go
magefiles/rulesengine/repos/common.go
magefiles/rulesengine/repos/release_service_catalog.go
tests/release/const.go

feat(RELEASE-1205): create engine rule for release catalog

---

magefiles/rulesengine/repos/common.go

we still see these escaped characters in the e2e tests output:
```
Will run [1m6[0m of [1m327[0m specs
Running in parallel across [1m20[0m processes
[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m
[38;5;243m------------------------------[0m
[38;5;11mP [PENDING][0m
```
setting the ReporterConfig's `NoColor` field to `true` should fix this
N/A
in CI 🤷

fix: add --no-color to rules

---

pkg/clients/oras/client.go
pkg/utils/build/task_results.go

Add validation for the `REPORTS` result emitted by the clair-scan Task.
https://issues.redhat.com/browse/EC-839

feat: verify REPORTS result from clair-scan Task

---

tests/load-tests/ci-scripts/max-concurrency/cluster_read_config.yaml

The PR adds additional PromQL to max-concurrency metric collector config. 
https://issues.redhat.com/browse/KONFLUX-4965
Successfully tested the changes by running max-concurrency builds on Hive cluster.
```
export THRESHOLD=1500 MAX_THREADS=200 MAX_CONCURRENCY_STEPS=1 COMPONENT_REPO=https://github.com/rh-perf-test-org/devfile-sample PIPELINE_REQUEST_CONFIGURE_PAC=true
./tests/load-tests/ci-scripts/max-concurrency/load-test.sh
./tests/load-tests/ci-scripts/max-concurrency/collect-results.sh
```

fix(KONFLUX-4965): add prometheus metrics to max-concurrency collector

---

tests/load-tests/run-stage-max-concurrency.sh

Follow up change based on https://github.com/konflux-ci/e2e-tests/pull/1382
Remove non-PAC build configs from `run-stage-max-concurrency.sh` script and use the latest templating env variable.
[KONFLUX-4272](https://issues.redhat.com//browse/KONFLUX-4272)
Bug fix (non-breaking change which fixes an issue)
Locally tested the changes against stage cluster.
```
source user.env
export THRESHOLD=3500 MAX_THREADS=300 MAX_CONCURRENCY_STEPS=2 COMPONENT_REPO=https://github.com/rh-perf-test-org/devfile-sample RUN_ON_STAGE=true
./tests/load-tests/ci-scripts/max-concurrency/load-test.sh
./tests/load-tests/ci-scripts/max-concurrency/collect-results.sh
```
I have performed a self-review of my code.

feat(KONFLUX-4272): Update latest PaC config in run-stage-max-concurrency.sh

---

pkg/clients/common/controller.go
pkg/clients/git/git.go
pkg/clients/git/github.go
pkg/clients/git/gitlab.go
pkg/utils/build/git.go

- The common controller currently contains Github and Gitlab clients
- Their functions differ
- Make the clients implement a provider-agnostic Git client interface so that provider-agnostic functions can be used in tests
[STONEBLD-2389](https://issues.redhat.com/browse/STONEBLD-2389)
This change is not being tested in this particular revision. I've used the functionality created in this pull request in build tests, please see the following PRs: https://github.com/konflux-ci/e2e-tests/pull/1419, https://github.com/konflux-ci/e2e-tests/pull/1421

feat: create generic git client interface

---

tests/build/build.go

It is currently not possible to merge a PR with multiple commits without squashing them. Created https://github.com/konflux-ci/e2e-tests/pull/1418 that should be merged before this, so we can avoid squashing
- Nudging functionality is currently only
being tested for GitHub repositories
- Switch to Git provider-agnostic functions
and test GitLab repositories too
[STONEBLD-2389](https://issues.redhat.com/browse/STONEBLD-2389)
Added `Focus` to the changed tests and ran e2e-tests.

feat: add tests for nudging gitlab repos

---

go.mod
go.sum
pkg/clients/release/plans.go
tests/integration-service/integration.go
tests/konflux-demo/konflux-demo.go
tests/release/pipelines/fbc_release.go
tests/release/pipelines/multiarch_advisories.go
tests/release/pipelines/push_to_external_registry.go
tests/release/pipelines/release_to_github.go
tests/release/pipelines/rh_advisories.go
tests/release/pipelines/rh_push_to_external_registry.go
tests/release/pipelines/rh_push_to_redhat_io.go
tests/release/pipelines/rhtap_service_push.go
tests/release/service/happy_path.go
tests/release/service/release_plan_and_admission_matched.go
tests/release/service/release_plan_owner_ref.go
tests/release/service/tenant_pipelines.go

feat: update createReleasePlan function

---

tests/release/pipelines/multiarch_advisories.go
tests/release/pipelines/rh_advisories.go

This commit fixes two data fields in the multiarch advisories release pipeline test. The product_id field is changed from a string to an int, and the component source is removed from the data section of the ReleasePlanAdmission. The same component source information already appears to be present in the create snapshot function.

fix: update release multiarch data fields

---

pkg/clients/release/releases.go

The name of the release file was  added a wrong prefix.  It's to change it to the correct one.

fix: typo in restoreRelease

---

tests/release/pipelines/multiarch_advisories.go
tests/release/pipelines/rh_advisories.go

The release service pipeline suite tests that use advisories do not attach CVEs. Thus, they should not use RHSA type.

fix: release advisory pipelines should use RHBA

---

go.mod
go.sum
pkg/clients/git/git.go
pkg/clients/git/github.go
pkg/clients/git/gitlab.go
tests/build/build.go

It is currently not possible to merge a PR with multiple commits without squashing them. Created https://github.com/konflux-ci/e2e-tests/pull/1418 that should be merged before this, so we can avoid squashing
Use generic, provider-agnostic, Git client functions leading to a nicer, more readable and maintainable code
N/A
`./bin/e2e-appstudio --ginkgo.v --ginkgo.label-filter=build-service`

refactor: use generic client in gitlab build tests

---

.github/workflows/PR.yaml

fix: bump golanci-lint action

---

tests/build/build_templates.go

To help debug the current issue on build-definitions CI, this PR increase the timeout of PR creation to 20 mins and also skip deleting the branches created while running tests
https://issues.redhat.com/browse/STONEBLD-2981

chore: increase timeout and skip removing branches

---

tests/build/build.go

Reverts konflux-ci/e2e-tests#1445 since the issue was fixed in https://github.com/konflux-ci/build-service/pull/363

chore: Revert "skip multicomponent test with same git url"

---

tests/load-tests/ci-scripts/collect-results.sh
tests/load-tests/ci-scripts/stage/collect-results.sh
tests/load-tests/pkg/journey/handle_collections.go

Application and Component JSON definitions were not being captured during load test execution because the objects were cleared when the `--purge` flag was set. 
This PR addresses the issue by moving the collection of Application and Component JSON definitions to the component handler level.
https://issues.redhat.com/browse/KONFLUX-4319
The changes have been tested successfully on Hive OpenShift cluster.
```
source user.env 
./tests/load-tests/ci-scripts/setup-cluster.sh
export COMPONENT_REPO=https://github.com/rh-perf-test-org/devfile-sample CONCURRENCY=1 APPLICATIONS_COUNT=2 COMPONENTS_COUNT=2
./tests/load-tests/ci-scripts/load-test.sh
```
At end of the load test, we should be able to find `collected-application-*.json` and `collected-component-*.json` files with the object definition …

feat(KONFLUX-4319): Capture Application & Component JSONs after load test

---

pkg/clients/has/components.go
pkg/clients/integration/pipelineruns.go
tests/integration-service/const.go
tests/integration-service/group-snapshots-tests.go
tests/integration-service/integration.go

Adding a multirepo and single repo(multicomponent) scenarios for creation of group snapshot.
Reduce the triplication of component A, B and C into one for loop to reduce code amount.
Include gitLab repo for scenario of multiple repos having a group snapshot.

feat(STONEINTG-1009): e2e tests for group snapshot

---

tests/release/pipelines/fbc_release.go

feat(RELEASE-1199): fbc release e2e should contain the test for staged

---

magefiles/rulesengine/repos/e2e_repo.go
pkg/utils/build/source_image.go
tests/build/build_templates_scenarios.go

This PR adds the `docker-build-multi-platform-oci-ta` pipeline test back, fixes the rule to run build tests 
https://issues.redhat.com/browse/KFLUXBUGS-1646
Tested it [here](https://github.com/konflux-ci/build-definitions/pull/1465)

fix: add docker-build-multi-platform-oci-ta pipeline test

---

integration-tests/scripts/konflux-e2e-runner.sh

this should fix the konflux bootstrap issue recently seen on ROSA HCP cluster:
```
Failed to pull image "timberio/vector:0.42.0-distroless-libc": fetching target platform image selected from image index: reading manifest sha256:872e4daa04a347d61841cc387f0b56ea7e3031f9b2eb2ca2e0a936696d7def3c in docker.io/timberio/vector: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
```

fix: add docker.io creds to tekton-logging ns

---

integration-tests/scripts/konflux-e2e-runner.sh
pkg/constants/constants.go
tests/release/pipelines/rh_advisories.go
tests/release/pipelines/rh_push_to_redhat_io.go
tests/release/releaseLib.go

In [ISV-5130](https://issues.redhat.com//browse/ISV-5130), the `rh-advisories` pipeline gained the ability to upload component and product-level SBOMs to the Atlas release instance.
The upload of SBOMs requires a new k8s Secret containing the SSO account and token for the stage [Atlas release instance](https://atlas.release.stage.devshift.net/). **The secrets have been added to the QE vault.**
This PR makes the e2e test use the new secrets and refactors secret creation to avoid duplicate code. I left the other tests use the old way of creating the secrets but I can refactor those as well if you wish.
[ISV-5130](https://issues.redhat.com/browse/ISV-5130) - Add new pipeline steps in rh-advisories for sbom upload 
[ISV-5394](https://issues.redhat.com/browse/ISV-5394) - Update rh-advisories …

feat(ISV-5130): add Atlas secrets to e2e tests

---

tests/release/pipelines/fbc_release.go

Correct the type of some values in the data of RPA for FBC test case

fix: update some values in the data of RPA for FBC

---

integration-tests/scripts/konflux-e2e-runner.sh
integration-tests/tasks/konflux-e2e-tests-task.yaml

* added `make ci/prepare/e2e-branch` to `integration-tests/tasks/konflux-e2e-tests-task.yaml` to determine the git reference for running `integration-tests/scripts/konflux-e2e-runner.sh`, which will solve the issue with PR pairing described in [KFLUXBUGS-1917](https://issues.redhat.com//browse/KFLUXBUGS-1917)
* the `integration-tests/tasks/konflux-e2e-tests-task.yaml` Task now contains only a code that's necessary for logging into OCP cluster and configuring PR pairing - most of the code that might change is then located in `integration-tests/scripts/konflux-e2e-runner.sh`, which will be possible to test from e2e-tests and konflux components' PRs
* CI in this PR is irrelevant, the functionality was tested in [this PR](https://github.com/konflux-ci/build-service/pull/377) …

fix: PR pairing

---

pkg/clients/tekton/pipelineruns.go
pkg/clients/tekton/taskruns.go
tests/release/pipelines/rh_advisories.go

chore: store taskRuns in rh_advisiories

---

tests/integration-service/group-snapshots-tests.go
tests/integration-service/integration.go
tests/integration-service/status-reporting-to-pullrequest.go

fix: improve Cleanup function

---

Dockerfile
integration-tests/pipelines/konflux-e2e-tests-pipeline.yaml
integration-tests/scripts/konflux-e2e-runner.sh
integration-tests/tasks/konflux-e2e-tests-task.yaml

* use new versions of tasks for (de)provisioning ROSA clusters and stepactions for pushing artifacts to OCI storage
* remove `create-oci-container` task, because it's not needed anymore, since [**secure-push-oci** stepaction detects whether it's needed to create a new OCI artifact](https://github.com/konflux-ci/tekton-integration-catalog/blob/168d270f154b72b42aff1973ca754939df6895d8/stepactions/secure-push-oci/0.1/secure-push-oci.yaml#L62) or use existing one
* the change was tested in a previous commit ([which was referencing the current PR git URL and branch](https://github.com/konflux-ci/e2e-tests/pull/1475/commits/af569d60b4c7ca82e7fce31d859c3a4de2859ba7#diff-b95cbbb0088e1a08e6e3983fd72cf84eeeb1b822379e1fa092fcc4c9dd0cddc4L120)) - the OCI artifact including the logs from this PR is …

feat: use secure-push-oci for archiving artifacts

---

integration-tests/pipelines/konflux-e2e-tests-pipeline.yaml

The konflux-ci pipeline should now use test results analysis which provides more information on the PR about the test failure
https://issues.redhat.com/browse/KFLUXDP-42

feat: enable ci-helper-app

---

tests/release/pipelines/rh_advisories.go

The name of the Atlas k8s secret is changed to reflect the collect-atlas-params task in the advisories pipeline.

fix(ISV-5130): use correct atlas secret name

---

pkg/constants/constants.go

This url is used in the RPA and it's used for Tekton git resolver. All the RPAs in konflux-release-data repo use the .git suffix and it's also what's used
as an example in Tekton docs.
For context, a user recently hit an issue:
https://github.com/konflux-ci/release-service-catalog/pull/759
We had a bug that caused an issue with the .git suffix. But e2e didn't expose the problem because the .git suffix was not there.

fix: git repo url should have .git suffix

---

tests/release/pipelines/fbc_release.go
tests/release/pipelines/release_to_github.go
tests/release/pipelines/rh_push_to_redhat_io.go
tests/release/pipelines/rhtap_service_push.go

Add storeTaskLogs to some test cases running against staging cluster
in release pipelines

chore: add storeTaskLogs for test cases

---

magefiles/magefile.go
tests/build/build_templates_scenarios.go

Source build task got changed and broken into two steps, leading to wrong behavior when running `make setup-source-build` , this PR will fix the issue
Part of https://issues.redhat.com/browse/STONEBLD-2991
Locally

fix: make target setup-source-build

---

tests/release/pipelines/multiarch_advisories.go

The PR is for refactoring multiarch test case to create new application and other CRs each time instead of binding to a fixed application and related CRs. It's to fit for the testing based on PR which may include some changes for the CRs, such as RPA.

refactor: multiarch_advisories to create new app each time

---

integration-tests/scripts/konflux-e2e-runner.sh

quick workaround for
```
Failed to pull image "docker.io/bitnami/os-shell:11-debian-11-r96": reading manifest 11-debian-11-r96 in docker.io/bitnami/os-shell: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
```
long-term we need to get rid of docker.io dependency to prevent these issues - tracked [here](https://issues.redhat.com/browse/KFLUXDP-133)
* after initial fix for tekton-results namespace I found out 2 more updates were needed:
* add pull secret to `default` SA in `product-kubearchive` namespace
* update `vectors-tekton-logs-collector` SA name in tekton-logging to `vector-tekton-logs-collector`

fix: docker.io creds to tekton-results postgres SA

---

tests/konflux-demo/README.md
tests/konflux-demo/config/scenarios.go
tests/konflux-demo/const.go
tests/konflux-demo/konflux-demo.go

* update konflux-demo test to be compatible with both downstream (infra-deployments) and upstream (konflux-ci/konflux-ci) versions of konflux
[KONFLUX-3683](https://issues.redhat.com//browse/KONFLUX-3683)
Tested the code changes also in konflux-ci repo in [this check run](https://github.com/konflux-ci/konflux-ci/pull/1156/checks)

fix: adapt konflux-demo for konflux-ci

---

magefiles/rulesengine/repos/build_service.go
magefiles/rulesengine/repos/common.go
magefiles/rulesengine/repos/image_controller.go
magefiles/rulesengine/repos/integration_service.go
magefiles/rulesengine/repos/release_service.go

Extend functinality to add via COMPONENT_IMAGE images like: quay.io/redhat-user-workloads/rhtap-build-tenant/build-service/build-service@sha256:20ca83111840a28c870750d576a4e2bdf0c8452f2ed3e1a21a64b9f2cbba580d
This images contain the tag name and the sha

feat(KFLUXDP-108): Allow to pass via COMPONENT_IMAGE env images with tag and sha

---

tests/load-tests/cluster_read_config.yaml

tekton-pipelines-controller pods are now owned by StatefulSet now, so their name is not like `tekton-pipelines-controller-[0-9a-f]+-.*` (e.g. `tekton-pipelines-controller-679f858ccf-w5p9s`), but `tekton-pipelines-controller-[0-9]+` (e.g. `tekton-pipelines-controller-0`).
None
- Bug fix (non-breaking change which fixes an issue)
Not tested, will use CI job here.

fix: Match new tekton-pipelines-controller pod name as it is handled by StatefulSet now

---

pkg/clients/github/repositories.go

Getting this:
```
I0127 20:47:45.961453   24251 logging.go:66] FAIL(80): Repo forking failed: Error renaming XXXXXXXXXXXXXXX/nodejs-devfile-sample-1 to nodejs-devfile-sample-cidaily-61000-0002: PATCH https://api.github.com/repos/XXXXXXXXXXXXXXX/nodejs-devfile-sample-1: 422 Validation Failed [{Resource:Repository Field:name Code:custom Message:name a repository operation is already in progress}]
```
Looks like we need to retry when renaming the repo here.
None
- New feature (non-breaking change which adds functionality)
It was not tested, will run CI job here

feat: Retry if renaming failed with 'name a repository operation is already in progress' error

---

default.env
integration-tests/scripts/konflux-e2e-runner.sh
integration-tests/tasks/konflux-e2e-tests-task.yaml

Adds sealights stepactions to e2e tests.

feat(KFLUXDP-140): Add logic to the tekton task that add a new step to send results to sealights

---

pkg/utils/build/sbom.go
tests/build/build_templates.go

Support unmarshalling the show-sbom task output into either CycloneDX or SPDX models. Do similar assertions for both SBOM formats.
https://issues.redhat.com/browse/STONEBLD-3051
Temporary commit in https://github.com/konflux-ci/build-definitions/pull/1865

feat: Support SPDX SBOMs

---

tests/build/tkn-bundle.go

It will enable the tkn-bundle test and retry the fetchImage step, which was failing intermittently
https://issues.redhat.com/browse/KONFLUX-5760

chore: enable tkn-bundle test 

---

tests/build/build.go

Recently in the periodic executions of the e2e-tests, below test started to fail frequently
` [FAIL] [build-service-suite Build service E2E tests] test PaC component build gitlab when the PaC init branch is merged [It] After updating image visibility to private, it should not trigger another PipelineRun [build-service, github-webhook, pac-build, pipeline, image-controller, build-custom-branch]`
one such example is [here](https://prow.ci.openshift.org/view/gs/test-platform-results/logs/periodic-ci-redhat-appstudio-infra-deployments-main-appstudio-e2e-tests-periodic/1884693173121323008).
It might be due the deletion of pipelineruns [here ](https://github.com/konflux-ci/e2e-tests/blob/6aa3c66ddd2e0fda956f898f7828c13ca8400f12/tests/build/build.go#L549) is taking longer time, increasing the …

fix: increase the wait time for no new pipelines gets triggered check

---

tests/load-tests/ci-scripts/max-concurrency/cluster_read_config.yaml
tests/load-tests/cluster_read_config.yaml

Collect additional ETCD metrics for loadtest. 
This is a follow up on PR https://github.com/konflux-ci/e2e-tests/pull/1502, this changes adds the metrics to the default load test and max-concurrenct scenarios.
https://issues.redhat.com/browse/KONFLUX-6576
Tested the changes through GitHub Actions in Konflux Staging and confirmed that below metrics are being collected.

feat(KONFLUX-6576): Collect ETCD metrics for loadtest

---

pkg/constants/constants.go
tests/enterprise-contract/contract.go

fix the failed test in [enterprise-contract-suite Enterprise Contract E2E tests] test creating and signing an image and task verify-enterprise-contract task Release Policy [It] verifies redhat products pass the redhat policy rule collection before release  [ec, pipeline]
delete var OldTektonTaskTestOutputName as https://issues.redhat.com/browse/RHTAP-810 is completed 

fix: ec golden-image check and delete OldTektonTaskTestOutputName

---

pkg/clients/github/git.go
tests/build/build.go

CleanupWebhook call [here](https://github.com/konflux-ci/e2e-tests/blob/f042c509583ad36ff31cb2b5f90df25e1858e0e3/tests/build/build.go#L952) not working properly, updated github org needed for the test, so that it works correctly. Also removed few deprecated functions.
N/A
Locally.

fix: update github org needed for the test

---

integration-tests/scripts/konflux-e2e-runner.sh

Setting the secret data (dockerconfigjson) immediately after creating the secret was causing error `the object has been modified; please apply your changes to the latest version and try again`. This commit reduces the secret content only to the docker.io registry, which should be sufficient
N/A, the issue came from [the report on slack](https://redhat-internal.slack.com/archives/C02FANRBZQD/p1740492413809459)
in CI 🤷

fix: docker pull secret linking

---

integration-tests/pipelines/konflux-e2e-tests-pipeline.yaml
integration-tests/scripts/konflux-e2e-runner.sh
integration-tests/tasks/konflux-e2e-tests-task.yaml

when e2e-tests Task times out, the artifact archiving is skipped. we need to configure a reasonable timeout for the make command for running tests to prevent this issue
https://issues.redhat.com/browse/KFLUXDP-199
I previously tested it by purposely [configuring 5 minute timeout](https://github.com/konflux-ci/e2e-tests/commit/c9776ae7861c20b238f95d80c1895cecf84e6db3)
* see the [test results analyzer message from that test run](https://github.com/konflux-ci/e2e-tests/pull/1532#issuecomment-2723760537)
* see the [archived e2e-tests.log in the artifact browser](https://app-artifact-browser.apps.rosa.konflux-qe.zmr9.p3.openshiftapps.com/e2e-tests/2025-03-14_06-25-13+konflux-e2e-kfps6/e2e-tests.log)

fix: add timeout for bootstrap & e2e

---

.github/workflows/PR.yaml
Dockerfile
docs/Installation.md
go.mod
go.sum
integration-tests/pipelines/konflux-e2e-tests-pipeline.yaml

to address the issue seen in bootstrap script
```
Installing ksctl from master
GOBIN=/tmp/toolchain-e2e/build/_output/bin CGO_ENABLED=0 go install github.com/kubesaw/ksctl/cmd/ksctl@master
go: github.com/kubesaw/ksctl/cmd/ksctl@master: github.com/kubesaw/[ksctl@v0.0.0-20250314110631-f896cfc64cdc](mailto:ksctl@v0.0.0-20250314110631-f896cfc64cdc) requires go >= 1.22.0 (running go 1.21.11; GOTOOLCHAIN=local)
make[4]: *** [make/ksctl.mk:70: install-ksctl] Error 1
```
([full log](https://app-artifact-browser.apps.rosa.konflux-qe.zmr9.p3.openshiftapps.com/build-service/2025-03-14_11-39-13+konflux-e2e-build-service-2dm47/e2e-tests.log))
caused by [this commit](https://github.com/kubesaw/ksctl/commit/05340f3c63c84364bbc029b62fe6b2c817fb3f0f#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec071671 …

fix: bump go version to v1.22

---

integration-tests/scripts/konflux-e2e-runner.sh

a follow-up on the bug introduced in https://github.com/konflux-ci/e2e-tests/pull/1532
see [this thread](https://redhat-internal.slack.com/archives/C07PZ0U12MA/p1741970053027719?thread_ts=1741963509.543829&cid=C07PZ0U12MA) for more details
```bash
bash-5.1# set -o pipefail
bash-5.1# E2E_TIMEOUT=1s
bash-5.1# ARTIFACT_DIR=/tmp
bash-5.1# timeout "$E2E_TIMEOUT" bash -c "make ci/test/e2e 2>&1 | tee ${ARTIFACT_DIR}/e2e-tests.log"
make: *** No rule to make target 'ci/test/e2e'.  Stop.
bash-5.1# echo $?
0
bash-5.1# timeout "$E2E_TIMEOUT" make ci/test/e2e 2>&1 | tee "${ARTIFACT_DIR}/e2e-tests.log"
make: *** No rule to make target 'ci/test/e2e'.  Stop.
bash-5.1# echo $?
2
```

fix: exit status of timeout command

---

integration-tests/tasks/konflux-e2e-tests-task.yaml

Sealights recommendations are to open the session before running the ginkgo tests.

feat: Initialize Test Session ID just before running Ginkgo tests

---

tests/build/tkn-bundle.go

This test is failing consistently in CI [here](https://github.com/redhat-appstudio/infra-deployments/pull/5929)
https://issues.redhat.com/browse/KONFLUX-7413

chore: disable tkn-bundle test

---

pkg/clients/common/secret.go
tests/release/releaseLib.go

Creating the Secret only if it didn't exist caused updates in the vault values to be ignored. This bug was discovered in this slack discussion: https://redhat-internal.slack.com/archives/C02CTEB3MMF/p1742898268213099

fix: always update secret

---

pkg/constants/constants.go
pkg/utils/build/custom_bundle.go
pkg/utils/tekton/bundle.go
tests/build/build.go
tests/build/build_templates.go
tests/build/build_templates_scenarios.go
tests/integration-service/gitlab-integration-reporting.go
tests/integration-service/integration.go
tests/konflux-demo/config/scenarios.go
tests/konflux-demo/config/types.go
tests/konflux-demo/konflux-demo.go
tests/load-tests/pkg/journey/handle_component.go
tests/release/releaseLib.go

* add option to use oci-ta bundle in e2e tests
* update konflux-demo test to test `docker-build-oci-ta` pipeline
https://issues.redhat.com/browse/KONFLUX-5837
in CI 🤷

feat: add option to use oci-ta-bundle

---

pkg/clients/github/pull_request.go
pkg/clients/has/components.go
tests/integration-service/const.go
tests/integration-service/status-reporting-to-pullrequest.go

* reflect build PLR failure to integration test status in git
* Use GetComponentPipelineRunWithType instead of GetComponentPipelineRun to void getting integration test
* Fix GetComponentPipelineRunWithType in has controller

feat(STONEINTG-1114): reflect build PLR failure to intg status in git

---

.github/workflows/loadtest.yaml
tests/load-tests/pkg/journey/handle_component.go

- Introduce new env variable in Github Action Runner `USER_START_INDEX` to control the starting user to test from users.json
- Add template variable `REPOURL` to replace Git URL for the forked repository.
https://issues.redhat.com/browse/KONFLUX-7535
Tested in RH01 Konflux Staging with Github Action

feat(KONFLUX-7535): New variable for GH action & PaC templating

---

pkg/clients/common/secret.go
tests/load-tests/pkg/journey/handle_purge.go

Cleanup MPC secrets as well if any
https://issues.redhat.com/browse/KONFLUX-3854

fix(KONFLUX-3854): Cleanup MPC secrets as well if any

---

pkg/framework/framework.go
pkg/utils/build/git.go
tests/build/build.go
tests/build/const.go
tests/integration-service/const.go
tests/integration-service/group-snapshots-tests.go

This PR fixes the buid test which used `appstudio-pipeline` SA, replaced it by component SA, also the temporary change of creating `use-new-sa` will be removed when the migration is complete.
commit 5cd18330e8c9f72363748985d62177890205140b addresses two intermittent CI issues in the e2e-tests.
https://issues.redhat.com/browse/STONEBLD-3263
Locally deployed dev cluster

fix: SA per component test changes

---

integration-tests/tasks/konflux-e2e-tests-task.yaml

It's to avoid  "[ERROR] The process for bootstrapping the cluster and running tests timed out after 90m"

chore: increase e2e_timeout to 150m

---

pkg/constants/constants.go
tests/konflux-demo/konflux-demo.go

There is a change in konflux-ci/build-service to reduce confusion when onboarding new components to Konflux (branch prefix from "appstudio" to "konflux").
New component branch prefix should be changed from "appstudio" to "konflux". This change should fix failing e2e tests in a build-service pipeline.
Related PR in build-services:
https://github.com/konflux-ci/build-service/pull/427
https://issues.redhat.com/browse/KONFLUX-7681
I've made the change in my fork and ran the pipeline in build-services.
Tested in this PR: https://github.com/konflux-ci/build-service/pull/427
Link to the pipeline run: https://console.redhat.com/application-pipeline/workspaces/rhtap-build/applications/build-service/pipelineruns/konflux-e2e-build-service-dwpck

fix(tests): change PaC pull request branch prefix

---

tests/build/build_templates.go

change the f.AsKubeAdmin to kubeadminClient in build-template.go([https://github.com/konflux-ci/e2e-tests/blob/83bce4d17de1c212a8dcba7022376b5732f54fba/tests/build/build_templates.go#L656]).
As https://github.com/konflux-ci/e2e-tests/blob/83bce4d17de1c212a8dcba7022376b5732f54fba/tests/build/build_templates.go#L222-L234 shows kubeadminClient is initialized using  f.AsKubeAdmin. To keep the consistent, kubeadminClient is better.

fix: Align f.AsKubeAdmin to kubeadminClient in build-template

---

magefiles/magefile.go
magefiles/rulesengine/repos/release_service_catalog.go

Release-service-catalog periodic test is triggered by adding label to an "on-push" snapshot, the PR is to add handling for "push" event of release-service-catalog repo. The "staging" branch in `https://github.com/konflux-ci/release-service-catalog` repo is expected to be tested.  

feat(RELEASE_1316): enable periodic job for release_service_catalog

---

pkg/utils/tekton/pipelineruns.go
tests/release/pipelines/rh_push_to_redhat_io.go

It's to fix the panic issue - one [example](https://app-artifact-browser.apps.rosa.konflux-qe.zmr9.p3.openshiftapps.com/release-service-catalog/konflux-e2e-tests-catalog-l468n/e2e-tests.log)

fix: panic when s.Terminated is nil

---

tests/integration-service/README.md
tests/integration-service/gitlab-integration-reporting.go

As reported, pipelineruns are still running by the time they are expected to be finished, this could be caused by slower gitlab instance on cluster(higher traffic). Increasing timeouts could reduce this issue.
See log below as an example.
https://prow.ci.openshift.org/view/gs/test-platform-results/logs/periodic-ci-redhat-appstudio-infra-deployments-main-appstudio-e2e-tests-periodic/1920630229852753920
Also updating readme.md file with added content from [STONEINTG-853](https://issues.redhat.com//browse/STONEINTG-853)

fix(STONEINTG-853): Increasing PLR wait timeout

---

tests/integration-service/README.md
tests/integration-service/status-reporting-to-pullrequest.go

Add suite to cover the push event integration test results  reporting in main 
- add a new suite in status-reporting-to-pullrequest to cover push event to main
- Updated the README with the new suite
[STONEINTG-852](https://issues.redhat.com/browse/STONEINTG-852)

feat(STONEINTG-852): add coverage for commit push event

---

magefiles/magefile.go
magefiles/rulesengine/repos/release_service_catalog.go
magefiles/rulesengine/scripts/find_release_pipelines_from_pr.sh
magefiles/rulesengine/types.go
tests/release/pipelines/fbc_release.go
tests/release/pipelines/multiarch_advisories.go
tests/release/pipelines/rh_push_to_external_registry.go
tests/release/pipelines/rh_push_to_registry_redhat_io.go

This PR is to be smart to select  e2e test cases according to the change in the PR. It can reduce some unrelated test cases to be executed for the PR in release-service-catalog.  
* Changed test labels to the name of the pipelines being tested in release-pipelines suite
* Added find_release_pipelines_from_pr.sh to select test cases according files changed in the PR
* Changed actions to add selectReleasePipelinesTestCases function for ReleaseServiceCatalogCIRule
Related PR: the PR [949](https://github.com/konflux-ci/release-service-catalog/pull/) 

feat(RELEASE-1343): smart selecting test cases for release pipelines suite

---

magefiles/rulesengine/repos/common.go

Reverts konflux-ci/e2e-tests#1548
we needed this just for a temporary debugging, it is no longer needed now

Revert "feat: Enable debug mode for ginkgo tests to detect Sealights issues"

---

Makefile

icm-injection-scripts were moved from build-tasks-dockerfles to buildah image
(commit ref: buildah commit ref: https://github.com/konflux-ci/buildah-container/commit/36236360f7b794a446828a02108592413e4e9ba4) 
we don't want to run the test in build-tasks-dockerfiles

ci: disable icm-injection-scripts test in build-tasks-dockerfiles

---

pkg/clients/common/namespace.go
pkg/constants/constants.go

Some Konflux components use namespace label for finding namespaces which are used by Konflux tenants.
Add the labels for namespaces which are created as part of the e2e-tests.

fix: label tenant namespaces

---

magefiles/rulesengine/repos/release_service_catalog.go

With DEPLOY_ONLY set, konflux deployment often hang at [line](https://github.com/redhat-appstudio/infra-deployments/blob/2228e063a7fd8af4a95b24bb13ce7360cdc229f0/hack/preview.sh#L293C16-L293C38). 
This PR is to avoid the issue.

chore: deploy konflux failed with tekton components missing

---

tests/integration-service/gitlab-integration-reporting.go

Segregation using when prevents from canceling integration pipelineruns. Passed 10/10 times on local cluster.

fix(STONEINTG): prevent canceling intg pipelineruns

---

integration-tests/pipelines/konflux-e2e-tests-pipeline.yaml
tests/build/build.go
tests/release/pipelines/fbc_release.go
tests/release/pipelines/multiarch_advisories.go
tests/release/pipelines/push_to_external_registry.go
tests/release/pipelines/release_to_github.go
tests/release/pipelines/rh_advisories.go
tests/release/pipelines/rh_push_to_registry_redhat_io.go
tests/release/pipelines/rhtap_service_push.go
tests/release/service/happy_path.go
tests/release/service/missing_release_plan_and_admission.go
tests/release/service/tenant_pipelines.go

1. Remove appstudio-pipeline SA since the SA will not be used by default
and it will not exist any more.  
2. Change the timeout value for CI job of the e2e-tests repo.

feat: remove appstudio-pipeline SA from release suite

---

tests/build/build.go

Component on-boarding failed in CI, due to test repos reached maximum webhook limit of 100
```
2025-05-15T16:11:13.327Z        ERROR   ComponentOnboarding     controller/component_build_controller.go:384    Pipelines as Code provision transient error     {"controller": "ComponentOnboarding", "controllerGroup": "appstudio.redhat.com", "controllerKind": "Component", "Component": {"name":"gl-multi-component-child-fzzm","namespace":"build-e2e-nucq-tenant"}, "namespace": "build-e2e-nucq-tenant", "name": "gl-multi-component-child-fzzm", "reconcileID": "8dc20337-998e-4436-b0a9-d3e01354c950", "ComponentGitSource": {"url":"https://gitlab.com/konflux-qe/build-nudge-child","revision":"multi-component-child-base-fzzm","dockerfileUrl":"Dockerfile"}, "error": "POST …
```

fix: cleanup hooks in after all block

---

pkg/clients/release/releases.go

When Release CR failed to be create, StoreRelease function will panic when it is called in AfterAll part. The PR is to fix the issue by moving the function in other place.

fix: panic in StoreRelease when Release CR is nil

---

magefiles/rulesengine/scripts/find_release_pipelines_from_pr.sh

When there is no test case related to the PR under test, it returns "no-test-case" instead of "happy-path".

chore: no test case will be ran when it's expected

---

tests/release/pipelines/multiarch_advisories.go
tests/release/pipelines/rh_advisories.go

The rh_advisories happy path previously only accepted URLs starting with https://access.redhat.com/errata. It has now been updated to only support support https://access.stage.redhat.com/errata for stage releases.
https://github.com/konflux-ci/release-service-catalog/pull/1003

feat(KONFLUX-8347): update rh_advisories pattern

---

Dockerfile

after openshift-ci started to use this repository's dockerfile for building the e2e-tests image, we ran into permission issues due to $GOBIN directory location in the filesystem
$GOPATH env var is in fact empty, so the $GOBIN then points to `/bin` which openshift-ci SA does not have write permissions to
This PR should fix it

fix: GOBIN location

---

Dockerfile

follow-up on https://github.com/konflux-ci/e2e-tests/pull/1612
fixes this issue
```
exec: go "install" "-mod=mod" "github.com/onsi/ginkgo/v2/ginkgo"
go: downloading github.com/go-task/slim-sprig/v3 v3.0.0
go: downloading github.com/google/pprof v0.0.0-20240424215950-a892ee059fd6
github.com/onsi/ginkgo/v2/ginkgo: go install github.com/onsi/ginkgo/v2/ginkgo: mkdir /opt/app-root/src/bin/: permission denied
```
tested locally

fix: e2e test runner permissions

---

pkg/clients/has/components.go

We are observing below errors in build-definitions CI. Temporary workaround is to increase timeout, but there is a filled story to investigate and found a permanent solution.
```
timed out when waiting for image-controller annotations to be updated on component 
```
https://issues.redhat.com/browse/STONEBLD-3552

fix: increase imageRepository create timeout

---

tests/build/build.go

After the successful execution, when application was deleted, the components were not deleted in correct order, it might be the cause for not cleanup of the gitlab webhooks related to the components, I think cleaning up of the component in correct order can help resolve this issue.
https://issues.redhat.com/browse/STONEBLD-3537
Locally.

fix: graceful cleanup of components

---

tests/build/tkn-bundle.go

* task/0.1/tkn-bundle.yaml is archived in https://github.com/konflux-ci/build-definitions/pull/2344 which causes tkn-bundle case fail with "task/tkn-bundle/0.1/ tkn-bundle.yaml": file does not exist'" in tkn-bundle test
* user task/0.2/tkn-bundle task

fix: use tkn-bundle 0.2 in tkn-bunde test

---

tests/enterprise-contract/contract.go

conforma team removed attestation_task_bundle package in this pr: https://github.com/conforma/policy/pull/1442 which lead to test scenario: Task bundles are in acceptable bundle list and  Task bundle references pinned to digest failed.
updated the test case ecp.
https://issues.redhat.com/browse/KONFLUX-9270

fix: update test cases due attestation_task_bundle remove

---

tests/enterprise-contract/contract.go

https://github.com/conforma/policy/commit/f7f1fc327fe120e0713eea19ccb6c8b174d6ef5d changes [‎policy/release/trusted_task/trusted_task.rego](https://github.com/conforma/policy/commit/f7f1fc327fe120e0713eea19ccb6c8b174d6ef5d#diff-6dcf5d6bef661f9aa3b5b8230f6a5a8aa2572da36b38330870bfca1cb803e2fe)
```
error := {
"msg": sprintf(
"Pipeline task %q uses an untrusted task reference, %s",
[tekton.pipeline_task_name(task), _task_info(task)],
),
"term": tekton.task_name(task),
}
```
to 
```
_format_trust_error(task) := error if {
latest_trusted_ref := tekton.latest_trusted_ref(task)
untrusted_pipeline_task_name := tekton.pipeline_task_name(task)
untrusted_task_name := tekton.task_name(task)
untrusted_task_info := _task_info(task)
error := {
"msg": sprintf(
"PipelineTask %q uses an untrusted task …
```

fix: match PipelineTask according for test case: Task are trusted

---

tests/build/build_templates.go

The show-sbom Task is now optional and no longer included within the default build pipelines. This removes the tests that require that Task to be present.

fix: remove tests for show-sbom Task

---

pkg/utils/contract/policy.go
tests/build/build_templates.go

This PR adds `@redhat` ec rule collection with some exceptions to be used while running tests in build-definitions CI
https://issues.redhat.com/browse/STONEBLD-3188
In build-definitions CI by creating custom image

fix: ec-rule used during in build-definitions CI

---

Makefile
magefiles/magefile.go

we have removed the `sbom-utility-script` and `icm-injection-scripts` image from the build-task-dockerfiles repo. This PR removes the code to setup bundles with these two images. 
https://issues.redhat.com/browse/STONEBLD-3695

chore: cleanup make target and code

---

pkg/clients/common/namespace.go
pkg/clients/tekton/rekor_hosts.go
pkg/clients/tekton/tekton_chains_public_keys.go
pkg/constants/constants.go
pkg/framework/framework.go
tests/enterprise-contract/contract.go

During test namespace creation, create also a rolebinding that allows default konflux-ci user to access test namespaces via konflux-ui:
This could be helpful when debugging tests, because konflux-ci doesn't offer kubernetest dashboard (UI) by default
https://issues.redhat.com/browse/KFLUXDP-377
locally after running an integration-service test (see the screenshot above)

feat: allow konflux-ci user to access test ns

---

go.mod
magefiles/rulesengine/repos/common.go

parse the amount of ginkgo procs passed to e2e via [this env var](https://github.com/konflux-ci/e2e-tests/blob/fb1e7653b7f550e005161d46c71bfc5476d48010/integration-tests/tasks/konflux-e2e-tests/0.2/konflux-e2e-tests.yaml#L136)
N/A
in [this PR](https://github.com/konflux-ci/e2e-tests/pull/1656/files)

fix: configure ginkgo procs based on env var

---

pkg/clients/has/components.go
pkg/clients/integration/pipelineruns.go
tests/integration-service/group-snapshots-tests.go
tests/integration-service/pipelinerun-resolution.go

* Update resolution e2e case steps
* Reduce the calls: 
add sleep before getting build PLR state since a build PLR need at least 6+ mins to complete
enlarge the interval when getting build/integration PLR, especially for integration resolution e2e case when getting final integration test
[STONEINTG-1332](https://issues.redhat.com/browse/STONEINTG-1332)

fix: integration-service e2e case improvement

---

magefiles/rulesengine/repos/infra_deployments.go
tests/build/build_templates.go

This test was disabled [here](https://github.com/konflux-ci/e2e-tests/pull/1642/files#diff-420007369ea2e1a8133dc8c9a8fc032202afa2a4fc08e7f8753701ae4ab87333R468) after toolchain was removed from e2e-tests
We had to change the way this test works, it now uses the tekton results API directly instead of toolchain API
This PR also enabled this test to run on pipeline-service updates in infra-deployments
[KFLUXDP-373](https://issues.redhat.com//browse/KFLUXDP-373)
```
ginkgo build ./cmd && ginkgo -v --label-filter "pipeline-service" ./cmd/cmd.test
```

fix: enable tekton results test for downstream

---

pkg/clients/integration/pipelineruns.go
tests/integration-service/const.go
tests/integration-service/gitlab-integration-reporting.go
tests/integration-service/group-snapshots-tests.go
tests/integration-service/integration.go
tests/integration-service/pipelinerun-resolution.go
tests/integration-service/status-reporting-to-pullrequest.go

* enlarge the timeout and interval when polling plr status change
* don't use has.WaitForComponentPipelineToBeFinished to get build plr
status because it retrigger build plr sometimes
* disable resolution e2e case temporarily to improve it

fix(STONEINTG-1332-1): integration e2e case improvement

---

tests/konflux-demo/konflux-demo.go

TTSIA
Reason is that this test case dramatically increases the test duration in sanity-test job in konflux-ci repo (which has lot less cluster resources available compared to infra-deployments clusters)

fix: remove retriggering of PLR from upstream test

---

tests/build/build_templates.go
tests/build/build_templates_scenarios.go

First commit was accidentally reverted
Second commit is fixing missing OverrideMediaType in DeepCopy implementation

fix: OverrideMediaType to properly update BUILDAH_FORMAT

---

tests/integration-service/gitlab-integration-reporting.go

* This note doesn't consistently show up in gitLab MRs even though the build pipelines do get triggered eventually
Signed-off-by: dirgim <kpavic@redhat.com>

fix: remove build note check in integration gitlab reporting
